### ISSUE TITLE
uploading images

### ISSUE THREAD

**Issue by alexsandr1992** [tinymce/tinymce-react#100]
Hi,
Where to find an example of configuration component Editor for image upload ?
I mean that is possible to show browser files dialog and upload selected file on server

**Comment by SimonFc** [comment]
Hi @alexsandr1992 
Perhaps you're looking for the "[Image & file upload options](https://www.tiny.cloud/docs/configure/file-image-upload/)" docs page. There's not any examples with tinymce-react specifically but everything should work the same (with a few syntactic differences). As for an example with the browsers file picker, here's [one](https://www.tiny.cloud/docs/demo/file-picker/). Is this what you're looking for?

**Comment by jenqtat-mpd** [comment]
Hi, i would like to know how to add file_picker_callback function in the <Editor> as well

**Comment by SimonFc** [comment]
@jenqtat-mpd _file_picker_callback_ is covered pretty extensively on the docs page I linked to and there's an example of it on the demo page I linked to. At what step(s) are you having difficulties?

**Comment by jenqtat-mpd** [comment]
@SimonFc is my bad. As I thought the "file_picker_callback" is one of the property in Editor like "onChange". Anyhow I mange to figure out that I can declare at init.

@alexsandr1992 a sample of having the image upload button appear on the dialog

             <Editor
                     apiKey=""                  
                      initialValue="<p>This is the initial content of the editor</p>"
                      plugins="advlist autolink lists link image charmap print preview anchor
                              searchreplace visualblocks code fullscreen
                              insertdatetime media table paste code help wordcount"
                      init={{
                        height: 500,
                        toolbar:
                          'undo redo | formatselect | bold italic backcolor | \
                          alignleft aligncenter alignright alignjustify | \
                          bullist numlist outdent indent | removeformat | image',
                        file_picker_callback: function(callback, value, meta) {
                          // Provide file and text for the link dialog
                          if (meta.filetype == 'file') {
                            callback('mypage.html', {text: 'My text'});
                          }
                          
                          // Provide image and alt text for the image dialog
                          if (meta.filetype == 'image') {
                            callback('myimage.jpg', {alt: 'My alt text'});
                          }

                          // Provide alternative source and posted for the media dialog
                          if (meta.filetype == 'media') {
                            callback('movie.mp4', {source2: 'alt.ogg', poster: 'image.jpg'});
                          }
                        }

                     }}
                     onChange={this.handleEditorChange}
                   />

**Comment by Shaker-Hamdi** [comment]
If that would help you, here's how I did it ...

```
<Editor
	initialValue={field.value}
	init={{
		height: 300,
		menubar: false,
		plugins: ["advlist autolink lists link anchor paste image"],
		paste_as_text: true,
		mobile: {
			toolbar_drawer: "floating"
		},
		file_picker_types: "file image media",
                toolbar="bold italic | \
				alignleft aligncenter alignright alignjustify | \
				bullist numlist outdent indent | image | removeformat"
		images_upload_handler: async function(
			blobInfo: any,
			success: any,
			failure: any
		) {
			let imageFile = new FormData();
			imageFile.append("files[]", blobInfo.blob());

			try {
                                const {data} = await axios.post("http://urlToHandleFileUpload", imageFile)
				success(data.fileURL);
			} catch (error) {
				handleResponseError(error);
				return;
			}
		}
	}}
	{...field}
	{...restProps}
	onEditorChange={content => setFieldValue(field.name, content)}
/>
```

Please note that `handleResponseError(error);` is just a function of my own to handle errors and display a toaster, but you can implement your own error handler.

**Comment by SimonFc** [comment]
Closing this as it doesn't appear to be an issue anymore

**Comment by JamersonAguiarOSF** [comment]
I have done it like this
```
<Editor
  ref={ref}
  apiKey={API_KEY}
  init={{
    plugins: PLUGINS,
    toolbar: TOOLBAR,
    toolbar_mode: 'sliding',
    images_upload_handler: async blobInfo => {
      return new Promise((resolve, reject) => {
        uploadFile(blobInfo)
          .then(data => {
            const { url } = data;
            resolve(url);
          })
          .catch(e => {
            showToast({
              type: 'error',
              message: ERROR_UPLOADING_IMAGE,
            });
            reject(e);
          });
      });
    },
    setup,
  }}
  {...props}
/>
```
Hope it helps.

**Comment by RUPAAK** [comment]
@JamersonAguiarOSF yours one is correct as latest version if Tiny for react reuires promises.  But when I try to save that image url  (returned from my api), it gives me "Cannot read properties of undefined (reading 'nodeName')" error. Can you help me on that. Yeah it is on react js

**Comment by tiny-james** [comment]
This would have changed with the release of TinyMCE 6.
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#images_upload_handler

In TinyMCE 5 the images_upload_handler used a `success` and `failure` callback. In TinyMCE 6 it expects a Promise to be returned.

**Comment by Kagin007** [comment]
> This would have changed with the release of TinyMCE 6. https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#images_upload_handler
> 
> In TinyMCE 5 the images_upload_handler used a `success` and `failure` callback. In TinyMCE 6 it expects a Promise to be returned.

Thank you! Saved me

**Comment by Ahmad495** [comment]
I'm trying to upload file from the backend. But the issue i'm facing is not with the upload. File gets uploaded. But Tinymce shows it as broken image. Does any one have idea about this.

**Comment by xuananh2212** [comment]
This is the code image:
![image](https://github.com/tinymce/tinymce-react/assets/91230849/ed51e9f4-4ea4-4af7-9126-383dc299ee2d)
This is the error image:
![image](https://github.com/tinymce/tinymce-react/assets/91230849/05246616-838c-4c21-a958-09c303cb3d45)
Calling the api has no error:
![image](https://github.com/tinymce/tinymce-react/assets/91230849/8d6dd7a5-76f9-49d4-a13c-8ac4c6af4c5c)
This is the fault, everyone

**Comment by OtavioCanedoSOITIC** [comment]
@xuananh2212 I'm with the same error, had you fix it?

**Comment by denis-yoyo** [comment]
Previously the **images_upload_handler** option passed success or failure callbacks to report the status of an image upload. In TinyMCE 6, images_upload_handler reports upload results by returning a Promise.

In order to solve the issues above, I made it run with this code:

`export const imagesUploadHandler = async (blobInfo) => {
  const file = blobInfo.blob();
  return new Promise(async (resolve, reject) => {
    try {
      const data = await fileService.rteFileUpload(file) as any;

      if (data && data.data && data.data.url) {
        const image = {
          location: data.data.url,
          alt: data.data.description || '',
          width: 300,
          height: '',
        };

        resolve(data.data.url); 
      } else {
        const errorMessage = 'Upload failed, please try again.';
        reject(errorMessage); 
        showErrorNotification(errorMessage);
      }
    } catch (e) {
      const errorMessage = 'An error occurred during upload: ' + e.message;
      reject(errorMessage); 
      showErrorNotification(errorMessage);
    }
  });
};`
