### ISSUE TITLE
Responsive toolbar doesn't work on mobile or window reload.

### ISSUE THREAD

**Issue by Shaker-Hamdi** [tinymce/tinymce-react#102]
Hello.

When loading any page on mobile with Tinymce in it, the editor doesn't respect the width of the window and the toolbar doesn't get the three dots menu (...).

To reproduce this, just look at the basic example on the website, try to resize your browser window and everything works great, the editor will behave fine and the toolbar will get the three dots menu and everything, but now try to reload the page while you're on mobile view, the editor will not be responsive.

https://www.tiny.cloud/docs/demo/basic-example/

**Comment by lnewson** [comment]
@Shaker-Hamdi this appears to be fine when testing locally. It's worth noting though, that mobile will default to using a scrolling toolbar to avoid taking up valuable screen space (we do have a task open to make it more visible that it's a scrolling toolbar though). So if you really want it to use the toolbar drawer, then you'll need to add something like the following to your init configuration, to override the mobile default:

```
mobile: {
  toolbar_drawer: 'floating'
}
```

**Comment by Shaker-Hamdi** [comment]
Thanks a bunch, that actually fixes my responsive issues. Where can I find the rest of the "mobile" configuration options object? I tried to search for it, but with no luck.

**Comment by lnewson** [comment]
Any valid TinyMCE setting can be used inside the `mobile` block. The defaults for mobile are documented here: https://www.tiny.cloud/docs/mobile/#mobiledefaultsforselectedsettings

**Comment by yc-codes** [comment]
`toolbar_drawer` is deprecated

```js
mobile: {
  toolbar_mode: 'floating',
}
// or
mobile: {
  toolbar_mode: 'wrap',
}
```
