### ISSUE TITLE
#Question: How to set default font-family and font-size for the generated elements?

### ISSUE THREAD

**Issue by Shaker-Hamdi** [tinymce/tinymce-react#104]
I noticed that the generated `<p>` and `<span>` elements have an inline style with `font-family` set to `Open sans` and `font-size` set to `14px`.

![image](https://user-images.githubusercontent.com/3071511/73594321-f5483000-4515-11ea-9265-319ddd18d17c.png)
How can I change these default values?

I tried to `fullpage_default_font_family` in the `init` object but didn't work. I also tried setting this in the `init` but didn't work either ...
```
invalid_styles: {
    "*": "color font-size" // Global invalid styles
}
```

I also tried `content_style` but didn't work.

If anyone has an example of how to make this work it would be great.

**Comment by SimonFc** [comment]
That's an odd combination of styles (margin?), how have you applied the values?

If you have been using the fontselect and fontsizeselect dropdowns then you're able to change the values used with the [font_formats](https://www.tiny.cloud/docs/configure/editor-appearance/#font_formats) and [fontsize_formats](https://www.tiny.cloud/docs/configure/editor-appearance/#fontsize_formats) settings. Is this what you're looking for? If not, please describe how you arrived at these inline styles and I'll see if I got some ideas

**Comment by Shaker-Hamdi** [comment]
@SimonFc I didn't apply any CSS, I only used the component with these options (Using Formik) ...

```
<Editor
	initialValue={field.value}
	init={{
		height: 300,
		menubar: false,
		plugins: ["advlist autolink lists link anchor"],
		mobile: {
			toolbar_drawer: "floating"
		}
		toolbar:
		     "bold italic | \
		 	alignleft aligncenter alignright alignjustify | \
		 	bullist numlist outdent indent | removeformat"
	}}
	{...field}
	{...restProps}
	onEditorChange={content => setFieldValue(field.name, content)}
/>
```

And I got the styles in the screenshot above.
All I need is to change the default `Open sans` font family and default font-size.

**Comment by SimonFc** [comment]
TinyMCE will not apply any inline font-size nor font-family styles to paragraphs so I'm not sure how you ended up with that. See if you can modify this [demo](https://codesandbox.io/s/tinymcereact-dj6cq?fontsize=14&hidenavigation=1&theme=dark) so as to reproduce the issue you have. What browser are you using btw?

**Comment by Shaker-Hamdi** [comment]
@SimonFc You know what? that was a very dumb mistake from my side, it turns out I was copying and pasting text from lorem ipsum that already had these styles in it.

I'm so sorry for bothering you. And thanks for your patience and response, I wouldn't have caught this dumb mistake if it wasn't for this discussion :D

**Comment by SimonFc** [comment]
No worries, happy I was be able to help!:) And great that you found the issue
