### ISSUE TITLE
#Question: How to make the "Image Upload" the default tab

### ISSUE THREAD

**Issue by Shaker-Hamdi** [tinymce/tinymce-react#107]
Hello, I have a question that I couldn't find an answer to.

I'm using the upload image feature (great feature by the way), and everything works great, I just need two things ...

First: How to make the upload tab is the default one?
Second: How to change the text of the popup `.tox`? 

![image](https://user-images.githubusercontent.com/3071511/74106749-da0e9d80-4b71-11ea-8c5d-60c795ca1240.png)

Is there any config for that?

**Comment by SimonFc** [comment]
Unfortunately TinyMCE doesn't provide any config for changing the structure and content of already defined UI components. The only way to get full control over this is to implement your own [dialog](https://www.tiny.cloud/docs/ui-components/dialog/) using the UI framework TinyMCE provides. (Not that it's a simple solution, you would still have to provide the functionality either by implementing everything from the ground up yourself or by forking the image plugin)

**Comment by hiepnn-rk** [comment]
First: How to make the upload tab is the default one?

you can set language by

```
tinymce.init({
    language: "fa_IR",
    language_url: "/langs/fa_IR.js",
    directionality :"rtl",      
});
```
Download the language pack you wish to use from [here](https://www.tiny.cloud/get-tiny/language-packages/).
