### ISSUE TITLE
Option to not set content to initialValue on load

### ISSUE THREAD

**Issue by charlesverge** [tinymce/tinymce-react#11]
When content is already in the html the initialValue over writes the content. Having an option to not do this would be ideal.

One suggestion is if initialValue is null than don't set the content.

**Comment by fyrkant** [comment]
Yeah this makes sense, I'll look into it and try to fix it today.

**Comment by fyrkant** [comment]
@charlesverge 
Thinking about this, I'm not sure I understand when the html can already have content, becase the `<Editor />` just creates the element that it initializes on so it will never already have content?

**Comment by charlesverge** [comment]
For example if a page like this, you would normally init with a selector of .editable and tinymce will create the two editors. But with requiring the <Editor> Tag you need to add it twice and try and stuff everything into a string.

<h1>Title of page</h1>
<p>Non editable content</p>
<div class="editable">This is default text, please click here to type</div>
<p>Non editable content</p>
<div class="editable">This is more default text, maybe you want to edit maybe not
<p>Test</p>
<table>some complex html you don't want to enter into a string</table>
</div>

**Comment by fyrkant** [comment]
In a react app you can't do it like that, you would have to have the editable content in state and switch between showing it in paragraphs tags, divs or whatever or in a `@tinymce/tinymce-react` Editor component.

**Comment by charlesverge** [comment]
Then the react way seams it would look more fluid like

```
<h1>Title of page</h1>
<p>Non editable content</p>
<Editor>This is default text, please click here to type</Editor>
<p>Non editable content</p>
<Editor>This is more default text, maybe you want to edit maybe not
<p>Test</p>
<table>some complex html you don't want to enter into a string</table>
</Editor>
```

**Comment by fyrkant** [comment]
Sure, but then it's just the same as using the `initialValue`, right? I could make it so that all child html would be turned into the initial value but I'm not sure it would make sense and would probably break if someone puts another react component inside of it. 🤔

**Comment by charlesverge** [comment]
Yes, another react component inside that would be problematic.

The specific use case that I'm looking at likely an edge case where templates with non editable and editable content are loaded. These templates are initially created by non programmers, so having the content entered into a string becomes either a manual task of converting html to reactjs, a dynamically loaded reactjs component which was created by phasing a html template for the .editable selector or using dangerouslySetInnerHTML and modifying the reactjs tincy component.

Non react tinymce this is a simple thing to do. With reactjs component it becomes this round about way of getting to the same result.

**Comment by fyrkant** [comment]
You could create a wrapping component around the `tinymce-react` component so you can get the functionality you wanted above, so something like this: 

```js
import ReactDomServer from 'react-dom/server';
import {Editor} from '@tinymce/tinymce-react';

const SuperEditor = (props) => {
  const convertedChildren = ReactDomServer.renderToStaticMarkup(props.children);

  return <Editor initialValue={convertedChildren} {...props} />;
};
```

But I'm not sure how good it would be to use the react-dom/server stuff on the client, that was just something I googled my way to in a few minutes 😅

**Comment by charlesverge** [comment]
@fyrkant That looks like a interesting solution. Though, my requirements are to have a dynamic amount of editors on a single page which load content from the div's. It looks like it is out of the scope of this component as using the selection causes an miss alignment with the handlers. ie on changes content is returned but there is not a away to tell which editor's content has changed.

The solution for me now currently is to disable the initialValue in a fork and the current method to retrieve the content of all the editors with 

```javascript
  saveContent() {
    let content = $('.content').clone();
    content.find('.inlineedit').each(function (i, e) {
      let id = e.getAttribute('id');
      console.log('content for id = ' + id + ' ' + window.tinymce.editors[id].getContent());
    });
  }
```

**Comment by fyrkant** [comment]
Sounds like you might be better off just using tinymce without the react wrapper. Anyway, I don't see this as an issue with the wrapper so I'll close this issue.

**Comment by charlesverge** [comment]
@fyrkant Thanks for the help!
