### ISSUE TITLE
React Hooks - How to get Editor instance?

### ISSUE THREAD

**Issue by bluefire2121** [tinymce/tinymce-react#113]
Simple question.

I'm trying to cache files in the file_picker_callback before they're saved to my server, but I can't seem to get the editor instance.

`    init={{
          file_picker_callback: handleFilePicker,
          setup: (editor: any) => setActiveEditor(editor) 
 }}`

https://www.tiny.cloud/docs/demo/file-picker/#

I've tried using setup to hold the editor instance in a useState() to no avail. Should I use a reference instead i.e. useRef()?

**Comment by SimonFc** [comment]
Obtaining a reference to the editor via the setup method and storing it using useState() should work, as should storing a reference to the editor in a component state or just as a property if you're using a class-component. In what way can't you "get the editor instance"?

**Comment by bluefire2121** [comment]
When is the editor initiated? 

Or perhaps it is and I need to wrap the **file_picker_callback** in a useCallback() to obtain its details. Right now my activeEditor is empty whenever I reference it inside my file picker handle.

**Comment by bluefire2121** [comment]
Follow up:
**init_instance_callback** isn't returning an editor.id so I guess it's not being initialized correctly.

**Comment by bluefire2121** [comment]
Yeah the class based approach works. I was just wondering how to do it with hooks. 

I'll use the class you provided for now as I can at least grab the instance that way. 

Thank you @SimonFc for the help.

**Comment by SimonFc** [comment]
It should work in a similar manner, just grap the editor in the onInit callback and pass it to your state-hook.

Awesome, I'll close this then. And no problem!

**Comment by bluefire2121** [comment]
I think it's related to 
Duplicate of #65 

It exists onBlur, but oddly doesn't exist in file_picker. 

At least there's a work around with classes. 

Thx again!

**Comment by SimonFc** [comment]
You mean that the editor doesn't exist on the file_picker_callback method? Yeah the editor is given as the second argument to all event handlers for the tinymce-react component. The file_picker_callback method in the init object is part if "vanilla" TinyMCE and doesn't follow this API pattern. It's understandable that this can cause some confusion.
