### ISSUE TITLE
ReactJS Editor wont render JavaScript content

### ISSUE THREAD

**Issue by WinWinHost** [tinymce/tinymce-react#12]
Hi All,

I have project that I am working on, and part of it is a plugin / javascript editor.
The tinyMCE container never renders the value!
I've had to move this project to a private repo.

But here it the public version before:
https://github.com/WinWinHost/mqtt-data-generator

Basically this is a MERN project and in the FormAlgorithms.js component I am NOT able to render and edit JavaScript. There is no error displayed or reason given. Just a blank TinyMCE.

But the tinyMCE area always remains blank, even though on the console I can see the content is being retrieved correctly.

Here is the JS, which is rendering a blank TinyMCE.
```
      <Editor 
          content={this.state.fileContents}
          config={{
            plugins: 'autolink link image lists print preview',
            toolbar: 'undo redo | bold italic | alignleft aligncenter alignright'
          }}
          onChange={this.handleInputChange}
        />
```
And here is the output of this.state.fileContents:
```
'use strict';

const autoregressive = (previousObservation, currentSensorObservations, algorithmConfig) => { // jshint ignore: line
  return {
    value: previousObservation ? previousObservation.value : undefined
  };
};

module.exports = autoregressive; 
```

Thanks in Advance for your help.

-Robert Baindourov

**Comment by fyrkant** [comment]
`content` isn't a valid prop on the Editor component, so that won't work, but even if you used the correct prop `initialValue` that will probably not work as you expect it. TinyMCE is an HTML editor, so it won't work just giving it a string of javascript, you will have to add it inside of some kind of html tag (a `pre` maybe?).

**Comment by fyrkant** [comment]
Sounds like you should use something like codemirror instead of TinyMCE, maybe this wrapper is good? https://github.com/JedWatson/react-codemirror

**Comment by fyrkant** [comment]
Yeah try it out, I think it's more what you want!
