### ISSUE TITLE
Is there a way to pass a callback to Editor Component once it is mounted.

### ISSUE THREAD

**Issue by milap1296** [tinymce/tinymce-react#120]
**Is your feature request related to a problem? Please describe.**
I am dealing with a design issue in which I want that one of my custom components lie between the toolbar and textarea. Since there is no plugin to add custom components and plug them in the tinymce-editor, what I am doing is once the tinymce-editor is mounted in the DOM, I will lookout for the toolbar class with a querySelector API and place my custom component with respect to the toolbar.

 **Describe the solution you'd like**
Since doing this query is a DOM api, and I believe that it shouldn't be needed each and every time while I am re-rendering a parent component, is there any way or could we add a callback prop/hook which can be called once the Editor component is mounted ?

**Comment by jscasca** [comment]
Hi @milap1296 

I think you should be able to hook up your function using the onInit property of the Editor component. Assuming you have an `afterInit` method declared in your app you could do something like this:
```
<Editor
  initialValue={this.state.content}
  init={{
    plugins: 'link image code',
    toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code'
  }}
  onInit = {this.afterInit}
/>
```
The `onInit` property will hook with the `init` event triggered by the editor once it has finished initializing. 

Let me know if this helps.

**Comment by milap1296** [comment]
@jscasca I appreciate you help but it doesn't help me out completely.
Let me reframe my issue a little, since I want to wait until the moment tinymce's toolbar is mounted on screen, is there a way or a hook that ensures me such behaviour, calling of onInit doesn't ensure anything about toolbar's mounting.
Also is it right to ask for a hook in tinymce-react or should this feature support is required from tinymce ?

**Comment by jscasca** [comment]
What kind of custom component do you need to put between the editing area and the toolbar? Have you considered using a side bar to place your custom component?

Technically, this wouldn't be supported as it's likely that messing with the editor DOM will end up breaking things.

Finally, calling `onInit` will trigger after the editor has finished initialising. As long as you have the latest version of TinyMCE (I believe there was a bug in a previous version) and you are not running inline mode, `onInit` will fire after the whole thing is mounted. So using `onInit` on react or using the `init_instance_callback` on TinyMCE are the closest things you will get.

**Comment by tiny-james** [comment]
Note that the sidebar is documented here:
[https://www.tiny.cloud/docs/ui-components/customsidebar/](https://www.tiny.cloud/docs/ui-components/customsidebar/)

**Comment by tiny-james** [comment]
As we can't really support adding custom UI between the toolbar and the editor I'm going to close this.
