### ISSUE TITLE
Missing package in package.json

### ISSUE THREAD

**Issue by alexcroitoru95** [tinymce/tinymce-react#122]
There is no **util** package inside package.json.

This gives the following error:
`Error: Can't resolve 'util' in 'node_modules/@tinymce/tinymce-react/lib/es2015/main/ts/components'`

**Comment by jscasca** [comment]
@alexcroitoru95 thanks for bringing this up. I will not close the issue until we have published this change

**Comment by tiny-james** [comment]
I believe this fix has now been published.
