### ISSUE TITLE
how can i set default styles?

### ISSUE THREAD

**Issue by Bygaga63** [tinymce/tinymce-react#123]
I need to get values from **onEditorChange** with default styles.

I added `content_style: 'body { font-family: Arial; font-size: 10pt}'.`
And when i type text in editor i see that it's font-family: Arial; font-size: 10pt.
But value that i recive from **onEditorChange** equal `<p>some text</p>`
I'd like to get something like this: `<p style="font-family: Arial; font-size: 10pt">some text</p>`

How can i do this?

**Comment by jscasca** [comment]
Hi @Bygaga63 

Currently, is not possible to inline content_style values. However, you can use the `forced_root_block_attrs` property in the editor to set any attribute on a root block to ensure that root blocks have the desired attributes.
E.G.:
```
<Editor
          initialValue="Some value"
          init={{
            height: 500,
            menubar: false,
            toolbar: ['undo redo | formatselect'],
            forced_root_block_attrs: {
              'style': 'font-family: Arial; font-size: 10pt'
            }
          }}
          onEditorChange={this.handleEditorChange}
        />
```
Will output something like this: `<p style="font-family: Arial; font-size: 10pt;">Some value </p>`
You can find more information on root blocks here: [https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block_attrs](https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block_attrs)

Let me know if this helps.

**Comment by Bygaga63** [comment]
> Hi @Bygaga63
> 
> Currently, is not possible to inline content_style values. However, you can use the `forced_root_block_attrs` property in the editor to set any attribute on a root block to ensure that root blocks have the desired attributes.
> E.G.:
> 
> ```
> <Editor
>           initialValue="Some value"
>           init={{
>             height: 500,
>             menubar: false,
>             toolbar: ['undo redo | formatselect'],
>             forced_root_block_attrs: {
>               'style': 'font-family: Arial; font-size: 10pt'
>             }
>           }}
>           onEditorChange={this.handleEditorChange}
>         />
> ```
> 
> Will output something like this: `<p style="font-family: Arial; font-size: 10pt;">Some value </p>`
> You can find more information on root blocks here: https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block_attrs
> 
> Let me know if this helps.

Yes, this is what i need! You made my day. Thank you:)

**Comment by SughoshKulkarni** [comment]
> Hi @Bygaga63
> 
> Currently, is not possible to inline content_style values. However, you can use the `forced_root_block_attrs` property in the editor to set any attribute on a root block to ensure that root blocks have the desired attributes.
> E.G.:
> 
> ```
> <Editor
>           initialValue="Some value"
>           init={{
>             height: 500,
>             menubar: false,
>             toolbar: ['undo redo | formatselect'],
>             forced_root_block_attrs: {
>               'style': 'font-family: Arial; font-size: 10pt'
>             }
>           }}
>           onEditorChange={this.handleEditorChange}
>         />
> ```
> 
> Will output something like this: `<p style="font-family: Arial; font-size: 10pt;">Some value </p>`
> You can find more information on root blocks here: https://www.tiny.cloud/docs/configure/content-filtering/#forced_root_block_attrs
> 
> Let me know if this helps.

Thank you. I also was trying to edit this style to default to a certain font in my flask application. This works fine.
