### ISSUE TITLE
How to set a maximum character limit to editor ? 

### ISSUE THREAD

**Issue by Senelith** [tinymce/tinymce-react#127]
How to restrict characters from being entered after the maximum limit exceeds ? and to show the character length  **234/5000**  likewise.
I couldn't find an exact documentation explaining this for the react integration. 
I'm using react functional component.

```
 <TinyMCE
            key={field.NAME}
            config={{
            menubar: false,
            plugins: 'autolink link  lists',
             toolbar: 'fontselect fontsizeselect formatselect| bold italic underline strikethrough | 
                           bullist numlist outdent indent | alignleft aligncenter alignright| insertfile 
                           image media pageembed template link anchor codesample'
             }}
             onChange={handleDescriptionEdito}
             onKeyup={handleDescriptionEditor}
 />
```
**EDIT :** 

I found out this [doc](https://www.tiny.cloud/docs/plugins/wordcount/#api)

i tried 
` const wordcount = window.tinymce.activeEditor.plugins; 
  wordcount.body.getCharacterCount();
`
in my handler function `handleDescriptionEditor` but it is giving out an error

`Cannot read property 'getCharacterCount' of undefined
`
Thanks

**Comment by tiny-james** [comment]
I'm working on improving the behaviour of TinyMCE as a controlled component at the moment. 
https://github.com/tinymce/tinymce-react/pull/128
Coincidentally the first test case I am trialling is a character limit. 
My initial experiments showed that the current implementation is a bit too aggressive in avoiding updates which makes it impossible to enforce a value that has been seen before. Additionally any time the content has to be set the cursor position is lost which is very jarring for the user.
In the PR I have removed the comparison to the prior props and have allowed passing in a cursor position represented as a TinyMCE selection bookmark. This allows returning to a previous value including selection which allows you to enforce a character limit.

Note in the your code sample you don't include the 'wordcount' plugin so it won't exist when you try to call its `getCharacterCount` function. Also if you are using TinyMCE as a controlled component then the `onEditorChange` function is recommended.

**Comment by tzakrzewski-dev** [comment]
Hello, i tryed also to get the number of character in react. it works fine like this code 


  handleEditorChange(content, Editor) {
    const wordcount = Editor.plugins.wordcount;
    this.setState({
      content,
      numberOfCharacter: wordcount.body.getCharacterCountWithoutSpaces(),
    });
  }
it set my state with the value

**Comment by fabiokiatkowski** [comment]
Hello,
some updates about this?

I have a controlled component with `onEditorChange` and `value` and I can get the size of the content but even I won't updating my state my view is updating and showing more characters that my value.

**Comment by LcsLpr** [comment]
Up

**Comment by tiny-james** [comment]
I have a PR open here:
https://github.com/tinymce/tinymce-react/pull/241

Which will enable better controlled component support, including allowing character limits:
https://codesandbox.io/s/tinymcereact-length-restriction-4f7eo

**Comment by tiny-james** [comment]
The 3.12.0 release should fix this issue. See either the example above or the storybook for an example.

**Comment by vietanhcao** [comment]
> numberOfCharacter:



> Hello, i tryed also to get the number of character in react. it works fine with this code
> 
> handleEditorChange(content, Editor) {
> const wordcount = Editor.plugins.wordcount;
> this.setState({
> content,
> numberOfCharacter: wordcount.body.getCharacterCountWithoutSpaces(),
> });
> }
> it set my state with the value

thank bro
