### ISSUE TITLE
Issues with image upload from local machine

### ISSUE THREAD

**Issue by LoganSimonsen** [tinymce/tinymce-react#13]
hack/workaround found here

https://stackoverflow.com/questions/41009605/tinymce-editor-with-react-cannot-access-local-files/41011203#41011203

**Comment by fyrkant** [comment]
That stackoverflow thread is not about this package.

**Comment by plainnany** [comment]
[#3876](https://github.com/tinymce/tinymce/issues/3876)

**Comment by singleDeveloper63** [comment]
```
import React,{ Component } from 'react';
import { Editor } from '@tinymce/tinymce-react';
import './App.css';
class App extends Component{
  render() {
    return (
       <Editor apiKey='gjzkgs1h0s7qiq5hcwi8o1refkb30ivor429dtsacrs39g8p'
        init={{
          width : 'auto',
          menubar: false,
          plugins: [
            'advlist autolink lists link image charmap print preview anchor | codesample',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount image'
          ],
          toolbar:
            'undo redo | formatselect | bold italic backcolor | codesample \
            alignleft aligncenter alignright alignjustify | \
            bullist numlist outdent indent | removeformat | help image'
        }}
       />
    );
  }
}

export default App;
```

What changes need for this code for uploading image from local directory ?

**Comment by K-Kumar-01** [comment]
> ```
> import React,{ Component } from 'react';
> import { Editor } from '@tinymce/tinymce-react';
> import './App.css';
> class App extends Component{
>   render() {
>     return (
>        <Editor apiKey='gjzkgs1h0s7qiq5hcwi8o1refkb30ivor429dtsacrs39g8p'
>         init={{
>           width : 'auto',
>           menubar: false,
>           plugins: [
>             'advlist autolink lists link image charmap print preview anchor | codesample',
>             'searchreplace visualblocks code fullscreen',
>             'insertdatetime media table paste code help wordcount image'
>           ],
>           toolbar:
>             'undo redo | formatselect | bold italic backcolor | codesample \
>             alignleft aligncenter alignright alignjustify | \
>             bullist numlist outdent indent | removeformat | help image'
>         }}
>        />
>     );
>   }
> }
> 
> export default App;
> ```
> 
> What changes need for this code for uploading image from local directory ?

should add images_upload_url also
