### ISSUE TITLE
content_style is not working

### ISSUE THREAD

**Issue by yassera2** [tinymce/tinymce-react#132]
`content_style` prop is not working.
Here is an example where I try to set the `<p>` tags with a background but it doesn't work.

https://codesandbox.io/s/spring-pine-7d4pz

**Comment by tiny-james** [comment]
The `content_style` setting must be passed to the `init` prop.
For example:
```
      <Editor
        value={"<p>Hello world</p>"}
        init={{
          content_style: "p {background: red;}"
        }}
      />
```

The only supported props are:
- `apiKey`
- `id`
- `inline`
- `init`
- `initialValue`
- `onEditorChange`
- `outputFormat`
- `value`
- `tagName`
- `cloudChannel`
- `plugins`
- `toolbar`
- `disabled`
- `textareaName`
- `tinymceScriptSrc`
- and all the editor events (eg. `onPaste` )
