### ISSUE TITLE
Update tinymce version

### ISSUE THREAD

**Issue by vrinceanuv** [tinymce/tinymce-react#135]
Hey guys,

I want to use the adv table plugins, but that is available in tinymce 5.1.2 and above, but the version in the react version is 5.0.0

I am asking for this, because i got an error in the console, that I cannot use that plugin, because the tinymce version is lower than the required one.

`Please use Advanced Tables with TinyMCE 5.1.2 or later. `

The current version is 5.3.0

Is there any chance we can get the updated tinymce version, please?

Thank you

**Comment by jscasca** [comment]
Hey @vrinceanuv 

If you are using the cloud version you can specify the cloud channel you want to use as described here: https://www.tiny.cloud/docs/integrations/react/#cloudchannel, I believe the current one on `stable` is `5.2.2` but you can learn more about the channels here: https://www.tiny.cloud/docs/cloud-deployment-guide/editor-plugin-version/#stablereleasechannel

Let me know if this helps

**Comment by vrinceanuv** [comment]
Thank you for helping out on this. 

@jscasca even so, would be recommended to have it updated in the react version as well?
Just curious :)

**Comment by jscasca** [comment]
Hi @vrinceanuv 

The react version doesn't include a TinyMCE version, it just defaults the `cloudChannel` value to `5`. You can specify a different cloud channel or use a different script source to specify a specific tinyMCE distribution as explained here: [Specifying script source](https://www.tiny.cloud/docs/integrations/react/#tinymcescriptsrc)

**Comment by ionescho** [comment]
why does the current stable release in the cloud still point to 5.4.1? (see here: https://cdn.tiny.cloud/1/no-api-key/tinymce/5/version.txt), event thought they just made 5.4.2 release this morning?
They fixed this bug: https://github.com/tinymce/tinymce/issues/5888 and others and the community needs the updates.

**Comment by tiny-james** [comment]
> why does the current stable release in the cloud still point to 5.4.1?
> they just made 5.4.2 release this morning
That is the reason... The process is not completely automated so sometimes the release takes a day to happen. Please be patient.

Closing this issues as it seems to be resolved.
