### ISSUE TITLE
AddNestedMenu items dynamically

### ISSUE THREAD

**Issue by nvgopi** [tinymce/tinymce-react#137]
Hi, 

Can I create this dynamically while setting up the nestedmenuitems. I want to populate the nestedmenu items based on a state value in react application. 

 editor.ui.registry.addNestedMenuItem('nesteditem', {
                  text: 'My nested menu item',
                  getSubmenuItems: function () {
                    return [
                      {
                        type: 'menuitem',
                        text: 'My submenu item',
                        onAction: function () {
                          editor.insertContent('<p>Here\'s some content inserted from a submenu item!</p>');
                        }
                      }
                    ];
                  }
                });

**Comment by jscasca** [comment]
Hi @nvgopi 

The `getSubmenuItems` fn will populate your submenu items every time you  open your menu. Here is an example of how to push new items: https://codesandbox.io/s/tinymcereact-hz0nw?file=/src/index.js

And here you can find everything about the Nested Menu Items: https://www.tiny.cloud/docs/ui-components/menuitems/#nestedmenuitems

Let me know if that helps

**Comment by nvgopi** [comment]
@jscasca, 

Thanks for the piece of code above. It will help a bit. I have the following code written and I am not sure why the second level menu items are always the same for each primary level.  I know this might be related with scope variables. Can you please suggest an alternative?
Attached a screenshot of the editor am currently encountering issue.

`  <Editor
          apiKey="5xdj8v2m5nktovpk23x99kv5x6rq3ykxett5nbww18qs3vka"
         initialValue="<p>This is the TinyMCE editor</p>"
         init={{
           height: 500,
          
           icons: 'material',
           elementpath: true,
           menubar: "file insert custom",
           menu: {
           custom: { title: "Custom menu", items: k.state.ListNames },
          },
           plugins: [
             'advlist autolink lists link image charmap print preview anchor',
             'searchreplace visualblocks code fullscreen',
             'insertdatetime media table paste code help wordcount'
           ],
           toolbar:
             'undo redo | formatselect | bold italic backcolor | \
             alignleft aligncenter alignright alignjustify | \
             bullist numlist outdent indent | removeformat insertFields',
             setup: function (editor) {
            
               /* example, adding a toolbar menu button */
    editor.ui.registry.addMenuButton('insertFields', {
      text: 'My button',
      fetch: function (callback) {
        var temp = [];
        
        for(var i = 0; i < k.state.ListItems.length; i++)
        {
          var obj = {};
          var fieldItems = k.state.ListItems[i].description;
          console.log(fieldItems);
          obj["text"] = k.state.ListItems[i].Title;
          obj["type"] = "nestedmenuitem";
          obj["getSubmenuItems"] = function () 
          {
            
            var arrObj = [];
            for(var k = 0; k < fieldItems.length; k++)
            {
              var fieldObject = {};
              fieldObject["text"] = fieldItems[k].Title;
              fieldObject["type"] = "menuitem";
              fieldObject["onAction"] = function () {
                editor.insertContent('{{' +  fieldItems[k].Title + '}}');
              }
              arrObj.push(fieldObject);
            }
            
            return arrObj;
          }
          
          temp.push(obj);
          console.log(temp);
        }
      
        console.log(temp);
        var items =  temp;

        callback(items);
      }
    });
          
            }
         }}
         onEditorChange={this.handleEditorChange}
       />`


![image](https://user-images.githubusercontent.com/31060544/82866396-6f2d7a80-9f46-11ea-8a61-a5eb206969e1.png)

**Comment by nvgopi** [comment]
Was able to resolve the issue. Thanks  @jscasca .Your example helped me in resolving the issue.

```
  setup: function (editor) {
           for(let i = 0; i < k.state.ListItems.length;i++)
           {
           // let Fields = k.state.ListItems[i].Fields;
            editor.ui.registry.addNestedMenuItem(k.state.ListItems[i].Id, {
            text: k.state.ListItems[i].Title,
            getSubmenuItems: () => {
              var getMenuItem = (t,r) => {
                return {
                  type: "menuitem",
                  text: t,
                  onAction: () => {
                    editor.insertContent("{{" + r +"|" + t + "}}");
                  }
                };
              };
              var nestedItems = [];
              for (let j = 0; j < k.state.ListItems[i].Fields.length; j++) {
               // console.log(Fields[j].Title);
                nestedItems.push(getMenuItem(k.state.ListItems[i].Fields[j].Title,k.state.ListItems[i].Title));
              }
              return nestedItems;
            }
          });
        }

         }
```
