### ISSUE TITLE
Use a placeholder

### ISSUE THREAD

**Issue by laura-chesches** [tinymce/tinymce-react#14]
Hello, can you please tell me how to use placeholder with this Editor? 
Thanks

**Comment by ribx** [comment]
there is this plugin, but there is no npm packaging for it

https://github.com/mohan/tinymce-placeholder

**Comment by fyrkant** [comment]
If you have issues about TinyMCE please open up an issue on the [correct repo](https://github.com/tinymce/tinymce/issues). 

But answering the question directly - there is no way at this moment to create a placeholder text, but it might be something that will be added in the future. You can keep an eye on [this feature request](https://github.com/tinymce/tinymce/issues/2623) for updates.

**Comment by yanickrochon** [comment]
The placeholder does not work with latest TinyMCE v5.10.7.
