### ISSUE TITLE
position Wrong

### ISSUE THREAD

**Issue by y1024** [tinymce/tinymce-react#140]
**What is the current behavior?**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

"@tinymce/tinymce-react": "^3.6.0",

![image](https://user-images.githubusercontent.com/9347686/83866876-0ec6e600-a75b-11ea-8af1-5a0f1839b9fc.png)

**Comment by tiny-james** [comment]
Hi y1024,

Can you provide more details to enable us to replicate this problem.

I created an editor with a long toolbar and with the toolbar_mode set to floating and added content so it is scrollable as in the picture and it seems to work correctly:
[https://codesandbox.io/s/tinymcereact-long-toolbar-wewnc](https://codesandbox.io/s/tinymcereact-long-toolbar-wewnc)

**Comment by tiny-james** [comment]
I am closing this issue as "can not replicate". 

If this bug is still occurring for you can you please provide a codesandbox link and clear replication instructions.
