### ISSUE TITLE
Export tinymce as an object for custom add-ons

### ISSUE THREAD

**Issue by burningalc** [tinymce/tinymce-react#142]
Since I'm trying to write custom plugins and buttons for tinymce editor, I found out that it cannot be done so using the reactjs library only (or maybe I missed how)

I would suggest improving by also export tinymce in `/src/main/ts/TinyMCE.ts` too since we can use it in exporting to avoid self importing.

I would love to help to code the feature and create a PR if this feature is ok. :D

**Comment by tiny-james** [comment]
Hi burningalc,

The react integration loads TinyMCE from a global variable `tinymce`. If this global is not on the page when the script needs to load an editor it will add a script tag linking to the cloud version of the editor but this will also create a `tinymce` global.

So all you have to do is add the script tag to the cloud version of the editor yourself and it will be there when you want to register plugins (if you want to preload the plugin that is).

Alternatively you can link to plugins using the [external_plugins](https://www.tiny.cloud/docs/configure/integration-and-setup/#external_plugins) setting and allow TinyMCE to load them when it added to the page by the integration.

Good luck with your plugin.

**Comment by tiny-james** [comment]
Here is an example:
[https://codesandbox.io/s/tinymcereact-externalplugins-demo-5nrvg?file=/src/index.js](https://codesandbox.io/s/tinymcereact-externalplugins-demo-5nrvg?file=/src/index.js)
