### ISSUE TITLE
collapse redux-form with tinymce-react

### ISSUE THREAD

**Issue by khoaanh2212** [tinymce/tinymce-react#143]
Now i'm working with redux-form and try to use tinymce-react as component in redux-form but it did not work.Any ideas to handle with it.
Thanks

**Comment by tiny-james** [comment]
Hi khoaanh2212,

Can you give us an example of what you tried? If possible please create a [codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) to demonstrate the issue.

I would follow the documentation here:
[https://redux-form.com/8.2.2/docs/api/field.md/#1-a-normal-component](https://redux-form.com/8.2.2/docs/api/field.md/#1-a-normal-component)

It seems that the editor component may need to be wrapped to handle the props `value` and `onChange`. Value can probably be passed though but `onChange` will have to be adapted to `onEditorChange`.

**Comment by tiny-james** [comment]
I'm closing this issue as "out of scope".

We can provide basic technical support here but for us to be able to help you need to provide something like a codesandbox link so we can see what it is you are trying. 

For technical support we recommend people ask on the [community forum or if you are a paying customer you can open a support ticket](https://support.tiny.cloud/hc/en-us).
