### ISSUE TITLE
Question - use API in ReactJs

### ISSUE THREAD

**Issue by crismarucci** [tinymce/tinymce-react#144]
Hi, 
I am somewhat confused on how to use the API on the component, i will be grateful if you can help me, I have implemented the Editor in my ReactJS App, and I want to use the [insertContent ](https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#insertcontent) method, but I can't get it to work. 
It is possible to use the API methods with the React Component? 
Tks in advance.

**Comment by jscasca** [comment]
Replying in #145
