### ISSUE TITLE
I can't find what I'm looking for: integrations/react.md

### ISSUE THREAD

**Issue by crismarucci** [tinymce/tinymce-react#145]
Hi!
I'm using ReactJS TinyMCE and I want to use the insertcontent method of the API in React, but I can't find the way to do it. I tried with tinymce.get('ID').insertContent('Testing') but I got "'tinymce' is not defined" error. What am I missing? 
Tks in advance for your help.

**Comment by jscasca** [comment]
Hi @crismarucci 

TinyMCE is probably not available when you are declaring it. What you can do is create a reference to the editor and access the API via that reference.

Here is an example in a [code-sandbox](https://codesandbox.io/s/awesome-lewin-rstbw?file=/src/App.js)

Let me know if that helps

**Comment by crismarucci** [comment]
Excellent solution!! It works great! Tks @jscasca for your help and the example!
