### ISSUE TITLE
cannot setting Domains  https://www.tiny.cloud/my-account/domains/

### ISSUE THREAD

**Issue by liukefu2050** [tinymce/tinymce-react#148]
I cannot setting domains because I can't get your mail in the url
https://www.tiny.cloud/my-account/domains/

Button “Resend email.” has nothing to do

in china my email is liukefu2020@sina.com

thank you

**Comment by jscasca** [comment]
Hi,

If you are having issues setting domains in your account you need to log a support request: https://support.tiny.cloud/hc/en-us

**Comment by liukefu2050** [comment]
thinks
