### ISSUE TITLE
Add an option for inserting chart

### ISSUE THREAD

**Issue by prakshi19** [tinymce/tinymce-react#149]
**Is your feature request related to a problem? Please describe.**
Need an editor with full functionality i.e it should have an option to add charts.
I can see that with tiny mce we can use charts but how to use it with react-tinymce?

**Comment by jscasca** [comment]
Hi @prakshi19 

Adding external plugins to the react wrapper is as easy as adding them to TinyMCE. You can use a similar configuration to include third party plugins in your tinymce-react element. You can find more information on how to configure TinyMCE in react here: [TinyMCE react integration](https://www.tiny.cloud/docs/integrations/react/)

**Comment by tiny-james** [comment]
I am closing this issue as it has been already answered.
