### ISSUE TITLE
initialValue will overwrite newer set value

### ISSUE THREAD

**Issue by ribx** [tinymce/tinymce-react#15]
The content of the Editor is loaded asynchronously, but I wanted to render the Editor itself already, because it takes quite some time. Problem is, that when changing the "value" attribute between the initial mounting and the final init of the editor, it will be overwritten by the "init" callback:

**in src/components/Editor.tsx:**
```javascript
editor.on('init', () => {
  this.initEditor(editor, initialValue);
});
```

I think the solution would be to guess the initialValue in the "initEditor" function instead of giving it here as an parameter.

**Comment by fyrkant** [comment]
Not sure I understand the problem, can you show how you are using the component? You shouldn't use the `value` and `initialValue` props together.

**Comment by ribx** [comment]
I was not. I was using `value`. Async is the problem, it works like this:
1. Editor is initialized first time with `value=""`, that value is set inside the `editor.on('init',...)` event
2. Asynchronously loaded initial values arrive and are given to the editor component with `value="initial"` and are set through the `componentWillReceiveProps` function
3. Editor is loaded, `init` event is fired which overwrites the content with the older value from the initialization

**Comment by fyrkant** [comment]
Ah, ok now I get it, I just have to move the initialValue check to the initEditor method.

**Comment by fyrkant** [comment]
I've already fixed the exact same bug in the tinymce-angular wrapper, totally forgot to check the react one too! 🤦‍♂️  I'll have a fix out today. 🙇

**Comment by fyrkant** [comment]
Hi @ribx !
`v2.2.2` is out now with a fix, can you try it out?

**Comment by ribx** [comment]
Works like a charm, thanks.
