### ISSUE TITLE
@tinymce/tinymce-react - not found in npm 

### ISSUE THREAD

**Issue by Medji777** [tinymce/tinymce-react#154]
**What is the current behavior?**

**
npm i @tinymce/tinymce-react --save

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tinymce%2ftinymce-react - Not found
npm ERR! 404 
npm ERR! 404  '@tinymce/tinymce-react@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vova/.npm/_logs/2020-08-06T10_49_49_227Z-debug.log

**

**What is the expected behavior?**
npm i @tinymce/tinymce-react --save

@tinymce/tinymce-react  installed

**Comment by danielterwiel** [comment]
I do not see why this package suddenly shouldn't be available without any further notice

It appears to be an npm problem: https://status.npmjs.org/incidents/cksjqc1w11v5

**Comment by seyaobey** [comment]
Same issue here. Our CI pipeline is suddenly failing:
`error An unexpected error occurred: "https://registry.yarnpkg.com/@tinymce%2ftinymce-react: Not found".`

**Comment by jscasca** [comment]
Hi,

This seems to be an issue with the npm registry and unfortunately is out of our control. It seems like it should be working now but it might take some time to re-populate the cache. Sorry for the inconvenience and thank you for your patience.

You can follow up the npm status update to have the latest reports on the issue: https://status.npmjs.org/

Cheers,

**Comment by Medji777** [comment]
Yes, everything works again, thanks!
