### ISSUE TITLE
Cannot set value for inputs in media and image plugin when used in Dialog from @material-ui/core package

### ISSUE THREAD

**Issue by andreir91** [tinymce/tinymce-react#156]
**What is the current behavior?**
Media and Image plugin has readonly input fields when the package is used in Dialog from @material-ui/core package

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

https://codesandbox.io/s/tinymcereact-forked-sfwz0?file=/src/demo.js

**What is the expected behavior?**

To be able to insert a value in the fields.

**Comment by simobrazz** [comment]
I have the same problem, any solution for this?

**Comment by FalkNisius** [comment]
In material-ui the <Dialog> component inherits from the <Modal> component.
The <Modal> component has an attribute disableEnforceFocus with a default value false.
If You add disableEnforceFocus={true} to Your material-ui <Dialog>, all tiny mce plugins with own dialogs are working as expected. You can test it on Your codesandbox.

**Comment by FalkNisius** [comment]
Perhaps it can be added to he tinymce integrations documentation like bootstrap integration

**Comment by andreir91** [comment]
Yes, you are right. Thanks for the solution.
