### ISSUE TITLE
Can not add button

### ISSUE THREAD

**Issue by khoaanh2212** [tinymce/tinymce-react#159]
Can not add button with this config 
 
```javascript
tinymce.init({
  selector: '#editor',
  toolbar: 'myCustomToolbarButton',
  setup: (editor) => {
    editor.ui.registry.addButton('myCustomToolbarButton', {
      text: 'My Custom Button',
      onAction: () => alert('Button clicked!')
    });
  }
});
```
Can you help with this? thanks.

**Comment by tiny-james** [comment]
Hi khoaanh2212,

You seem to have specified a config for standard TinyMCE and not the TinyMCE react component.

If you need to do this with react try the following:
https://codesandbox.io/s/tinymcereact-custom-button-jnmzj?file=/src/index.js
