### ISSUE TITLE
Update documentation to include custom plugin example

### ISSUE THREAD

**Issue by mikelax** [tinymce/tinymce-react#16]
Overview
===
I am working on a react application and am using this wrapper to integrate tinymce as an editor. I have written a simple plugin that I would like to add to the editor. 
The [tinymce documentation](https://www.tinymce.com/docs/api/tinymce/tinymce.plugin/) shows how to include a custom plugin using the `PluginManager.add` function. 

How do I add my custom plugin using this wrapper?

**Comment by fyrkant** [comment]
To use this wrapper with a cusotm plugin there's really nothing that differs from how you'd do it with vanilla TinyMCE. You put your plugin code in a separate js file and add it to you config, either by putting it in the plugins folder and adding it to your plugins property in your config if you are hosting TinyMCE yourself or by using the [external_plugins](https://www.tinymce.com/docs/configure/integration-and-setup/#external_plugins) property if you are using TinyMCE cloud, linking to your custom plugin.

**Comment by fyrkant** [comment]
Yes you do have to use the pluginmanager.add method to add the plugin, but you also have to pull it into your init config.

**Comment by fyrkant** [comment]
This does not seem to be an issue with the react wrapper so I'm closing this.

**Comment by bhunwal** [comment]
@mikelax do you have a working example which you can share?

**Comment by mikelax** [comment]
@bhunwal  I don't think I was ever able to get a custom plugin working. We ended up just adding some custom buttons to the [toolbar](https://www.tiny.cloud/docs/configure/editor-appearance/#toolbar) and implementing the functionality that way.

**Comment by vctormb** [comment]
> Yes you do have to use the pluginmanager.add method to add the plugin, but you also have to pull it into your init config.

Is there a documentation demonstrating it in a clear way?

**Comment by vctormb** [comment]
That's how I'm creating a custom plugin.

```
<Editor
      init={{
        plugins: ['customPlugin'],
        toolbar: 'customPlugin',
        setup: editor => {
          customPlugin(editor); // I'm importing this plugin from a js file
        }
      }}
    />
```

I don't even know if this is a correct way to do it. That's the only way that I've found that works good.

**Comment by SimonFc** [comment]
@vctormb 
When TinyMCE(not the editor) is loaded a global object called `tinymce` is created. That is the object that's being refered to in [this example](https://www.tiny.cloud/docs/api/tinymce/tinymce.plugin/). If you make that `tinymce.PluginManager.add('customPlugin, (editor) => { /* Do stuff here */ });'` is being run before the editor is being set up, that is before this part -
```
<Editor
      init={{
        plugins: ['customPlugin']
      }}
    />
```
the editor instance will load the plugin(run the code) previously added to the global `tinymce` object. Doing it this way with the PluginManager ensures that everything in the editor instance is being set up in the right order.
