### ISSUE TITLE
Import @tinymce/tinymce-react Not display any thing

### ISSUE THREAD

**Issue by ohmyheartbeat** [tinymce/tinymce-react#161]
When I use @tinymce/tinymce-react  Editor, but i cant see any thing in the view.How Can I find some reason and fix it.
thanks!

**Comment by tiny-james** [comment]
Hi ohmyheartbeat,

There is a [guide for setting up the TinyMCE react integration](https://www.tiny.cloud/docs/integrations/react/#tinymcereactintegrationquickstartguide).

If after following that guide you are unable to get anything to display can you please supply the code snippet you are using and we might be able to give you some guidance.

**Comment by tiny-james** [comment]
Please supply your replication code using the codesandbox template available here:
https://codesandbox.io/s/6yz4jzrrxw?fontsize=14

**Comment by tiny-james** [comment]
I'm closing this issue as "out of scope". It appears to be a request for technical support but we can't provide that here beyond the basics - instead try [the community forum or open a support ticket if you are a customer](https://support.tiny.cloud/hc/en-us).

If this is a bug report then please reopen and reply with a codesandbox and clear replication instructions.
