### ISSUE TITLE
<Editor> plugins/quickbars not working

### ISSUE THREAD

**Issue by lliebman** [tinymce/tinymce-react#162]
**What is the current behavior?**
There are multiple places where I have TinyMCE react implemented in a website. Three of the four work as expected, where when a user clicks into a TinyMCE they are offered the rich text features tooltip. However, there is one that will populate a passed inital value like the rest of them, but wont offer the user any of the "rich" text features. I think the plugins/quickbars aren't working for some reason? Very confused because the Editor is implemented in almost exactly the same way across all 4 usages. The only differences are the commented out lines in the sandbox link which pull info from different places.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
https://codesandbox.io/s/tinymcereact-forked-0xvmy?file=/src/index.js

**What is the expected behavior?**
quickbars_selection_toolbar and quickbars_insert_toolbar should work across all implementations of <Editor>. 
Pic of good usage:
<img width="324" alt="Screen Shot 2020-08-24 at 10 21 04 AM" src="https://user-images.githubusercontent.com/55757312/91075969-af5ad280-e5f3-11ea-8ddb-d9115dc7d0fe.png">

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
Currently using 3.5.0 I think?

**Comment by tiny-james** [comment]
Hi lliebman,

The "quickbars" plugin has not been enabled in the codesandbox demo you provide. When it is enabled the quick bars display as expected. I have also added the "hr" plugin as you used it in the quick bars.

```jsx
    <Editor
      apiKey="qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc"
      // initialValue={this._getWidget().getNotesDisplay()}
      //   disabled={!this._getWidget().canEditNotes()}
      // inline={true}
      //  onBlur={this.saveNotesChange}
      init={{
        placeholder: "Query notes",
        plugins: "lists link paste emoticons quickbars hr",
        inline: true,
        quickbars_selection_toolbar:
          "fontselect fontsizeselect | bold italic backcolor forecolor | bullist numlist quicktable | alignleft aligncenter alignright | hr link emoticons",
        quickbars_insert_toolbar: "quicktable | hr | emoticons",
        toolbar: false,
        menubar: false,
        fontsize_formats:
          "8px 10px 11px 12px 14px 16px 18px 24px 36px 48px 64px 72px 88px"
      }}
      //onEditorChange={this.debounceHandleEditorChange.bind(this)}
    />
`
