### ISSUE TITLE
Link target(s) not set in DOM

### ISSUE THREAD

**Issue by JaeEmAre67** [tinymce/tinymce-react#163]
**What is the current behavior?**
Links created in tinymcd-react via the toolbar link option do not retain the target choice made and do not see any kind of target in the DOM

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
Our Code:
import React from "react";
import { Editor } from "@tinymce/tinymce-react";

export default function App() {
  return (
    <div className="ourApp">
      <Editor
        init={{
          allow_unsafe_link_target: true,
          convert_urls: false,
          media_live_embeds: false,
          paste_data_images: true,
          plugins:
            "print preview fullpage importcss searchreplace directionality visualblocks visualchars fullscreen image link media codesample table charmap hr nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars paste code",
          remove_script_host: false,
          target_list: [
            { text: "Same Tab/Window", value: "_self" },
            { text: "New Tab/Window", value: "_blank" }
          ],
          toolbar:
            "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist | forecolor backcolor removeformat | charmap | fullscreen  preview | insertfile media link anchor codesample | a11ycheck ltr rtl | showcomments addcomment | code"
        }}
      />
    </div>
  );
}
**********************
End user clicks on the toolbar link icon and populates the Insert/Edit Link popup enters URL (http://imdb.com), Text to display (this link), leaves Title blank, chooses New Tab/Window from the Open Link in.... dropdown and saves their changes

**What is the expected behavior?**
Content created via TinyMCE-React renders with target= property on anchor tag(s) created

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
version 6.14.8
Chrome Version 83.0.4103.97
Windows 10 Enterprise Version 1903
This has been the only version of TinyMCE we've used

**Comment by JaeEmAre67** [comment]
Sorry, tried npm to find version. Provided is incorrect. Correct version used is 5.0.14

**Comment by tiny-james** [comment]
I attempted to replicate this on [codesandbox.io](https://codesandbox.io/s/tinymcereact-forked-7tp0b?file=/src/index.js) but it seemed to work as expected. Have you tried with the latest version of TinyMCE?
![attempt-replicate-target-bug](https://user-images.githubusercontent.com/41130888/91937627-a9709a00-ed35-11ea-9948-92d19d522e4b.gif)

**Comment by tiny-james** [comment]
I'm closing this issue as "can not replicate" due to lack of new information. If you believe this bug still persists please provide a codesandbox and clear replication instructions.
