### ISSUE TITLE
I can't find what I'm looking for: integrations/react.md Integrating with Semantic Ui React and Formik

### ISSUE THREAD

**Issue by HurmisIndia** [tinymce/tinymce-react#166]
@tinymce/tinymce-react
3.6.0

It was quite a battle to make tinymce work with semantic-ui-react and formik in my Create React App

```
<Formik
initialValues={{post_content: ''}
>
{({values}) =>(
<Form>
<Editor 
initialValue={values.post_content}
onEditorChange={content => {
let e = {
target : {
name: 'post_content',
value: content
}}
}} />
</Form>
)}
</Formik>
```
With out this mod I wasnt able to solve the issue. Is there any better way to do that?

**Comment by tiny-james** [comment]
Hi HurmisIndia,

These issues are intended for bug reports for the react integration, if you need technical support please try [here](https://support.tiny.cloud/hc/en-us). 

I skimmed the Formik docs and it looks like you'd have to wire up the `value`, `onEditorChange` and `onBlur` properties so I suspect that you may have to write more than you currently have to get it to work.

I have noted in our backlog that tighter integration with Formik is a possible future improvement to the react integration though we give no guarantees for when we can get to that.
