### ISSUE TITLE
Uncaught TypeError: Cannot read property 'remove' of null

### ISSUE THREAD

**Issue by Arm1** [tinymce/tinymce-react#17]
I have a issue : 
Uncaught TypeError: Cannot read property 'remove' of null
    at Editor.componentWillUnmount (Editor.js:71)
    at callComponentWillUnmountWithTimer (react-dom.development.js:8732)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)

getTinymce() can sometimes return nulls in componentWillUnmount()

https://github.com/tinymce/tinymce-react/blob/026591d85d58dd33b09fa37436776aed66e0d830/src/components/Editor.tsx#L59

It seems that it occurs when tinymce is not loaded yet. 

Tks for your good work !

**Comment by fyrkant** [comment]
So it happens when you try to remove the editor before TinyMCE has been loaded? I guess a simple null check should fix this.

**Comment by fyrkant** [comment]
I added a null check and released a new version, can you try it out and see if it fixed your problem?

**Comment by fyrkant** [comment]
Closing this as a fix has been released, leave a comment if you still have the problem and I can open it up again.

**Comment by Arm1** [comment]
It fixes the issue, Thanks !
