### ISSUE TITLE
Optimize script loader

### ISSUE THREAD

**Issue by sirajalam049** [tinymce/tinymce-react#172]
## Is your feature request related to a problem? Please describe.
Script loader does not have async or defer which cause render-blocking.
https://github.com/tinymce/tinymce-react/blob/9f9e3189fbcf8d00b22acb399bd18eb5d436d284/src/main/ts/ScriptLoader.ts#L34-L49

<img src="https://user-images.githubusercontent.com/22110988/92652836-20e09380-f30b-11ea-9d30-b5784eb54d4b.png" />

 ## Describe the solution you'd like
There should be flexibility to the user to decide the script loading time and mode (async / defer)

**Comment by sirajalam049** [comment]
A possible solution in PR https://github.com/tinymce/tinymce-react/pull/169 is 

https://github.com/sirajalam049/tinymce-react/blob/bf9e1b78087caefb43bb5cb1622f323fd871dba1/src/main/ts/ScriptLoader.ts#L35-L53

**Comment by tiny-james** [comment]
I've merged your PR and now I'm doing a minor cleanup before release.

One difference from your PR is that the settings will all be under the `scriptLoading` prop so for example:
```
      <Editor
        apiKey={apiKey}
        initialValue={sampleContent}
        init={{ height: 300 }}
        scriptLoading={{
          async: true,
          delay: 500
        }}
      />
```

**Comment by tiny-james** [comment]
This has been released.
