### ISSUE TITLE
I can't find what I'm looking for: integrations/react.md

### ISSUE THREAD

**Issue by yashboura303** [tinymce/tinymce-react#179]
ReactJs Integration
I have created a function to upload image to firebase but how do I pass the 'image file' to my function? I have looked into 'images_upload handler' but how do I access the user uploaded file inside that function?

[For better understanding](https://stackoverflow.com/questions/64267689/how-to-upload-the-local-image-to-firebase-storage-in-tinymce-reactjs-integratio)

**Comment by tiny-james** [comment]
Hi @yashboura303 ,

I am not familiar with firebase but I should be able to help you with accessing the file that is being uploaded.

In the react integration many of the editor settings are passed to the `init` prop like this:

```
<Editor init={{
  image_upload_handler: (blobInfo, successCallback, failureCallback, progressCallback) => {

  }
}}/>
```
Now I note that in the [docs](https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_handler) the types of those parameters are not actually specified so I'm assuming that is what you are asking for.

The blobInfo has the following type:
```typescript
interface BlobInfo {
    id: () => string;
    name: () => string;
    filename: () => string;
    blob: () => Blob;
    base64: () => string;
    blobUri: () => string;
    uri: () => string;
}
```
The parts that will probably be useful to you are the `blobInfo.blob()` call which returns a [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) containing the file contents. Additionally you may be interested in `blobInfo.filename()` which returns a the name of the original file (if you are using imagetools you may also want to enable [images_reuse_filename](https://www.tiny.cloud/docs/configure/file-image-upload/#images_reuse_filename) so you don't get randomly generated filenames on editing the image). You would use these functions to pass the image to firebase.

While the image is uploading you can **optionally** call `progressCallback(percentUploaded)` where `percentUploaded` is a number between 0 and 100 representing the percentage that has been uploaded so far. You can skip this step when getting things working as it's just to give nice visual feedback to the user.

Once you have a URL for the uploaded image from firebase you need to call `successCallback(imageUrl)`, if the image fails to upload successfully you should call `failureCallback(yourErrorMessage)`.

I hope that helps. We intended to improve our documentation with this type information in the near future.

**Comment by yashboura303** [comment]
@tiny-james I needed this only, thank you!
