### ISSUE TITLE
Enter new line not working properly in react

### ISSUE THREAD

**Issue by redfang909** [tinymce/tinymce-react#185]
When I create sentence and click enter in my keyboard, it enter up, it suppose go down and create new line. How can I fix it. It's working fine when I used initialValue, but initialValue doesn't initiate state from my api, so I used value.

```
<Tinymce
   apiKey={API_KEY}
    value={editorData}
/>
```

https://stackoverflow.com/questions/64571110/tinymce-editor-enter-new-line-not-working-properly-in-react

**Comment by lingdocs** [comment]
I am having this issue but only on Android. How did you resolve this?
