### ISSUE TITLE
Passing through "bindHandlers" on every key pressed

### ISSUE THREAD

**Issue by thiberaw** [tinymce/tinymce-react#187]
I am willing to write an Ember addon for TinyMCE integration following the example written here and I am trying to understand the reason of this:

In the case that a function is passed through _**onEditorChange**_ property then the _**bindHandlers**_ from **src/main/ts/Utils.ts** will be triggered everytime a key is pressed.

If any _**IEventPropTypes**_ in **the src/main/ts/components**/**EditorPropTypes.ts** has been overwritten, it turns out that all of those overwritten events will be unbind and (re)bind everytime a key is pressed.  
  
I might be missing something, but it might come at a cost when using the editor I guess.  
  
Could you please tell me if

1.  this is something known (and it is maybe wanted, but in this case for which reason(s) ?)
2.  there's no cost (performances at usage, loss of data)

Thank you in advance for the time you may take to clear my thoughts

**Comment by tiny-james** [comment]
It was probably done this way because the assumption was that event bindings won't change very often in which case the inefficiency is not very important.

I will look into it to see if there's a nice way to only replace the bound handler if needed.

**Comment by tiny-james** [comment]
Internal tracking number: INT-2277

**Comment by tiny-james** [comment]
This should be fixed now. It should only rebind a handler if the associated prop changes.
