### ISSUE TITLE
Focus is lost when the border-style of the tox-tinymce-element is changed

### ISSUE THREAD

**Issue by andertstephan** [tinymce/tinymce-react#189]
**What is the current behavior?**
The goal is to adapt the border of the editor depending on the focus (change color and width). 
The style change also works, but you cannot click a button directly in the command bar after the style changed. With a click, the focus is lost and the formatting is only adopted with another click.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
Example: [https://codesandbox.io/s/tinymcereact-forked-5ebtc](https://codesandbox.io/s/tinymcereact-forked-5ebtc)
1. Type a word into the editor.
2. Highlight the word.
3. Make it bold on the command bar.

**What is the expected behavior?**
The formatting should be adopted directly, as in an editor without style adjustments.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
- tinymce: 5.6.0
- tinymce-react: 3.8.1
- Chrome, Edge, Firefox

**Comment by tiny-james** [comment]
Hi anderstephan,

The focus and blur events are intended to avoid this problem. I modified your example to use them and they work for the replication case you suggest.
[https://codesandbox.io/s/tinymcereact-focus-and-blur-xttdu](https://codesandbox.io/s/tinymcereact-focus-and-blur-xttdu)

**Comment by andertstephan** [comment]
Hi tiny-james,

Thank you. That is the solution to the problem.

**Comment by navdesign** [comment]
Thats helpful thank you
