### ISSUE TITLE
TypeScript Types not in sync between latest react component (3.8.1) and TinyMCE 5.6.x

### ISSUE THREAD

**Issue by barrymay** [tinymce/tinymce-react#190]
**What is the current behavior?**
When using TinyMCE 5.6.1 with the latest TinyMCE-React (3.8.1), errors now show related to how the init prop is defined.  Appears related to the TinyMCE RawEditorSettings type and the Editor type. 
- Part of errors displayed: '"Types of property 'entity_encoding' are incompatible"
- These errors did not happen when using tinymce 5.5.*
- To workaround, using @ts-ignore (or the new @ts-expect-error) makes the editor behave properly

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
- In a TypeScript project
-- Update TinyMce to 5.6.1
-- Update TinyMce-react to 3.8.1
-- Assign a custom init handler function associated with the RawEditorSettings type exposed by TinyMCE types

**What is the expected behavior?**
-- No errors should display when using the components together

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
- TinyMCE 5.6.1
- TinyMCE-React 3.8.1
- TypeScript 3.9.7
- this issue did not occur when using TinyMCE-React 3.8.1 and TinyMCE 5.5.x

Last note: I know the TS integration is new, so it may not have been necessary to recompile packages to associate the types in prior versions - greatly appreciate all the efforts here!

**Comment by tiny-james** [comment]
I released a new build v3.8.3 which uses the TinyMCE 5.6 types.
