### ISSUE TITLE
"editor.selection is null" thrown when removing and re-adding editor

### ISSUE THREAD

**Issue by Ardeshir81** [tinymce/tinymce-react#191]
**What is the current behavior?**

I have two themes in my app: dark & light, and also I have a page in my app that has TinyMCE editor in it and a page that don't. For the theme switching to work, I had to keep the value of editor in one state, and on  theme change, I had to remove the editor from the page, and re-add it later with a little delay. It was the only way that theme switching would work.

Now this theme switching mechanism (removing and re-adding later) caused a problem. whenever I load editor, navigate to another page, and come back later, an error: `editor.selection is null` is thrown. Or whenever I toggle theme twice, the same error is thrown. **Note that this error is thrown only when I switch pages fast, Or I toggle theme fast**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

https://codesandbox.io/s/dreamy-napier-24xg8?file=/src/App.js

> Try moving between `Path1` and `Path2` fast, or try clicking on `Toggle Theme` button fast

**What is the expected behavior?**

Nothing to be thrown and editor being remounted safely

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Firefox 83
TinyMCE-dev: `{"releaseDate": "2020-11-25"}`
@tinymce/@tinymce-react: `3.8.1`

**Comment by Ardeshir81** [comment]
This issue was already created for TinyMCE: https://github.com/tinymce/tinymce/issues/4015

**Comment by tiny-james** [comment]
It seems like the editor is getting destroyed after it has started loading stylesheets but before they load. When the stylesheets load they trigger the next step in the editor loading process however the editor has already been destroyed and references to the selection have been cleared.

**Comment by tiny-james** [comment]
Jira ref: INT-2282

**Comment by tiny-james** [comment]
TinyMCE 5.7 has been released to community which should fix this issue. I've updated the codesandbox to use the cloud channel "5-testing" and it seems to be fixed but let me know if you have any problems.

https://codesandbox.io/s/naughty-golick-nctmh-cloudchannel5-testing-nctmh?file=/src/RichTextEditor.tsx

**Comment by tiny-james** [comment]
I tried replicating using files like you had (as I tried replicating using the cloud urls with 5.6.1 and I couldn't get it to fail) and it still seems fixed:
https://codesandbox.io/s/tinymce-570-test-nctmh?file=/src/RichTextEditor.tsx

**Comment by Ardeshir81** [comment]
Thanks tiny-james. That's good news. I'll give it a try.

**Comment by Ardeshir81** [comment]
hey @tiny-james Thanks for your work, I confirm updating to 5.7.0 fixes the issues. I tried it in both codesandbox and in my own project, in both cases the problem is resolved :+1: 

I consider the issue as closed now
