### ISSUE TITLE
tinymce-react still load MCE version 4

### ISSUE THREAD

**Issue by mopsyshin** [tinymce/tinymce-react#198]
tinymce-react still load MCE version 4
so they show me message below

"Your access to TinyMCE will expire on 25 Februrary 2021. Please either contact your administrator or upgrade your account using the instructions available here."

Is there any schedule to update to MCE version 5?

Or should i do something before expiring?

**Comment by tiny-james** [comment]
> tinymce-react still load MCE version 4

TinyMCE react does not specify version 4 anywhere so one of two things has happened.

1. You have loaded TinyMCE 4 somewhere else on the page and the integration is using it.
2. You have specified the `cloudChannel` prop as either version of 4 or as `"stable"`. Currently `"stable"` is still TinyMCE 4 but when support ends it will be automatically switched to TinyMCE 5. 

> should i do something before expiring

Yes!

If you have a link to TinyMCE 4 on your page then upgrade it to TinyMCE 5 and check that your configuration still works. Alternatively if you have specified the `cloudChannel` prop then just remove that prop and it will load the stable version of TinyMCE 5.

There is an article on migrating here:
[https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/](https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/)

**Comment by tiny-james** [comment]
Note that the change to loading version 5 of TinyMCE happened in version 3.0.0 which was released in February 2019, prior to that the integration would load the stable channel by default. If you have an older version of the integration you will need to upgrade.

**Comment by mopsyshin** [comment]
i'm using @tinymce/tinymce-react 3.8.4 version.
and there is no cloudChannel prop in code

![Screen Shot 2021-01-04 at 10 09 53 AM](https://user-images.githubusercontent.com/20161023/103493485-02337900-4e75-11eb-829e-3a10634192b5.png)

but, in html head, there is `<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>`

![Screen Shot 2021-01-04 at 10 06 19 AM](https://user-images.githubusercontent.com/20161023/103493470-e6c86e00-4e74-11eb-8640-05c496a2b147.png)

is there any solution?

**Comment by tiny-james** [comment]
Please read the webpage that I linked about migrating. In short you need to change your script tag to:
```html
<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
```
Replacing "no-api-key" with your TinyMCE cloud API key which is on your [dashboard](https://www.tiny.cloud/my-account/dashboard/). If you have not signed up for TinyMCE cloud then you will need to do so - it is free.

**Comment by mopsyshin** [comment]
ah i got it, i was stupid

I forget that add script manually. i think that script added automatically

thanks you
