### ISSUE TITLE
Peer dependency on React 16?

### ISSUE THREAD

**Issue by kkkrist** [tinymce/tinymce-react#201]
Is there a reason for sticking to React 16 as a peer dependency? It keeps me from upgrading to React 17.

Thanks for maintaining this project, it's greatly appreciated!

**Comment by tiny-james** [comment]
Thanks for pointing this out. I don't think this has been done deliberately so I'll look into it and put out a new version if possible.

**Comment by tiny-james** [comment]
Version 3.9.0 should have the react 17 peer dependency now.

**Comment by kkkrist** [comment]
Thank you for the quick response!
