### ISSUE TITLE
Multiple (many) editable elements on the same page

### ISSUE THREAD

**Issue by stebogit** [tinymce/tinymce-react#202]
I have many (up to like ~100) editable elements on my page and I create a new editor component for each element, which freezes the page while the components mount/load.

![Screen Shot 2021-01-07 at 9 30 26 AM](https://user-images.githubusercontent.com/12717225/103924618-27212980-50cb-11eb-9c79-94c2f7f2dbbd.png)

I found [this solution](https://stackoverflow.com/a/9111839/4530144) for the conventional JS component with jQuery, however I wonder if there is an already established pattern to solve my issue, loading a single inline instance which edits one element at a time, with the react component.
Otherwise I think I should be able to set up a custom controlled component, however I'm not sure how to allow the component  to render the inline editor on the selected textarea or element in the right place when the user clicks on the editable textarea or div.

Any suggestion or pointer would be much appreciated.

**Comment by tiny-james** [comment]
Well the selected solution on that page is for TinyMCE 3 (mceAddControl does not exist in TinyMCE 4 or 5).

It should be fairly easy to write an editor that displays on click though. You'll want inline mode and have a placeholder div of the right size that just swaps out for the editor on click.

Something like this (though I have not tested this):
```jsx
const EditorCell = (props) => {
  const [clicked, setClicked] = useState(false);
  return (
    !clicked ?
    <div style={{width: '100%', height: '100%'}} onClick={() => setClicked(true)} /> :
    <Editor inline={true} {...props} />
  );
} 
```

**Comment by stebogit** [comment]
So you mean that there is no way to mount a single (initially hidden) editor instance on the page that appears in the right place, that is over the clicked textarea/div?

I have not tried your solution (thanks for the suggestion btw), but it looks to me that every time the user clicks on an editable field the editor is mounted, loading a new set of its dependencies. Is that right?
If so, isn't there a way to cache those resources for any editor component mounted later?

**Comment by tiny-james** [comment]
Sure it's possible. You'd have to put the editor in a "display:none" div at the bottom of the page and then move that div over your square and show it when you click the square. You'd probably also want to fire a focus on the editor.

That said it's going to be a lot harder to do and you'll probably want to be creating and destroying the editor to reset the UI after each use anyway (you can reset the undo state at least but it's not perfect). The startup time after the first init is generally fairly small as all the scripts and stylesheets are already on the page and cached so only noticeable if you're trying to load many editors simultaneously.

**Comment by stebogit** [comment]
@tiny-james (and whoever else might find useful in the future) I was able to make it work, but I had to focus the editor on initialization, otherwise the (inline) toolbar would not appear unless clicking again on the field:
```js
const EditorCell = ({content, ...props}) => {
  const [clicked, setClicked] = useState(false);
  return !clicked ? (
      <div
        className="mce-content-body"
        onClick={() => setClicked(true)}
        dangerouslySetInnerHTML={{__html: content || ''}}
      />
    ) : (
      <Editor
        onInit={(e, editor) => editor.focus()}
        value={content || ''}
        inline={true}
        {...props}
      />
    );
} 
```
Thanks again for your help!
