### ISSUE TITLE
How to hide the Open link in option in Insert/Edit Link

### ISSUE THREAD

**Issue by Rajesh-Thiyagarajan** [tinymce/tinymce-react#203]
Hi Team

How to hide or remove the ` Open link in` option from **Insert/Edit** Link modal
![image](https://user-images.githubusercontent.com/67726510/103982354-57aba680-5151-11eb-9233-c44f4ab7abf6.png)

**Comment by tiny-james** [comment]
This is documented in the link plugin:
[https://www.tiny.cloud/docs/plugins/opensource/link/#target_list](https://www.tiny.cloud/docs/plugins/opensource/link/#target_list)

Essentially you need to set TinyMCE's `"target_list"` setting to `false`. This is done in the `init` prop.
```jsx
<Editor init={{target_list: false}} />
```
