### ISSUE TITLE
TinyMCE initialization problem

### ISSUE THREAD

**Issue by LullabyLY** [tinymce/tinymce-react#208]
Hello, I'd like to ask that I'm very slow in initialization, sometimes I don't initialize well in 5 minutes, and I'll report the following error during initialization：Uncaught (in promise) TypeError: Cannot read property 'once' of undefined
What is the reason?

**Comment by tiny-james** [comment]
Hi @LullabyLY ,
Can you provide some replication code using codesandbox? I have been unable to trigger this bug myself.
https://codesandbox.io/s/6yz4jzrrxw?fontsize=14

The property `once` is for registering events so I suspect the `undefined` value is the editor however I'm stumped as to how this could happen.

**Comment by LullabyLY** [comment]
Hi,@tiny-james,sorry for not replying for so long.The following is my main code and error,I am also very confused how this problem is triggered, it has bothered me for a long time
` <Editor
                            key={conditionAutoList}
                            init={{
                              plugins: 'noneditable',
                              toolbar: false,
                              menubar: false,
                              statusbar: false,
                              height: '100%',
                              width: '100%',
                              base_url: '/static',
                              content_style:
                                'body{margin:0} p  {margin: 0px; border:0px ; padding: 8px 10px;font-size:12px}',
                              setup: editor => {
                                const onAction = (
                                  autocompleteApi: any,
                                  rng: any,
                                  value: any,
                                ) => {
                                  editor.selection.setRng(rng);
                                  editor.insertContent(
                                    '<span style="background-color: #f2f5fc;padding:0 5px;margin:0 3px" class="mceNonEditable" contenteditable="false">' +
                                      value +
                                      '</span>',
                                  );
                                  autocompleteApi.hide();
                                };

                                var getMatchedChars = function(pattern: any) {
                                  return conditionAutoList.filter(
                                    (char: any) => {
                                      return char.text.indexOf(pattern) !== -1;
                                    },
                                  );
                                };
                                editor.ui.registry.addAutocompleter(
                                  'conditionAutoList',
                                  {
                                    ch: '@',
                                    minChars: 0,
                                    columns: 1,
                                    highlightOn: ['char_name'],
                                    onAction: onAction,
                                    fetch: function(pattern) {
                                      return new tinymce.util.Promise(function(
                                        resolve: any,
                                      ) {
                                        var results = getMatchedChars(
                                          pattern,
                                        ).map((char: any) => {
                                          return {
                                            type: 'cardmenuitem',
                                            value: char.value,
                                            label: char.text,
                                            items: [
                                              {
                                                type: 'cardcontainer',
                                                direction: 'vertical',
                                                items: [
                                                  {
                                                    type: 'cardtext',
                                                    text: char.text,
                                                    name: 'char_name',
                                                  },
                                                ],
                                              },
                                            ],
                                          };
                                        });
                                        resolve(results);
                                      });
                                    },
                                  },
                                );
                              },
                            }}
                            value={relationList}
                            onInit={(content: any, editor: any) => {
                              setEditorRelation(editor);
                              if (baseConfig.processStatus === 3) {
                                editor.setMode('readonly');
                              }
                            }}
                            onEditorChange={handleRelationChange}
                          />`

`Uncaught (in promise) TypeError: Cannot read property 'once' of undefined
    at dE.fire (tinymce.min.js:22919)
    at VE.fire (tinymce.min.js:23003)
    at CN (tinymce.min.js:21591)
    at l (tinymce.min.js:21659)
    at tinymce.min.js:2568`

**Comment by kjalnes** [comment]
I had a similar issue with `onInit` getting the same 'once' error as shown above, where I had a callback that took the editor as an argument. I had to wrap the call in a setTimeout, e.g. `onInit={(ev) => setTimeout(() => callback(ev.target), 0)}` to presumably get the call stack to clear before calling my callback with the editor, which is being passed as `ev.target` to the callback.

**Comment by tiny-james** [comment]
I had another go at replicating the freeze or load failure using your sample code as a base:
https://codesandbox.io/s/tinymcereact-replicate-issue-208-5chvb?file=/src/index.js

I couldn't get anything to load slowly or freeze but then I had to remove some of the code you listed since I don't have the functions you are calling. 

If it is occurring in the init handler then it might be a problem we already fixed a couple of weeks ago (the bug @kjalnes  describes) where doing anything in the init handler that changed react state would cause it to rebind the event handlers while it was trying to call them. If it is that bug then you should just update to the latest version.

**Comment by tiny-james** [comment]
I'm going to close this issue as "probably fixed" since I believe it might have been either the init handler bug or alternatively the value race condition bug. If this is still happening then leave a message and I'll reopen it.
