### ISSUE TITLE
How to get text format of TinyMCE Editor

### ISSUE THREAD

**Issue by hrishiakhade** [tinymce/tinymce-react#213]
Hello,
 I am using this editor to get the HTML format of the text.  is it possible to get the text format of the content as well ?
 I need both HTML and text format of the content .
 
```
                           <Editor
                                apiKey={TINYMCE_KEY}
                                textareaName= '#myTextarea'
                                init={{
                                    setup: (editor) => this.editor = editor,
                                    height: 500,
                                    menubar: false
                                }}
                                initialValue=''
                                id='tinyMceID'
                                onEditorChange={this.handleEditorChange}
                                value={this.state.articleContent}
                            />
```

**Comment by tiny-james** [comment]
Yes it is possible to get both text and html but you will need to use a reference to the editor. You can either do that using the ref prop (see https://codesandbox.io/s/tinymcereact-get-text-and-html-ld838?file=/src/index.js ) or you could get the reference passed as the second parameter to `onEditorChange` (or any of the events) and call `editor.getContent({format: 'text'})`.

**Comment by tiny-james** [comment]
If you are using a controlled editor you'd do something like this:
https://codesandbox.io/s/tinymcereact-forked-3ts1z?file=/src/index.js

I'm looking into why the setTimeout is needed in the onInit, seems to be an accidental side effect (aka bug) of how we bind events.

**Comment by hrishiakhade** [comment]
> Yes it is possible to get both text and html but you will need to use a reference to the editor. You can either do that using the ref prop (see https://codesandbox.io/s/tinymcereact-get-text-and-html-ld838?file=/src/index.js ) or you could get the reference passed as the second parameter to `onEditorChange` (or any of the events) and call `editor.getContent({format: 'text'})`.

Thanks a lot buddy !!   This one worked
