### ISSUE TITLE
focus editor programmatically in tinymce react component

### ISSUE THREAD

**Issue by BasirBaidya** [tinymce/tinymce-react#214]
I want to focus the editor from outside of the component programmatically. How can I do this?

**Comment by tiny-james** [comment]
You have two options.

Once the editor is loaded you can simply use the `tinymce` global and run `tinymce.activeEditor.focus()`. 

Alternatively you can get a reference to the editor object via either an event callback like `onInit` or you could just use the ref prop and call it from the class property.

Example:
https://codesandbox.io/s/tinymcereact-focus-programatically-wue01
