### ISSUE TITLE
How to get tinyymce instance?

### ISSUE THREAD

**Issue by printjs** [tinymce/tinymce-react#22]
```js
tinymce.activeEditor.uploadImages(function(success) {
  document.forms[0].submit();
});
```
I need to call the above code.

**Comment by printjs** [comment]
@TinyMCE-User

**Comment by printjs** [comment]
not tinymce instance. I can't use language_url , Because it will report an error with 'can't find tinymce'

**Comment by fyrkant** [comment]
Are you using the tinymce-react component?

**Comment by printjs** [comment]
@fyrkant yes,I use  tinymce-react

**Comment by fyrkant** [comment]
I'm not sure I understand the problem you are having, is tinymce not being loaded on the page or are you not able to find the tinymce instance? You should be able to set all setting as in vanilla tinymce in the init prop to the editor.

**Comment by r0stig** [comment]
I also think it would be great to get the editor instance. I need this instance to be able to insert content with setContent among other things. Today I'm using the global tinymce.activeEditor method but to be able to get the instance with a method (getEditor() maybe?) feels more intuitive.

**Comment by fyrkant** [comment]
You can use the `tinymce.get('ID')` to get the instance of the editor, where the ID is the one you set on the component `<Editor id="ID" />`. Or use the editor as a controlled component: https://github.com/tinymce/tinymce-react#using-as-a-controlled-component

**Comment by fyrkant** [comment]
Ah, sorry clicked the close button.

**Comment by r0stig** [comment]
It's just a matter of preference I guess. The setContent-call was just an example. I'm using more methods under the editor-object (https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/). It's nice to not being forced to use the global object when using the editor within a React component.

**Comment by fyrkant** [comment]
Where would you want a `getEditor` method though, can't really put a method on the `<Editor />` component right? 🤔

**Comment by r0stig** [comment]
I get the Editor instance by:
`<Editor ref={node => this.references.editor = node} />`

Then I would like to be able to use:
`this.references.editor.getEditor().<api-method-here>`

**Comment by fyrkant** [comment]
I don't like using the ref prop like that, `ref` should only get the html element reference. You could use the setup callback in the init object to get a reference to the editor instead if you don't want to use the tinymce global. I think something like `<Editor init={{ setup: (editor) => this.editor = editor }} />` should work.

**Comment by IamFonky** [comment]
Hello!
I'm using tinymce-react and i would like to make a simple button that apply a custom style (like a custom Bold or Italic button).
First i add my custom style 
``` json
      style_formats: [
        {
          title: 'MyCustomStyle',
          block: 'div',
          classes: 'my-custom-class',
        },
```
then I add a custom button :   
``` js
      setup: function(editor: Editor) {
        editor.ui.registry.addButton( 'MyCustomButton', {
          text: 'Apply custom style,
          onAction: function() {
            // editor have fire but no formatter 
            editor.formatter.toggle(btnName);
            editor.fire('change');
          },
        });
      },
```
Before react i was doing  `tinymce.activeEditor.formatter.toggle('MyCustomStyle')` but I can't now... How can i apply a style from a button with react component (preferably without using ref or getEditor(id))?

**Comment by SimonFc** [comment]
@IamFonky  You already have the editor in your example, right? `editor.formatter.toggle('MyCustomStyle')` If you need the editor somewhere else you could store a reference to the editor from the setup function and pass it around.

**Comment by IamFonky** [comment]
Sure but as you can see in my comment, formatter doesn't exists on the editor object (I loged it to be sure but nope)

**Comment by SimonFc** [comment]
Strange, the formatter should be available on the editor. I can see if I'm able to help you if you reproduce the issue here [codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14)

**Comment by IamFonky** [comment]
Here's a prinscreen.

![tinymceformatter](https://user-images.githubusercontent.com/25899984/62061498-98e31b80-b227-11e9-8904-395e12317631.png)

I have to go now but i'll make a simple one on codesandbox tomorow to show you.

Thx for your quick answer!

**Comment by IamFonky** [comment]
Here you are, you can see in the codebox console that there is no formatter at all ;)

[https://codesandbox.io/s/fervent-rosalind-nugp0](https://codesandbox.io/s/fervent-rosalind-nugp0)

**Comment by SimonFc** [comment]
I see why now, the formatter along with some other parts are set up a bit later in the editors initialization process and are not available at that point. The editor fires an 'init'-event when everything is done and you can access the formatter. With tinymce-react this is possible to do in two ways, see here: https://codesandbox.io/s/naughty-matsumoto-ycjsq?fontsize=14

**Comment by IamFonky** [comment]
Ok, that's perfect!
Thank you very much!
