### ISSUE TITLE
Issue with pasting content from word/browser

### ISSUE THREAD

**Issue by Nishthatandon** [tinymce/tinymce-react#220]
The copy pasting into the editor is losing the text formatting.

**Comment by tiny-james** [comment]
Pasting from word is supported by the premium plugin [powerpaste](https://www.tiny.cloud/docs/enterprise/paste-from-word/) .

If you are already a subscriber then please open a [support case](https://support.tiny.cloud/hc/en-us/requests/new) and we'll look into the problem.

If you are not yet a subscriber you can trial powerpaste for 30 days with a new cloud account to see if it solves your problem before you subscribe.
