### ISSUE TITLE
Allow Configuration Change or Size Change

### ISSUE THREAD

**Issue by amber-cd** [tinymce/tinymce-react#221]
We use TinyMCE React inside components which may be resized by the user. We would like to be able to resize the TinyMCE editor responsively. We are specifically using a third-party resizer component which calculates and provides height in pixels, so we cannot just use percentage-based height solutions.

 **Describe the solution you'd like**
I would like to be able to change the component's height and width by passing in a prop, or otherwise have some type of resize method exposed.

 **Describe alternatives you've considered**
We have tried using key-based solutions involving the height and width, such that the component will re-mount with the new configuration options when the height and width changes. However, this has led to issues with the editor flickering and losing focus, the editor flickering and losing typed-in data, and issues with the component crashing and not rendering entirely.

On previous versions of TinyMCE, we created our own React component and used editor.theme.resizeTo, but that method no longer seems to be available since upgrading to the newest TinyMCE version + the official React component.

**Comment by tiny-james** [comment]
The simplest way is to set the editor to 100% width and height and then wrap it in a div that you set the size on.

For example:
https://codesandbox.io/s/tinymcereact-dynamic-size-55ukt

**Comment by amber-cd** [comment]
Yep, that is certainly a much, much better way to do it than I'd been doing. Talk about missing the forest for the trees. Thanks!
