### ISSUE TITLE
onEditorChange is not triggered when typing IME

### ISSUE THREAD

**Issue by yuanfux** [tinymce/tinymce-react#225]
**What is the current behavior?**
onEditorChange is not capturing the composition end event (tested on Chinese pinyin) on iOS Chrome / Safari. 
<img width="374" alt="Screen Shot 2021-02-22 at 3 35 06 PM" src="https://user-images.githubusercontent.com/6414178/108676737-a788d600-7523-11eb-928f-a9a6a58d15f9.png">

From the above image, one can clearly see onEditorChange is not firing when user clicks "你好" and finishes word composition process on the iOS keyboard.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
https://codesandbox.io/s/tinymcereact-forked-piom2?file=/src/index.js

**What is the expected behavior?**
onEditorChange should be fired immediately when user clicks the word and finishes the composition process. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
the bug was found on iOS (13.6.1) Chrome and Safari with most updated TinyMCE & tinymce-react versions.

**Comment by tiny-james** [comment]
Can you please try this codesandbox and tell me if it fixes the problem:
https://codesandbox.io/s/tinymcereact-forked-f7l4q?file=/src/index.js

That sandbox triggers the update on the compositionend event which I suspect is the problem because currently it's only being fired on change keyup and setcontent. The keyup event might be firing too early to catch the character being inserted. I would have expected the change event to fire but maybe we're not detecting compositionend events for it.

**Comment by yuanfux** [comment]
> Can you please try this codesandbox and tell me if it fixes the problem:
> https://codesandbox.io/s/tinymcereact-forked-f7l4q?file=/src/index.js
> 
> That sandbox triggers the update on the compositionend event which I suspect is the problem because currently it's only being fired on change keyup and setcontent. The keyup event might be firing too early to catch the character being inserted. I would have expected the change event to fire but maybe we're not detecting compositionend events for it.

I tested the fix and the issue still exists.

<img width="375" alt="Screen Shot 2021-02-24 at 2 01 41 PM" src="https://user-images.githubusercontent.com/6414178/108955766-aaadce80-76a9-11eb-8401-e678ffd9dffd.png">

**Comment by tiny-james** [comment]
Well I don't know why that didn't work so here's a code sandbox that will log all the input and key events that I can think of along with the editor content at the time of the event so we can see what events will help:
https://codesandbox.io/s/tinymcereact-input-event-logging-f7l4q

Please try typing in a IME composition and post the event log so I can see when the events are fired relative to the content getting updated. My fear is that we'll see the events firing before the content is updated so we might have to resort to timers.

**Comment by yuanfux** [comment]
I had the complete Log for you.

```
setcontent: ""
keydown: ""
compositionstart: ""
compositionupdate: ""
input: "<p>n</p>"
keyup: "<p>n</p>"
change: "<p>n</p>"
keydown: "<p>n</p>"
compositionupdate: "<p>n</p>"
input: "<p>ni</p>"
keyup: "<p>ni</p>"
keydown: "<p>ni</p>"
compositionupdate: "<p>ni</p>"
input: "<p>ni h</p>"
keyup: "<p>ni h</p>"
keydown: "<p>ni h</p>"
compositionupdate: "<p>ni h</p>"
input: "<p>ni ha</p>"
keyup: "<p>ni ha</p>"
keydown: "<p>ni ha</p>"
compositionupdate: "<p>ni ha</p>"
input: "<p>ni hao</p>"
keyup: "<p>ni hao</p>"
compositionupdate: "<p>ni hao</p>"
input: "<p>你好</p>"
input: ""
input: "<p>你好</p>"
compositionend: "<p>你好</p>"
```

![IMG_0915](https://user-images.githubusercontent.com/6414178/110583047-0b5c0180-81a8-11eb-8ee8-65f47881f2d5.jpg)

It looks like `input` and `compositionend` events can capture the correct word. Should be an issue with how `onEditorChange` was triggered.

**Comment by tiny-james** [comment]
Thanks. I'll add compositionend to the triggering events and make a new build.

**Comment by tiny-james** [comment]
Release 3.10.4 will have this change when it finishes building. ETA 30 minutes.

**Comment by tiny-james** [comment]
Closing as this should hopefully be fixed.
