### ISSUE TITLE
fixed_toolbar_container selector can't find elements which are behind React portals

### ISSUE THREAD

**Issue by pvrobays** [tinymce/tinymce-react#226]
**What is the current behavior?**
When using TinyMCE Editors behind React portals, the fixed_toolbar_container selector might not be found as it's on another body.
FYI: The use case we have is that we have two window instances, linked through React portals. Both of them use TinyMCE editors.

**What is the expected behavior?**
That either the 'fixed_toolbar_container' selector gets found, no matter on which body instance it exists (seems almost impossible to solve), or that you can pass an HTMLElement object instead of a plain selector string.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
TinyMCE: 5.6.2; I believe it has never worked before.

**Comment by pvrobays** [comment]
I've create a feature request + PR for this in the tinymce repo: https://github.com/tinymce/tinymce/issues/6559

**Comment by tiny-james** [comment]
I'm closing this as "out of scope for the react integration" because the feature has to be implemented on TinyMCE and if it is implemented will probably not require any changes to the react integration to use.
