### ISSUE TITLE
Insert react component into tinymce-react

### ISSUE THREAD

**Issue by mgiorgi-github** [tinymce/tinymce-react#227]
Can i insert a React component into tinymce-react content?
I've tried to add custom tag <ImageMedia /> (react functonal component created in the same file of <Editor>) but don't work fine, don't add nothing... i should emulate Wordpress media manager, show in visual mode my component and in source code a shortcode...
Thanks

**Comment by mgiorgi-github** [comment]
I've tried to add custom_elements with React Component (custom_elements: "ImageMedia") but the editor replace it with "&nbsp;"
This can be a solution?

**Comment by tiny-james** [comment]
You could use react to render the initial HTML using [renderToStaticMarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) however using react inside the editor is not supported and probably won't work.

There is a plugin for [showing hidden characters in TinyMCE](https://www.tiny.cloud/docs/plugins/opensource/visualchars/) or if you want some sort of macro support you could investigate the [text pattern plugin](https://www.tiny.cloud/docs/plugins/opensource/textpattern/). You also mentioned a media plugin that you're trying to emulate - it might be useful to look into the [file_picker_callback](https://www.tiny.cloud/docs/plugins/opensource/image/#file_picker_callback) configuration of the image plugin which will allow you to open up your own UI for selecting images.

**Comment by tiny-james** [comment]
In answer to the second question. You can add custom html elements to the allowed list in tinymce using [extended_valid_elements](https://www.tiny.cloud/docs/configure/content-filtering/#extended_valid_elements).

If your element is called `ImageMedia` then you would set `extended_valid_elements: 'ImageMedia[*]'` which should allow a custom tag called ImageMedia with any attributes.

**Comment by tiny-james** [comment]
Ok, lacking further details I'm going to close this as answered.
