### ISSUE TITLE
What is the tinymce version in tinymce-react?

### ISSUE THREAD

**Issue by andrew2558** [tinymce/tinymce-react#229]
What is the tinymce version in tinymce-react?

**Comment by tiny-james** [comment]
We get the types for TinyMCE from whatever the latest version of TinyMCE 5 is at the time of compilation. At the moment that is 5.7.0.

When the integration runs it will by default load TinyMCE from the cloud using the 5-stable channel.  You can however load TinyMCE from any source you like either loading it on the page directly or by specifying the `cloudChannel` prop or the `tinymceScriptSrc` prop. Note if you are loading it from the cloud you should specify your `apiKey` (you can get one for free from https://tiny.cloud ).
