### ISSUE TITLE
mathematical equation

### ISSUE THREAD

**Issue by miryuk** [tinymce/tinymce-react#230]
Hello. I need to create a math button in a 'TinyMCE-react'. Please, can you recommend a solution for that? 

I've tried 'wiris', but after saving formulas all symbols are disappearing on rendering...

**Comment by tiny-james** [comment]
MathType/wirs is the only mathematics/formula plugin for TinyMCE that I am aware of. I highly recommend you ask them for support. Any settings that you would normally pass to tinymce you can pass using the `init` prop (excluding 'target' and 'selector').

Are the symbols not displaying in TinyMCE or is it once they have left the editor that they are not displaying?

I know that MathML uses some non-html tags so if it's within the editor you possibly need to tweak the [extended_valid_elements](https://www.tiny.cloud/docs/configure/content-filtering/#extended_valid_elements) setting to include the MathML elements. They don't mention this on the plugin page though so I suspect this is not the problem.

Alternatively if it is outside of the editor that the equations are not displaying it is possible that you have not linked the [script that MathType uses for rendering](https://docs.wiris.com/en/mathtype/mathtype_web/integrations/mathml-mode#add_a_script_to_head). 

Again please ask the developers of the MathType plugin as we are not involved in its development.
