### ISSUE TITLE
Create custom toolbar buttons for cut, copy and paste

### ISSUE THREAD

**Issue by GaneshPrabhu07** [tinymce/tinymce-react#233]
**What is the current behavior?**
selected text from the editor can be performed cut, copy and paste operations using shortcuts (ctrl X, ctrl V..etc)

**What is the expected behavior?**

created a custom toolbar buttons for cut, copy & paste. Once user clicks the corresponding icons,  selected text from editor has to be worked according to that.

**Comment by tiny-james** [comment]
Browser restrictions may prevent them from working all the time but the buttons already exist.
https://www.tiny.cloud/docs/advanced/available-toolbar-buttons/

Here's an example:
https://codesandbox.io/s/tinymcereact-cut-copy-paste-5ky0j?file=/src/index.js
