### ISSUE TITLE
Accessing custom plugins with external_plugins prop

### ISSUE THREAD

**Issue by TotesOates** [tinymce/tinymce-react#235]
Hi, I'm trying to implement a custom plugin. However, it seems like the plugin is either not being picked up by tiny MCE or tiny MCE will fail to render if I add `import 'tinymce/tinymce'` in my files with no error logs in the console. Here's an example of what I'm doing. 

```javascript
// /app/plugin/demo.js

tinymce.PluginManager.add('helloworld', function (editor, url) {
    editor.ui.registry.addButton('helloworld', {
        text: 'My Custom Button',
        onAction: function () {
            alert('Button clicked!');
        },
    });
});
```

```javascript
// /app/component/tinyMCE.js

import { Editor } from '@tinymce/tinymce-react'
render() {
        let initObject = {
            height: 500,
            menubar: false,
            plugins: [
                'insertdatetime media table code help wordcount',
            ],
             external_plugins: {
                                 'helloworld': '../plugin/demo.js' 
                         },
            toolbar: 'help | helloworld',
            contextmenu: false,
            selector:'textarea',
        }

        return (
            <div>
                <Editor
                    apiKey="1234567890"
                    init={initObject}
                />
            </div>
        )
}
```

**Comment by tiny-james** [comment]
Your code is mostly correct (though you should not specify a `selector` in the `init` prop as it will be ignored). You can see a slightly simplified version working here:
https://codesandbox.io/s/tinymcereact-simple-plugin-mtipb

The most likely cause of the failure is that you have the path to the plugin file wrong. If you check the browser console you'll probably see a message about being unable to load the plugin.

I don't know your specific environment but if you are using create-react-app and you have put the "plugin" folder in the "public" folder then you should specify:
```
'helloworld': process.env.PUBLIC_URL + '/plugin/demo.js'
```
See https://create-react-app.dev/docs/using-the-public-folder/
