### ISSUE TITLE
color-map 有多余的颜色

### ISSUE THREAD

**Issue by june6969** [tinymce/tinymce-react#238]
`custom_colors: false,
			color_cols:5,
			color_map: [
				'DFB511',
				'color1',
				'E4810F',
				'color2',
				'E9582E',
				'color3',
				'76AD1A',
				'color4',
				'00A76D',
				'color5',
				'1AA1D4',
				'color6',
				'4485DB',
				'color7',
				'A434E9',
				'color8',
				'D95096',
				'color9',
				'A434E9',
				'color8',
				'D95096',
				'color9'
			]`
			
![image](https://user-images.githubusercontent.com/13671661/111461594-5baf0280-8758-11eb-8f3d-66117407b523.png)

**Comment by june6969** [comment]
the last two color is not set,but can't remove

**Comment by tiny-james** [comment]
You have 11 colors listed and 11 swatches so it seems to match.
```javascript
{
custom_colors: false, 
color_cols:5, 
color_map: [
  'DFB511', 'color1', // 1
  'E4810F', 'color2', // 2
  'E9582E', 'color3', // 3
  '76AD1A', 'color4', // 4
  '00A76D', 'color5', // 5
  '1AA1D4', 'color6', // 6
  '4485DB', 'color7', // 7
  'A434E9', 'color8', // 8
  'D95096', 'color9', // 9
  'A434E9', 'color8',// 10 
  'D95096', 'color9' // 11 
]
}
```
https://codesandbox.io/s/tinymcereact-colormap-770m6

That said the colors I get are different however you can see that the last two colors are repeated:
![image](https://user-images.githubusercontent.com/41130888/111548832-08c06400-87c7-11eb-9411-ec3da8de95c7.png)
