### ISSUE TITLE
3.11.1 backwards typing behavior

### ISSUE THREAD

**Issue by talaikis** [tinymce/tinymce-react#240]
**What is the current behavior?**

Typing on 3.11.1 cursor stays at the start of the editor and text moves to the right. Reproduction - simply upgrade from any previous working version, like 3.10.4

**What is the expected behavior?**

Correct typing behavior.

Downgrade to 3.10.4 fixes it.

**Comment by tiny-james** [comment]
You are probably updating `initialValue` which will cause the editor to reset and lose the cursor position. The initialValue prop under normal conditions should only be set once.

See example here:
https://codesandbox.io/s/tinymcereact-async-initialvalue-w441y

**Comment by talaikis** [comment]
> You are probably updating `initialValue` which will cause the editor to reset and lose the cursor position. The initialValue prop under normal conditions should only be set once.

I see, it seems so. Closing this.
