### ISSUE TITLE
onEditorChange doesn't work properly on version 3.12.0 when using React JavaScript framework.

### ISSUE THREAD

**Issue by kingofdice66** [tinymce/tinymce-react#245]
onEditorChange doesn't trigger for version 3.12.0 when text is bolded, italicized, aligned left etc. 
It gets triggered when text is written or deleted in the application, but not when the text is bolded, italicized etc.
On version 3.11.1 for example, onEditorChange works as intended, but not for version 3.12.0
I will paste a link with a code sample written in codesandbox with a couple of comments left in the code.
I've placed a console log inside the function to see if the function is called when the respective changes are made.
Change @tinymce/tinymce-react version in codesandbox and observe the issue.

The link to the code:
 https://codesandbox.io/s/tinymcereact-form-github-bug-report-for-tinymce-regarding-oneditorchange-forked-tbskz

**Comment by tiny-james** [comment]
Release 3.12.1 is now available and should fix this issue.

**Comment by kingofdice66** [comment]
> Release 3.12.1 is now available and should fix this issue.

Happy to hear that. TinyMCE is one of the best, if not the best, WYSIWYG editors out there.
