### ISSUE TITLE
"window" in Chrome console shows two instances of tinymce editor.

### ISSUE THREAD

**Issue by frederikhors** [tinymce/tinymce-react#25]
I'm using your instructions, but now I discovered this:

When my react project loads editor I digit `window` in my Chrome console and:

![image](https://user-images.githubusercontent.com/41120635/42729022-08d5b606-87cb-11e8-9209-782d659eee06.png)

I find **two instances** of editor.

Is this ok?

I think nope. Right?

**Comment by fyrkant** [comment]
It is by design, it is the same tinymce instance with two references for backwards compatibility.
