### ISSUE TITLE
How to set the theme source url?

### ISSUE THREAD

**Issue by hopewise** [tinymce/tinymce-react#253]
When testing locally, the theme is being loaded from:
`https://cdn.tiny.cloud/1/invalid-origin/tinymce/5.7.1-108/themes/silver/theme.min.js`
However, when I deployed the project, it will try to load it from my website:
`https://my-domain.com/assets/tinymce/themes/silver/theme.js` ( it used my website domain and `theme.js` instead of `theme.min.js`)

The question is, why the source url has changed from cdn of tiny cloud to my website ? how to set it back? and at least how to force loading the `theme.min.js` instead of `theme.js` if I have to use my website as the host?

**Comment by tiny-james** [comment]
The theme will be loaded relative to `tinymce.min.js`. If you have bundled `tinymce.min.js` then you will need to set the [base_url](https://www.tiny.cloud/docs/configure/integration-and-setup/#base_url).

If it's not that then I'll need more information to help.

**Comment by hopewise** [comment]
Thanks @tiny-james , but I found this has solved my issue:

    theme_url: 'https://cdn.tiny.cloud/1/invalid-origin/tinymce/5.7.1-108/themes/silver/theme.min.js',

however, is it safe to rely on their cdn?

**Comment by tiny-james** [comment]
I'll refer you to the [cloud sign-up page](https://www.tiny.cloud/auth/signup/). Where you have `invalid-origin` you should have an API key. 

Also it's not recommended that you specify the full version. Instead use a release [channel](https://www.tiny.cloud/docs/cloud-deployment-guide/editor-plugin-version/#devtestingandstablereleases). That said you'd normally load the full editor from the cloud, not just part of it.

Of course if you're bundling part of the editor you'll probably want to know how to bundle the whole editor. Check out the [quick-start guide](https://www.tiny.cloud/docs/integrations/react/#tinymcereactintegrationquickstartguide) and scroll down to the last dot-point of step 5.

**Comment by tiny-james** [comment]
I'm closing this because it seems like it's fixed.

**Comment by hopewise** [comment]
Thanks @tiny-james

**Comment by kolserdav** [comment]
I have the same problem, my content styles depend on the theme of the application, but when I change the theme, the editor styles are not re-rendered. Is there any way to force `content_style` to change during the life cycle?
```typescript
/* eslint-disable no-unused-vars */
import React, { useRef } from 'react';
import { Editor } from '@tinymce/tinymce-react';
import { TINY_API_KEY } from '../../utils/constants';
import { Theme } from '../../Theme';

export type EditorOnChange = (e: {
  readonly type: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readonly target: any;
  readonly isDefaultPrevented: () => boolean;
  readonly preventDefault: () => void;
  readonly isPropagationStopped: () => boolean;
  readonly stopPropagation: () => void;
  readonly isImmediatePropagationStopped: () => boolean;
  readonly stopImmediatePropagation: () => void;
}) => void;

export default function App({
  value,
  onChange,
  theme,
}: {
  value: string;
  onChange: EditorOnChange;
  theme: Theme;
}) {
  const editorRef = useRef(null);

  return (
    <Editor
      onInit={(evt, editor) => {
        if (editorRef.current) {
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          editorRef.current = editor as any;
        }
      }}
      value={value}
      onChange={onChange}
      apiKey={TINY_API_KEY}
      init={{
        language: 'ru',
        height: 500,
        skin: 'oxide-dark',
        menubar: false,
        plugins: [
          'advlist',
          'advcode',
          'advtable',
          'autolink',
          'checklist',
          'export',
          'lists',
          'link',
          'image',
          'charmap',
          'preview',
          'anchor',
          'searchreplace',
          'visualblocks',
          'powerpaste',
          'fullscreen',
          'formatpainter',
          'insertdatetime',
          'media',
          'table',
          'wordcount',
          'image',
        ],
        toolbar:
          'undo redo | casechange blocks | bold italic backcolor | ' +
          'alignleft aligncenter alignright alignjustify | ' +
          'bullist numlist checklist outdent indent | table image |  removeformat',
        content_style: `body { font-family:Helvetica,Arial,sans-serif; font-size:14px; background-color: ${theme.paper}; color: ${theme.text}}`,
      }}
    />
  );
}

```
