### ISSUE TITLE
Image Resize option not showing

### ISSUE THREAD

**Issue by codetestmg** [tinymce/tinymce-react#255]
My issue similar to https://github.com/tinymce/tinymce-react/issues/56

Image Resize option not showing after uploading from local as well as from url.

Output : 
https://pasteboard.co/JZFXGHo.png

Code : 

import React, { useState } from 'react';
import 'tinymce/tinymce';
import 'tinymce/icons/default';
import 'tinymce/themes/silver';
import 'tinymce/plugins/paste';
import 'tinymce/plugins/link';
import 'tinymce/plugins/image';
import 'tinymce/plugins/table';
import 'tinymce/skins/ui/oxide/skin.min.css';
import 'tinymce/skins/ui/oxide/content.min.css';
import 'tinymce/skins/content/default/content.min.css';
import { Editor } from '@tinymce/tinymce-react';

const App = () => {
  const [contentEditor, setContentEditor] = useState();
  const handleEditorChange = (content, editor) => {
    console.log('Content was updated:', content);
    setContentEditor(content);
  }

  return (
    <Editor
      initialValue="<p>This is the initial content of the editor</p>"
      init={{
        skin: false,
        content_css: false,
        height: 500,
        menubar: true,
        plugins: [
          'link image',
          'table paste'
        ],
        toolbar:
          'undo redo | formatselect | bold italic backcolor | \
             alignleft aligncenter alignright alignjustify | \
             bullist numlist outdent indent | removeformat | help'
      }}
      value={contentEditor}
      onEditorChange={handleEditorChange}
    />
  );
}

export default App;

Dependency

 "dependencies": {
    "@tinymce/tinymce-react": "^3.12.3",
    "cra-template": "1.1.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "tinymce": "^5.7.1"
  },

**Comment by tiny-james** [comment]
The image resizing does work:
https://codesandbox.io/s/tinymcereact-image-resizing-jw5ny

It seems that the problem is that you have disabled the content CSS with the line:
```js
content_css: false,
```

Content CSS includes things like the image resize handles. If you disable the content CSS loading you must provide it as a string to the editor.

Eg...
```jsx
  // Content styles, including inline UI like fake cursors
  /* eslint import/no-webpack-loader-syntax: off */
  import contentCss from '!!raw-loader!tinymce/skins/content/default/content.min.css';
  import contentUiCss from '!!raw-loader!tinymce/skins/ui/oxide/content.min.css';

  export default function TinyEditorComponent(props) {
    // note that skin and content_css is disabled to avoid the normal
    // loading process and is instead loaded as a string via content_style
    return (
      <Editor
        init={{
          skin: false,
          content_css: false,
          content_style: [contentCss, contentUiCss].join('\n'),
        }}
      />
    );
  }
```

**Comment by codetestmg** [comment]
@tiny-james .Thanks finally solved.
