### ISSUE TITLE
input content in reverse order from version 3.11.0

### ISSUE THREAD

**Issue by DachengChen** [tinymce/tinymce-react#256]
i want input "test"
but in the content window it show "tset", it looks like after input every chars , the mouse point go back to the first plact of text.

i have downlgrade to version 3.10.4, and works fine.

**Comment by tiny-james** [comment]
This sounds like you might be using the controlled component incorrectly. You are probably updating the `initialValue` prop more than once.

Please refer to the [examples in the documentation](https://www.tiny.cloud/docs/integrations/react/#usingthetinymcereactcomponentasacontrolledcomponent).

If you are still having problems then please provide a [replication using codesandbox](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14).

**Comment by tiny-james** [comment]
Closing as I can not reproduce this error and no replication case was provided.
