### ISSUE TITLE
Fallback editor if cdn.tiny.cloud is blocked because of strict network rules

### ISSUE THREAD

**Issue by codingyourlife** [tinymce/tinymce-react#257]
**Is your feature request related to a problem? Please describe.**
Someone using our platform has very strict network rules and simply **blocks** unexpected traffic including tinymce CDN.

Developer console writes:
cdn.tiny.cloud/1/no-…/5/tinymce.min.js:1 Failed to load resource: the server responded with a status of 403 (URLBlocked-CASB(Warning))

 **Describe the solution you'd like**
I already tried to do a manual check if cdn.tiny.cloud can be called but it doesn't work and it's a back and forth because I cannot test it. In my opinion the best thing would be to simply get a onFailedToInitialize event where I put in the fallback editor.

I also want to emphasize that tinymce is also used in readonly inline mode to render the content so the page is pretty broken then if I cannot detect this.

 **Describe alternatives you've considered**

Can I maybe somehow manually load the JS file?

In case this feature becomes a won't do (small target group) I'd kindly ask if it would be possible to name the full URL that is being blocked because I only have the info with the 3 "..." in it so only cdn.tiny.cloud/1/no-…/5/tinymce.min.js. Also anything that can help with a workaround is much appreciated.

**Comment by codingyourlife** [comment]
I figured out that I can set `tinymceScriptSrc={"/local-cdn/tinymce/tinymce.min.js"}` but when I block https://cdn.tiny.cloud/* via adblock plus it fails to load theme.min.js. how can I load theme.min.js also from local?

**Comment by codingyourlife** [comment]
ok figured it out completely :).
so you can download the self-hosted version here: [https://www.tiny.cloud/get-tiny/self-hosted/](https://www.tiny.cloud/get-tiny/self-hosted/)
and load it via
```
init={{
	base_url: "/local-cdn/tinymce",
}}
```
where local-cdn is your folder in the public folder of react

**Comment by evbo** [comment]
how to make with work with webpack?

**Comment by tiny-james** [comment]
We don't recommend bundling. It makes the process vastly more complex as TinyMCE is not just one script, it's many scripts and stylesheets that need to be loaded in specific ways to work. [Loading from a folder is much easier.](https://www.tiny.cloud/docs/tinymce/6/react-zip-host/) That said there is some documentation on bundling with the react integration:

- [Bundling the TinyMCE .zip package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-zip-bundle/)
- [Bundling the TinyMCE package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/)

There is also more general information about bundling TinyMCE which is applicable to the react integration, you just need to ensure there is a `tinymce` global on the page that the integration can use:

[Introduction to bundling TinyMCE](https://www.tiny.cloud/docs/tinymce/6/introduction-to-bundling-tinymce/)

**Comment by evbo** [comment]
Luckily I am developing a desktop app, so I realized I can just throw it into my public folder and tell webpack to ignore ;)

**Comment by hengyanqwe** [comment]
> We don't recommend bundling. It makes the process vastly more complex as TinyMCE is not just one script, it's many scripts and stylesheets that need to be loaded in specific ways to work. [Loading from a folder is much easier.](https://www.tiny.cloud/docs/tinymce/6/react-zip-host/) That said there is some documentation on bundling with the react integration:
> 
> * [Bundling the TinyMCE .zip package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-zip-bundle/)
> * [Bundling the TinyMCE package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/)
> 
> There is also more general information about bundling TinyMCE which is applicable to the react integration, you just need to ensure there is a `tinymce` global on the page that the integration can use:
> 
> [Introduction to bundling TinyMCE](https://www.tiny.cloud/docs/tinymce/6/introduction-to-bundling-tinymce/)
How to use tinyMCE with npm install ？

**Comment by hengyanqwe** [comment]
> We don't recommend bundling. It makes the process vastly more complex as TinyMCE is not just one script, it's many scripts and stylesheets that need to be loaded in specific ways to work. [Loading from a folder is much easier.](https://www.tiny.cloud/docs/tinymce/6/react-zip-host/) That said there is some documentation on bundling with the react integration:
> 
> * [Bundling the TinyMCE .zip package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-zip-bundle/)
> * [Bundling the TinyMCE package with the React framework](https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/)
> 
> There is also more general information about bundling TinyMCE which is applicable to the react integration, you just need to ensure there is a `tinymce` global on the page that the integration can use:
> 
> [Introduction to bundling TinyMCE](https://www.tiny.cloud/docs/tinymce/6/introduction-to-bundling-tinymce/)

 I have already installed tinymce via npm install. Isn’t there a way to use it directly? Do I have to copy it to the React folder?
