### ISSUE TITLE
theme.min.js:4 Uncaught TypeError: u.hasPlugin is not a function

### ISSUE THREAD

**Issue by vinodsamy** [tinymce/tinymce-react#258]
The version I am using @tinymce/tinymce-react": "^3.6.0

**Comment by tiny-james** [comment]
Could you please provide a replication case using the latest version? I have not seen this error in my normal usage and without a replication unless it is a very common error I probably won't be able to fix it.

Codesandbox is normally the easiest way to post a replication case:
https://codesandbox.io/s/6yz4jzrrxw?fontsize=14

**Comment by tiny-james** [comment]
Closing as I can not reproduce the issue with the information provided. If you provide a replication I will reopen the case.
