### ISSUE TITLE
Injected editor is non-responsive sometimes when dragging inside SharePoint modern page

### ISSUE THREAD

**Issue by polinin** [tinymce/tinymce-react#26]
Hi!
I injected tinymce-react into my SPFx webpart, it works, but there're really annoying small issues:
If drag and drop the webpart to different places in the layout 2 times, the editor hides its content, the editor is blank (the body of iframe is empty in html) and it's impossible to edit content until i reload the page. After i reload the page the old content is there.
Also if at first time i want to edit text inside the editor, cursor jumps into the beginning of the line. So for example there was text "Not finished" and i click inside the editor to add words after "finished", cursor is in correct position in the end of the line, but i start typing " yet" and it goes to the start and I get " yet Not finished" as the result.

The editor is initialized like this: 
```
<Editor
        id={id}
        init={{
          plugins: ['paste', 'link', 'insertdatetime image'],
          skin_url: `${rootUrl}/SiteAssets/`,
          inline: false,
          menubar: false
        }}
        currentContent={content}
        onChange={(event) => {
          this.updateEditorContent(event.target.getContent());
        }}
      />
```
tinymce/tinymce-react@2.2.5
tinymce@4.8.1

**Comment by fyrkant** [comment]
I've never done anything in SharePoint but I guess that the problem is caused by something similar to this: https://github.com/tinymce/tinymce-angular/issues/9

When the iframe is removed the editor won't work, so you'd have to reinitialise it, is there any event in sharepoint htat you can listen to when the editor is dragged around so you can reinitialise?

The other issue sounds like it's caused by you setting the editor content as the same time as you're writing into the editor, which will mess up the editor caret position. What is the `updateEditorContent` method doing?

**Comment by polinin** [comment]
@fyrkant Hi, thank for the quick reply!
Yes, now i'm rerendering the editor, but it's quite ugly solution, because there is no special event to catch dragging of the webpart, so i have to add click event listener to the whole page container and check whether it was drag button or not... Anyway the editor's html remains there except iframe content and it's still possible to get correct content by calling editor.getContent(), isn't it possible to put the correct iframe back in place?

And my` updateEditorContent` is:
 ```
private updateEditorContent(content: string): void {   
      let {id, onContentUpdated} = this.props,
        editor = tinymce && tinymce.get(id);

      if (editor) {
        editor.setContent(content);
        onContentUpdated(content); //just saving it to SharePoint properties
      }   
  }
```

**Comment by akhil23484** [comment]
> @fyrkant Hi, thank for the quick reply! Yes, now i'm rerendering the editor, but it's quite ugly solution, because there is no special event to catch dragging of the webpart, so i have to add click event listener to the whole page container and check whether it was drag button or not... Anyway the editor's html remains there except iframe content and it's still possible to get correct content by calling editor.getContent(), isn't it possible to put the correct iframe back in place?
> 
> And my` updateEditorContent` is:
> 
> ```
> private updateEditorContent(content: string): void {   
>      let {id, onContentUpdated} = this.props,
>        editor = tinymce && tinymce.get(id);
> 
>      if (editor) {
>        editor.setContent(content);
>        onContentUpdated(content); //just saving it to SharePoint properties
>      }   
>  }
> ```
> 
> **Updated:** Turns out, my updateEditorContent method is obsolete, content is being updated without it. So no problem here! Cursor is back in place:)

Hi @polinin ,

Were you able to find a solution for this. I am facing similar issue in shrepoint where the iframe gets empty when a new webpart is added on top of the editor and when we drag and drop the editor.

Thank You!
