### ISSUE TITLE
"Link" plugin does not allow editing in bootstrap modal

### ISSUE THREAD

**Issue by tbighetti** [tinymce/tinymce-react#261]
**What is the current behavior?**
"Link" plugin does not allow editing in bootstrap modal

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
Bootstrap 5 modal: https://codesandbox.io/s/tinymce-link-plugin-bootstrap-modal-5-8ig31?file=/src/index.js
Bootstrap 3 modal: https://codesandbox.io/s/tinymce-link-plugin-bootstrap-modal-1u2y7?file=/src/index.js

**What is the expected behavior?**
Edit the “URL”, “Text display” and “Title” fields.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
* I'm converting a project to React
* tinymce-react 3.12.1
* Windows 10
* Chrome 90.0.4430.212 64 bits

I am available for testing and send more information if necessary.

**Comment by tiny-james** [comment]
It's probably related to the way bootstrap grabs focus for its dialogs. I know we have a workaround for bootstrap 4 here:
https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog

Though I believe bootstrap 5 removed JQuery so that probably won't work. I'll look into it.

**Comment by tiny-james** [comment]
The workaround for react looks like this:
```jsx
  useEffect(() => {
    const handler = function (e) {
      if (
        $(e.target).closest(
          ".tox-tinymce-aux, .moxman-window, .tam-assetmanager-root"
        ).length
      ) {
        e.stopImmediatePropagation();
      }
    };
    document.addEventListener("focusin", handler);
    return () => document.removeEventListener("focusin", handler);
  }, []);
```
As I mentioned before previous versions of bootstrap had JQuery bundled so our recommended workaround uses JQuery however that doesn't work with Bootstrap 5. That recommended method above  is basically the old JQuery workaround translated into native javascript and wrapped up an a React effect.

https://codesandbox.io/s/tinymce-link-plugin-bootstrap-modal-5-6ifml?file=/src/index.js

**Comment by tbighetti** [comment]
> It's probably related to the way bootstrap grabs focus for its dialogs. I know we have a workaround for bootstrap 4 here:
> https://www.tiny.cloud/docs/integrations/bootstrap/#usingtinymceinabootstrapdialog
> 
> Though I believe bootstrap 5 removed JQuery so that probably won't work. I'll look into it.

Thank you for the explanation! It worked for me.

**Comment by tiny-james** [comment]
I ended up adding these work-arounds to the react integration docs so they should be easier to find in future:
https://www.tiny.cloud/docs/integrations/react/#usingtinymcereactintegrationinabootstrapdialog
