### ISSUE TITLE
Caret jumps to top right after Enter key pressed in Editor

### ISSUE THREAD

**Issue by RabbitTerra** [tinymce/tinymce-react#262]
<Editor
              apiKey={process.env.REACT_APP_TMCE_KEY}
              **initialValue**={richContent}
              init={{
                height: 500,
                menubar: false,
                plugins: 'print preview importcss tinydrive searchreplace autolink autoresize save directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount imagetools textpattern noneditable help charmap quickbars emoticons',
                mobile: {
                  theme: 'silver',
                  menubar: true,
                  plugins: 'print preview importcss tinydrive searchreplace autolink save directionality visualblocks visualchars fullscreen image link media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount textpattern noneditable help charmap quickbars emoticons'
                },
                toolbar: 'undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor backcolor casechange permanentpen removeformat | pagebreak | charmap emoticons | fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | a11ycheck ltr rtl | showcomments addcomment',
                content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }',
                tinycomments_mode: 'embedded',      
                template_cdate_format: '[Date Created (CDATE): %m/%d/%Y : %H:%M:%S]',
                template_mdate_format: '[Date Modified (MDATE): %m/%d/%Y : %H:%M:%S]',
                image_caption: true,   
                toolbar_mode: 'sliding',
                contextmenu: 'link image imagetools table',
                file_picker_callback: function (callback, value, meta) {
                  /* Provide file and text for the link dialog */
                  if (meta.filetype === 'file') {
                    callback('https://www.google.com/logos/google.jpg', { text: 'My text' });
                  }
                  /* Provide image and alt text for the image dialog */
                  if (meta.filetype === 'image') {
                    callback('https://www.google.com/logos/google.jpg', { alt: 'My alt text' });
                  }
                  /* Provide alternative source and posted for the media dialog */
                  if (meta.filetype === 'media') {
                    callback('movie.mp4', { source2: 'alt.ogg', poster: 'https://www.google.com/logos/google.jpg' });
                  }
                },
                images_upload_url: `${process.env.REACT_APP_BACKEND_URL}/api/fileupload`
              }}
              **onEditorChange**={handleRichTextChange}
            />

**Comment by tiny-james** [comment]
It is hard to be certain without knowing what `handleRichTextChange` does however I suspect you are updating the `initialValue`. 

The `initialValue` should only be set once as every time it is changed the editor is reset to that initial state - it is like this to support the asynchronous loading of initial content.

If you intend to write a controlled component you should set the `value` prop which will not reset the editor. If you intend to write an uncontrolled component you should not update the `initialValue` after you set it the first time.

**Comment by tiny-james** [comment]
There are some useful examples in the technical guide:
https://www.tiny.cloud/docs/integrations/react/#usingthetinymcereactcomponentasauncontrolledcomponent

There are some live demos on the storybook:
https://tinymce.github.io/tinymce-react/?path=/story/editor--controlled-input

**Comment by tiny-james** [comment]
Closing this issue as it will most likely be solved by avoiding updating the `initialValue` property `onEditorChange`. If this is not the case then please post more information on what `handleRichTextChange` does.
