### ISSUE TITLE
Multiple instances with different configuration

### ISSUE THREAD

**Issue by DavidSvetlik** [tinymce/tinymce-react#27]
Hi, it seems that React version has a problem with multiple instances - when the settings are the same, then it's alright, but once I try to set, for example "fixed_toolbar_container", all instances follow setting of the last one.

**Comment by kibernetika** [comment]
I have the same problem. And there are not only properties. When I setup event handlers, all instance handle from first instance Editor.

` <Editor
                            id='first'
                            value={this.state.first}
                            init={{
                                ...
                            }}
                            onEditorChange={this.handleEditorChangeFirst}
                        />

 <Editor
                            id='second'
                            value={this.state.second}
                            init={{
                                ...
                            }}
                            onEditorChange={this.handleEditorChangeSecond}
                        />`

In the second Editor setup value={this.state.first} but must be value={this.state.second} and event handler from first instance (handleEditorChangeFirst) but must be from second (handleEditorChangeSecond).

**Comment by kibernetika** [comment]
I fix it's.

**Comment by fyrkant** [comment]
Yeah you shouldn't need to touch the selector setting when using the react wrapper. I'll take a look at this.

**Comment by fyrkant** [comment]
I can't seem to reproduce this, adding two editors to one page works for me. Could some maybe set up a reproduction in a github repo that I could take a look at?

**Comment by kibernetika** [comment]
Yes, you are right. I remove **selector** and all still work fine. And I can't reproduce this bug.

**Comment by DavidSvetlik** [comment]
@fyrkant Will try to do.

@kibernetika So "fixed_toolbar_container" wasn't working correctly before and now does just like that?

**Comment by DavidSvetlik** [comment]
@fyrkant Just to be sure - you tried using "fixed_toolbar_conainer" set to different selector (element) for each editor instance, right?

**Comment by fyrkant** [comment]
Yes I tried it and it works.

**Comment by DavidSvetlik** [comment]
@kibernetika @fyrkant 

Oh, I am sorry. Looks like the mistake was on my side the whole time - I had there global configuration object merged with instance-specific settings, but I forgot to put an empty object as the first argument for Object.assign. 

One more time, I am sorry for this and thank you for your time.
