### ISSUE TITLE
Button registered in contextToolBar is not getting disable

### ISSUE THREAD

**Issue by n-anandpara** [tinymce/tinymce-react#272]
**What is the current behavior?**
I have registered the context toolbar on Image, and onSetup I am disabling the button in it.  It gets disabled, but some method overrides it. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

Upload and select the image, the button in the context toolbar should come as disable. 
https://codesandbox.io/s/tinymceeditor-demo-8t3jz

**What is the expected behaviour?**
Buttons in the context toolbar should be disabled if set as disabled. 

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

**Comment by tiny-james** [comment]
You need to check if the button should be disabled in the setup call. The setup call happens when the button is about to be displayed.

I made a few tweaks to your demo to demonstrate:
https://codesandbox.io/s/tinymceeditor-demo-forked-7p0ky?file=/src/EditorMediaHelper.js

**Comment by tiny-james** [comment]
Since I haven't got a reply I'm going to assume that my suggested fix solved the issue. If not please feel free to comment and I'll reopen the issue.
