### ISSUE TITLE
Display ''none'' on live build

### ISSUE THREAD

**Issue by UzairSamad** [tinymce/tinymce-react#274]
When i deploy my react and write something in editor it dosen't shows at front-end but send content with display ''none''

Expected Behaviour:
it should show the text and tables e.t.c,as its showing in the localhost

**Comment by tiny-james** [comment]
Are there error messages in the console?

**Comment by tiny-james** [comment]
I need more information to make progress on this issue.

Please provide a replication case. Also provide any errors in the console.

You can use codesandbox to share a replication case:
https://codesandbox.io/s/6yz4jzrrxw?fontsize=14

Without any more detail I will close this case in a week as I can not make progress.
