### ISSUE TITLE
Active styles being applied to first button of the toolbar overflow when it's opened

### ISSUE THREAD

**Issue by AntonioLok** [tinymce/tinymce-react#276]
# Behaviour:
If we click on the "..." button (ie. the more button) from the toolbar and the toolbar overflow renders, the first button has active styles being applied to it by default.

# Steps to repo:
Add a lot of different toolbar items to the point that it overflows the tinymce so that the "more" button gets rendered instead and click on the "more" button

# Expected behaviour:
The first button should not have the active style applied.

# Version of tinymce, browser and os.
Version 3.12.6, chrome, mac OS. I did not try on a previous version of tinymce react.

# SS
<img width="652" alt="Screen Shot 2021-08-17 at 11 12 07 AM" src="https://user-images.githubusercontent.com/14690224/129753668-a00da7b5-ff0b-4e61-b5f6-260e9463ff92.png">

**Comment by tiny-james** [comment]
The highlight is showing the selected button. If you press the left or right arrow key the highlight will move. If you press spacebar it will "press" the button. This is working as intended and is needed to allow keyboard navigation. 

If you think the styling is incorrect please open a ticket on the tinymce repository and explain what you think it should do differently. The tinymce-react integration is not responsible for the rendering of tinymce itself.
