### ISSUE TITLE
Pass in custom element ref

### ISSUE THREAD

**Issue by anton-johansson** [tinymce/tinymce-react#277]
**Is your feature request related to a problem? Please describe.**
We have an extensive component & label library where we generate our own `ref` object and pass down to the underlying component. This way, we can use the `ref` in our framework to focus a specific component when needed. It doesn't look like this library has support for that, and it always generates the `ref` on its own and hides it:
https://github.com/tinymce/tinymce-react/blob/main/src/main/ts/components/Editor.tsx#L66

 **Describe the solution you'd like**
A simple `ref` property would be great, and if it exists, simply skip `React.createRef`.

 **Describe alternatives you've considered**
None.

 **Other**
I'd be happy to attempt adding this via a pull request if you think the solution is allright.

**Comment by tiny-james** [comment]
Reading your description I don't think the ref is going to do your library any good as the element we keep a ref for is immediately hidden (at least in iframe mode which is the default). If you attempted to focus it or get content from it you'd be disappointed.

The probably more useful way to use the ref attribute in **tinymce-react** would be to return the editor instance in the ref (as in the same value you'd get from `tinymce.activeEditor` or `tinymce.get('editor-id')` or as the second argument to event handlers like `onInit` ). Not sure how common doing something like that is though so it may just confuse people. I think I'll do a PR anyway and you can try it out using release candidate build.

**Comment by tiny-james** [comment]
So I can't set the `ref` to the editor instance it seems as it instead returns the component instance so ignore that suggestion. What you request is also impossible due to the way react works as far as I can tell.

**Comment by anton-johansson** [comment]
Aha, that makes sense. I was not aware that it was an `iframe`. That's unfortunate, it makes things a tad more complicated for us. Most React-component that I have worked with have support for passing down a `ref` in order to work with them like this. Is it possible to use a non-`iframe` mode?

**Comment by anton-johansson** [comment]
Could one idea be to:
1. Allow adding a callback for when the (hidden) `textarea` receives focus
2. Allow passing down a `ref` that will end up on the (hidden) `textarea`

That way I could do something like:
```
<Editor
    onReceiveFocus={(editor) => editor.focus()}
/>
```

This could (I'm not 100% sure) solve both this issue and #278. Assuming that the hidden element still receives events when they receive focus programmatically (i.e. via `ref` or via `label` clicks).

**Comment by tiny-james** [comment]
> Allow adding a callback for when the (hidden) textarea receives focus

It can't receive focus because it is hidden.

> Allow passing down a ref that will end up on the (hidden) textarea

There's very little you could do with that textarea though. Why do you need a reference to it?

Maybe if you describe the problem you are trying to solve or give us an example of where you solved it for some other component we can work out something.

**Comment by anton-johansson** [comment]
> > Allow adding a callback for when the (hidden) textarea receives focus
> 
> It can't receive focus because it is hidden.

That makes a ton of sense. I wasn't sure if they could still get focus "programmatically" when hidden.

> > Allow passing down a ref that will end up on the (hidden) textarea
> 
> There's very little you could do with that textarea though. Why do you need a reference to it?
> 
> Maybe if you describe the problem you are trying to solve or give us an example of where you solved it for some other component we can work out something.

Well, technically, I need a reference to the actual text area that's within the `iframe`, which I realize is a hassle (or not even possible).

I'll think about this and experiment some more and update this issue later.

**Comment by tiny-james** [comment]
> Well, technically, I need a reference to the actual text area that's within the iframe

Rich text editors like TinyMCE use a feature called [content editable](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable) so what they do is create an iframe and then build a new HTML document inside. The body tag of that document gets the contenteditable attribute set to true. They then use a lot of Javascript to build on what the webbrowsers provide to make the editing experience more palatable. 

So no, there is no textarea inside the iframe. The body of the iframe can receive focus. It can also fire focus events. You can set its value using the TinyMCE API.

**Comment by tiny-james** [comment]
Closing this as implementing this feature request does not make sense with how the editor works.
