### ISSUE TITLE
label for="..." doesn't seem to work

### ISSUE THREAD

**Issue by anton-johansson** [tinymce/tinymce-react#278]
**What is the current behavior?**

I'm giving the TinyMCE `Editor` component an `id`. This `id` is passed down to the `<textarea/>` element. I'm adding a `<label for="...">` with the same ID. As far as I know, this should be enough to focus the field, but it doesn't seem to do the trick for me. I'm not sure if this is related to this project, but maybe someone knows why?

**What is the expected behavior?**

I expect the text area to receive focus when I left click my `<label>`.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

* `"@tinymce/tinymce-react": "3.12.6"`
* TinyMCE JS 5.8.2
* Ubuntu 20.04

I have not tried with older versions of TinyMCE.

**Comment by tiny-james** [comment]
The way TinyMCE works is that it hides the textarea and creates the editor immediately afterwards hence there is nothing visible for the label to focus. The editor itself uses an iframe to display the content.

To implement focusing the editor on clicking the label you'll need to use an event handler and call `focus` on the editor instance:
https://www.tiny.cloud/docs/api/tinymce/tinymce.editor/#focus

Here's an example:
https://codesandbox.io/s/tinymce-react-focus-editor-on-label-click-p6mop

**Comment by tiny-james** [comment]
I'm closing this issue as there are existing APIs to focus the editor and we don't really have a way to associate it using `for="..."`.

**Comment by zhenzhenChange** [comment]
I made event listeners and took a detour to implement them.

```tsx
import { Editor } from '@tinymce/tinymce-react'
import { Fragment } from 'react/jsx-runtime'
import { type Editor as TinyMCEEditor } from 'tinymce'

// NOTE: custom config
// import { RichConfig } from './rich.config'

export interface RichProps {
  value?: string
  onChange?: (value: string) => void
  focusFor?: string
  placeholder?: string
}

export function RichCore(props: RichProps) {
  const { focusFor, value, onChange, placeholder } = props

  const handleInit = (instance: TinyMCEEditor) => {
    if (!focusFor) return

    const focusForDom = document.querySelector(`[for="${focusFor}"]`)
    if (!focusForDom) return

    const handler = () => instance.focus()
    focusForDom.addEventListener('click', handler)
  }

  return (
    <Editor
      init={{ placeholder, ...RichConfig.init }}
      tinymceScriptSrc={RichConfig.SCRIPT_PATH}
      value={value}
      onEditorChange={onChange}
      onInit={(_, editor) => handleInit(editor)}
    />
  )
}
```

```tsx
const FOR = 'FOR'

function Widget() {
  return (
    <Fragment>
      <label htmlFor={FOR} />
      <RichCore focusFor={FOR} />
    </Fragment>
  )
}
```
