### ISSUE TITLE
Change language dynamically

### ISSUE THREAD

**Issue by roman-pauk** [tinymce/tinymce-react#281]
Hi, I'm using tinymce in my current react project
In the project we have select to switch language(without page refresh)

But how to change language in tinymce?
I pass a new value to `init` object but there is no change

Do I have to run some additional editor callback(something like `reinitialize`)?

**Comment by tiny-james** [comment]
You can trigger a re-init by changing the `key` of the `<Editor>`. That said I don't think TinyMCE itself properly supports changing the language without reloading the page as when I last checked it loaded the language data for plugins when they are first loaded. It might work for the core editor and plugins though.
Here's a demo:
https://codesandbox.io/s/tinymce-react-language-selector-qxxv8

**Comment by roman-pauk** [comment]
Yeah, it works)
@tiny-james thank a lot

**Comment by PeterSDH** [comment]
@tiny-james thanks , solved my problem
