### ISSUE TITLE
document base url does not update when URL changes in a single-page-app?

### ISSUE THREAD

**Issue by ragesoss** [tinymce/tinymce-react#29]
I discovered a bug in my app that uses tinymce-react, related to the handling of relative URLs. I'm not certain, but I'm guessing that it's related to how `document_base_url` is handled.

Here's how I've observed the bug:

* Page loads with a url like `dashboard.wikiedu.org/courses/My_School/My_course_(Fall_2018)`
* User navigates to `dashboard.wikiedu.org/courses/My_School/My_course_(Fall_2018)/timeline`
* TinyMCE field contains a link like `/training/students/getting-started`.
* After saving, the now-relative updated url is one level off of what it originally was.

In contrast, the relative url is still pointed to the correct place after saving if the user loads `dashboard.wikiedu.org/courses/My_School/My_course_(Fall_2018)/timeline` initially.

**Comment by fyrkant** [comment]
I'm not following, is this a bug in tinymce?

**Comment by ragesoss** [comment]
@fyrkant I'm sure whether it's a bug in tinymce, tinymce-react, or something particular to how my app handles routes and URLs, but my best guess is that it would be a tinymce-react concern: how React single-page-app routing and how relative URLs work within a TinyMCE instance as the URL changes. I'll try to set up a minimal reproduction case when I get a chance.

**Comment by ragesoss** [comment]
Here's a minimal app demonstrating the issue: https://github.com/ragesoss/tinymce-react-routing

If you clone the repo, then run `yarn` and `yarn start`, you can poke at it.

The basic conditions are:
* render TinyMCE, with initial content that includes a link to a same-domain URL.
* change the URL to (or from) a subpage without reloading the page.
* Now edit the content. The URL will be converted from the original absolute URL to a relative one, but it will be relative to a different URL than the current browswer URL, which can break links.

**Comment by SimonFc** [comment]
@ragesoss,
Setting the [convert_url](https://www.tiny.cloud/docs/configure/url-handling/#convert_urls) option to false fixes the issue in your reproduction app. I'll be closing this now but let me know if you're still having the issue and this doesn't work out for you in your real use case!
