### ISSUE TITLE
Using with Typescript useRef

### ISSUE THREAD

**Issue by JoshuaHintze** [tinymce/tinymce-react#292]
**What is the current behavior?**

When going through the quick start examples I am having trouble using the non-controlled component method for instantiation. Specifically the useRef being assigned in the onInit callback.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

Specifically the example shows

const editorRef = useRef(null);
....
<Editor
onInit={(evt, editor) => editorRef.current = editor}
... >

When changing useRef(null) to useRef<Editor>(null) it gives a typescript error stating that editorRef.current is a readonly value.

What is the correct way to initialize the useRef in typescript?

**What is the expected behavior?**

Not to give typescript errors

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Latest version

**Comment by tiny-james** [comment]
It seems the `useRef` needs the type annotated in typescript.

Here's an example:
```tsx
import React, { useRef } from 'react';
import { Editor } from '@tinymce/tinymce-react';
import { Editor as TinyMCEEditor } from 'tinymce';

function App() {
  const editorRef = useRef<TinyMCEEditor | null>(null);
  const log = () => {
    if (editorRef.current) {
      console.log(editorRef.current.getContent());
    }
  };
  return (
    <div className="App">
             <Editor
         onInit={(evt, editor) => editorRef.current = editor}
         initialValue="<p>This is the initial content of the editor.</p>"
         init={{
           height: 500,
           menubar: false,
           plugins: [
             'advlist autolink lists link image charmap print preview anchor',
             'searchreplace visualblocks code fullscreen',
             'insertdatetime media table paste code help wordcount'
           ],
           toolbar: 'undo redo | formatselect | ' +
           'bold italic backcolor | alignleft aligncenter ' +
           'alignright alignjustify | bullist numlist outdent indent | ' +
           'removeformat | help',
           content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
         }}
       />
       <button onClick={log}>Log editor content</button>
    </div>
  );
}

export default App;
```

It's a little unfortunate that the type names for the react component and the tinymce instance are the same. If we do a major version bump I will look at changing the component name so it doesn't clash.

**Comment by GimpMaster** [comment]
Thank you @tiny-james 

The key I was missing was assigning useRef<TinyMCEEEditor | null>(null);

I.E. I had the TinyMCEEditor but not the | null.

Thank you for the example.

**Comment by LifeTech-Org** [comment]
@tiny-james. Thanks for this reply. Still relevant!

**Comment by fullstackzach** [comment]
I had trouble with the above workaround once we switched our projects from using pnpm to npm

I'm using pnpm here instead. I get the following error:

```
src/uiKit/TemplateEditor/index.tsx:13:31 - error TS2322: Type 'import("/node_modules/.pnpm/tinymce@6.6.0/node_modules/tinymce/tinymce").Editor' is not assignable to type 'import("/node_modules/.pnpm/@types+tinymce@4.6.5/node_modules/@types/tinymce/index").Editor'.

13       onInit={(_, editor) => (editorRef.current = editor)}
                                 ~~~~~~~~~~~~~~~~~

error TS2740: Type 'Editor' is missing the following properties from type 'Editor': $, settings, addButton, addContextToolbar, and 6 more.

13       onInit={(_, editor) => (editorRef.current = editor)}
                                 ~~~~~~~~~~~~~~~~~
```

code:

```
 const editorRef = useRef<TinyMCEEditor | null>(null);

  return (
    <Editor
      onInit={(_, editor) => (editorRef.current = editor)}
```

My workaround is this:

```
    <Editor
      onInit={(_, editor) =>
        (editorRef.current = editor as unknown as TinyMCEEditor)
```

any suggestions to avoid having to use this workaround when using pnpm?

**Comment by tiny-james** [comment]
My guess is that you're importing two different versions of TinyMCE and that's why there's a type mismatch. This normally happens when the lock file sets a older version. I would probably delete and recreate the lock file so it hopefully resolves both imports to the same version of TinyMCE.

**Comment by zeroeye0** [comment]
onInit={(_evt, editor) => editorRef.current = editor} then `OK!`

**Comment by zeroeye0** [comment]
mine: `onInit={(_evt, editor) => editorRef.current = editor}` then *OK!*
