### ISSUE TITLE
Failed to load icons from cdn.tiny.cloud 402 error

### ISSUE THREAD

**Issue by ponomarenkotema** [tinymce/tinymce-react#296]
**What is the current behavior?**

Failed to load icons: thin from url https://cdn.tiny.cloud/1/tn1be8r3gt2jmwcl6dymzfmldea67d0f0jvpqcetuqjowutr/tinymce/5.10.1-124/icons/thin/icons.js

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

3.13.0

**Comment by tiny-james** [comment]
Can you please post your configuration?

Thin icons appear to be working:
https://codesandbox.io/s/tinymce-react-thin-icons-bee31

**Comment by ponomarenkotema** [comment]
@tiny-james probably some of parameters are deprecated 

```
{
          height,
          menubar: false,
          plugins: ['code link wordcount emoticons paste codesample'],
          formats: {
            strikethrough: { inline: 's' },
            underline: { inline: 'u' }
          },
          toolbar: 'undo redo | bold italic underline strikethrough | link | codesample emoticons | code',
          skin: 'snow',
          icons: 'thin',
          forced_root_block: false,
          force_br_newlines: true,
          convert_newlines_to_brs: false,
          remove_linebreaks: true,
          cleanup: true,
          inline_styles: false,
          entity_encoding: 'raw',
          paste_as_text: true,
          contextmenu: 'bold italic underline strikethrough link'
        }
```

**Comment by tiny-james** [comment]
Indeed these settings are no-longer supported after TinyMCE 3:

- `force_br_newlines`
- `convert_newlines_to_brs`
- `remove_linebreaks`
- `cleanup` (was removed in 3.4)
- `inline_styles` 

That said listing them should not break anything, it just won't do anything.

I updated the code sandbox with your supplied config and it's still working:
https://codesandbox.io/s/tinymce-react-thin-icons-bee31?file=/src/index.js

I am closing this issue as "can not replicate".
