### ISSUE TITLE
Cant see the plugins at all. Just the textarea is visible.

### ISSUE THREAD

**Issue by Plash-jindal** [tinymce/tinymce-react#3]
```
<Editor
                      inline={false}
                      init={{
                          plugins: 'link image code',
                          toolbar: 'undo redo | bold italic | alignleft aligncenter alignright | code'
                      }}
                      initialValue={this.state.mailBody}
                      onChange={this.handleChange}
                    />
```

Cant see the plugins at all. Just the textarea is visible.

**Comment by Plash-jindal** [comment]
Yes, I am importing the TinyMCE, 
`import {Editor} from '@tinymce/tinymce-react';`

**Comment by Plash-jindal** [comment]
![screen shot 2017-11-24 at 15 18 47](https://user-images.githubusercontent.com/16471729/33214119-d2d955dc-d12a-11e7-84cb-b0e415ffa701.png)

I am just able to see this every time.

**Comment by fyrkant** [comment]
No I mean, how are you loading TinyMCE, not the component. TinyMCE needs to be globally available for the component to work, easiest is just adding a script tag link to tinymce cloud.

**Comment by Plash-jindal** [comment]
Yes, I have included the tinyMCE in the index.html file but still it is not working and it is not giving me any error on consoles.

**Comment by fyrkant** [comment]
Hmm, do you have your code on github or available somewhere else so I can take a look at it?

**Comment by Plash-jindal** [comment]
No, I do not have the code available on github. 
Just wondering if this module is compatible with react 15.0.1?

**Comment by fyrkant** [comment]
It should work with React 15, I don't think I am using anything only available in 16.

What version or tinymce-react are you using? I accidentally published a broken version on 2.0.1,  so make sure you have the latest version.

**Comment by Plash-jindal** [comment]
Well I created another application using create-react-app and it worked with that because it is having react 16 version.

But my project is with react 15. And the tinymce-react version I installed is 2.0.3

**Comment by fyrkant** [comment]
Ok, then I guess that is a sign that it doesn't work with react 15. I wonder why 🤔

**Comment by Plash-jindal** [comment]
Please solve this issue as I guess it should also work with React 15.

**Comment by fyrkant** [comment]
Is there a reason you cannot update to React 16?

**Comment by fyrkant** [comment]
Or at least to a newer 15 release like 15.4 or 15.6? I suspect it would work with one of those, the splitting or React and ReactDom might be the problem?

**Comment by fyrkant** [comment]
Closing this as we wont change anything to make old React versions work. Update to at least React 16, is my advice.
