### ISSUE TITLE
Triggering a refresh of the image_list property from the image plugin without re-initializing the editor

### ISSUE THREAD

**Issue by Mandalorian007** [tinymce/tinymce-react#306]
I am using the tinymce image plugin with an uncontrolled editor where I set a bunch of default images in the image_list property just like the [basic example](https://www.tiny.cloud/docs/plugins/opensource/image/).
![image](https://user-images.githubusercontent.com/3373692/148610734-66162a25-72d6-4a4c-bb81-c1466d0ef73b.png)

I have replaced the hardcoded list with the return of a function. The user is able to upload an image on the same page which will edit the return of the function used by the tinymce editor, but the list does not dynamically regenerate after the editor has been initialized.
![image](https://user-images.githubusercontent.com/3373692/148610973-32e672b1-9d87-41da-83ac-1c985bb0d947.png)
The `getContentImagesForEditor()` function pulls information from react state.

Ideally, I would like to trigger a regeneration of the image_list property without unloading and reloading the uncontrolled editor. Is this possible?

**Comment by tiny-james** [comment]
You can do this with the [alternate version](https://www.tiny.cloud/docs/plugins/opensource/image/#exampleofacustomasyncfunction) of the `image_list` setting that takes in a function to be called when the list is needed:
```jsx
<Editor
  init={{
    plugins: 'image',
    menubar: 'insert',
    toolbar: 'image',
    image_list: (successCb) => {
      successCb(getContentImagesForEditor());
    }
  }}
/>
```

Just be aware that the `getContentImagesForEditor` called will be the one that existed in your render function when the editor was first initialized so you will need to use references if you are setting data based on props and not just dynamically fetching content.

I recommend doing something like this:
https://codesandbox.io/s/tinymce-react-dynamic-image-list-z2vym

**Comment by Mandalorian007** [comment]
@tiny-james Thank you very much for the detailed explanation and example this makes a lot of sense!

**Comment by Mandalorian007** [comment]
Circling back to add some context in case someone has this same question in the future. The solution for managing databased on props and state that tiny-james linked ended up using the editor's ref to store the results which does work, but since I was using an uncontrolled component I actually needed the editor's current value to be able to extract the content. Because of this I ended up creating a separate ref for data storage and my final solution looks like:
```
// create reference for datastorage in react component
const imageListRef = useRef({
        imageList:[]
    })

//contentImages is react state (via recoiljs in this case)
imageListRef.current.imageList = useCallback(() => {
        return contentImages.map(contentImage => {
            return {
                title: contentImage.name,
                value: contentImage.url
            }
        })
    }, [contentImages])
    
// define image list on the editor
image_list: function (success) {
    success(imageListRef.current.imageList());
},
```
