### ISSUE TITLE
Editor on popup - inset/edit link not working 

### ISSUE THREAD

**Issue by MMohesen88** [tinymce/tinymce-react#307]
I faced issue on the Editor when appears only on Modal; Modal from react material-ui.
the below code snippet for the editor implementations  

config :
```
{
    plugins:['link', 'autolink'],
    menubar:"link",
    toolbar:"link",
    toolbar_sticky: false,
    autosave_ask_before_unload: true,
    autosave_restore_when_empty: false,
    autosave_retention: null,
    image_advtab: true,
    default_link_target: "_blank",
    link_assume_external_targets: true,
    link_context_toolbar: true,
    link_default_protocol: "https",
    link_title: true,
    link_quicklink: true,
    paste_as_text: true,
    file_picker_types: "image",
}
```
Editor : 
`import { Editor } from "@tinymce/tinymce-react";`
`import { Modal } from "@material-ui/core";`

`...`

`<Editor init={config} onEditorChange={handleOnChange}           />`

in case the Editor on the popup the insert/edit link disabled and not editable, and the user unable to insert new or edit link

Screenshot :
<img width="484" alt="Screen Shot 2022-01-12 at 12 08 41 AM" src="https://user-images.githubusercontent.com/90827115/149029255-49916b7f-952b-40e4-8fb9-c8048340c788.png">

**Comment by tiny-james** [comment]
This sounds like the modal is preventing focus (Bootstrap modals do something similar). I wonder if the same fix will work:
https://www.tiny.cloud/docs/integrations/react/#bootstrap5

**Comment by tiny-james** [comment]
It was indeed a focus issue. The modal provides a handy setting `disableEnforceFocus` which you will need to use with TinyMCE.
https://codesandbox.io/s/tinymce-react-material-ui-core-modal-disableenforcefocus-s1to5
