### ISSUE TITLE
Event onEditorChange shouldn't trigger after injecting new content with value

### ISSUE THREAD

**Issue by stopsopa** [tinymce/tinymce-react#31]
I've managed to reproduce this issue here:

https://codesandbox.io/s/5k20j840yl

Please try to type something in tinymce in English tab, and then switch tab to German and look what's happening with state of component, it is not happening with input field. State of German instance of tinymce is copied to english when I switch tab.

I found workaround - [uncomment in code in codesandbox]

**Comment by fyrkant** [comment]
The problem was being caused by the fact that setState is async, so you can fix it like this: https://codesandbox.io/s/5kr1885514

**Comment by BaptWaels** [comment]
I've got the exact same problem. It seems to be a real issue even if we can implement a workaround on our side

**Comment by SimonFc** [comment]
@BaptWaels So that I understand the issue you have I made a [demo](https://codesandbox.io/s/tinymcereact-79wvr?fontsize=14). Do you mean that the onEditorChange event should run whenever the value prop gets a new value?

**Comment by BaptWaels** [comment]
@SimonFc I've got the exact same problem as @stopsopa in his demo here:
https://codesandbox.io/s/5k20j840yl

`onEditorChange ` seems to be toggled when the Editor redraw (when tab changes). `onEditorChange ` should only be toggled when the user input something or do I misunderstand something ?

**Comment by SimonFc** [comment]
Ignoring some other issues with the code, I added a single console.log statement and switched when the tabs are displayed as active as it seemed wrong. https://codesandbox.io/s/react-and-scss-fdsc3?fontsize=14 The only time `onEditorChange` fires is when the editors content changes so nothing unexpected there right?

**Comment by chhch** [comment]
I have the same problem. The behaviour of tinymce is different from the behaviour of input and textarea. Tinymce calls `onEditorChange` more often than input or textarea call `onChange`.

It can be reproduced by clicking on the buttons "en" or "de" in this demo https://codesandbox.io/s/react-and-scss-r02p5. As you can see in the console output, tinymce calls `onEditorChange` every time the value changes. The input field calls `onChange` only when the user enters something.

@SimonFc I think most would expect tinymce to behave identically to input and textarea? @BaptWaels I am still looking for a solution. Could you tell, what workaround do have implemented?
