### ISSUE TITLE
React - Multiple Editors 

### ISSUE THREAD

**Issue by jlmelb** [tinymce/tinymce-react#317]
Hi,

I am currently trying to follow one of the React examples (https://codesandbox.io/s/z03vw) in order to render multiple tinymce editors on my React page.  However, I am encountering two errors Cannot read properties of undefined (reading 'open') and Cannot read properties of undefined (reading 'length'). 

I am wondering whether this is a similar issue to https://github.com/tinymce/tinymce-react/issues/236 but I am not sure on how to proceed to resolve.

Any tips would be much appreciated - I have provided my sample code below.  I am current using version 3.13.0 for React Tinyme.

Thanks in advance.

`import React, { useRef,useState, useEffect} from "react"
import {Editor} from "@tinymce/tinymce-react";

const Qliktest = (props) => {

    const [value, setValue] = useState('');
    const handleEditorChange = (value, editor) => {
        setValue(editor.getContent({format: 'html'}));
    };
    
    function InputEditor (props) {
        return (
            <Editor
                init={{
                    height: 500,
                    menubar: "file edit view insert format tools table help",
                    plugins: [
                        "advlist autolink lists link image charmap print preview anchor",
                        "searchreplace visualblocks code fullscreen",
                        "insertdatetime media table paste code help wordcount"
                    ]
                }}
                initialValue=''
                value=''
                onEditorChange={handleEditorChange}
            />
        )
    };
    
    return (
        <>
            <h1>Heading 1</h1>
            <InputEditor
                id='editor1'
                initialValue=''
                value=''
            />
            <h1>Heading 2</h1>
            <InputEditor
                id='editor2'
                initialValue=''
                value=''
            />
            <h1>Heading 3</h1>
            <InputEditor
                id='editor3'
                initialValue=''
                value=''
            />
        </>
    )
}

export default Qliktest;`

**Comment by tiny-james** [comment]
I pasted your code into a sandbox and it renders without error:
https://codesandbox.io/s/tinymce-react-issue-317-4pmof

Note there are still problems (setting value to empty string will make it impossible to edit as it will enforce the empty string) however I assume that's because it's a work in progress.

I need more information to help.

**Comment by jlmelb** [comment]
Hi @tiny-james 

Thanks for the quick reply.   I'm not 100% sure but the problem may have been the order in which the components were being rendered.  

I created a seperate .js file and set-up a TinyMCEComponent.js file with the below component and was able then to load multiple editors on my other pages.  

Problem is solved so I will close the issue.

Thanks for your help!

`
const TinyMCEComponent = (props) => {
    const [value, setValue] = useState('');
    const handleEditorChange = (value, editor) => {
        setValue(editor.getContent({format: 'html'}));
    }
    return (
        <div>
            {props.showEditor === props.id && ( 
            <Form>
                <Editor
                    initialValue={props.initialValue}
                    init={{
                        height: 300,
                        menubar: false,
                        plugins: [
                            'advlist autolink lists link image charmap print preview anchor',
                            'searchreplace visualblocks code fullscreen',
                            'insertdatetime media table paste code help wordcount'
                        ],
                        toolbar: 'undo redo | formatselect | ' +
                            'bold italic backcolor | alignleft aligncenter ' +
                            'alignright alignjustify | bullist numlist outdent indent | ' +
                            'removeformat | help',
                        content_style: 'body { font-family:Helvetica,Arial,sans-serif; font-size:14px }'
                    }}
                    onEditorChange={handleEditorChange}
                    value={value}
                />
                <Button title="Submit"
                        color="info"
                        onClick={(e) => props.handleSubmitClick(e, props, value)}
                >
                    Submit
                </Button>
            </Form>
            )}
        </div>
    );
}
`
