### ISSUE TITLE
Should be able to load TinyMCE from node_module

### ISSUE THREAD

**Issue by Flaburgan** [tinymce/tinymce-react#325]
Hello and thank you for your work.

If I understand correctly, we can load TinyMCE either by getting it from the cloud (I'd like to avoid that), or by having the files locally and giving them to `tinymceScriptSrc` (that's what I'm doing at the moment). But tinymce-react has a dependency to tinymce in package.json, so doesn't that mean that it is embedded twice? Can't we simply get tinymce from the node modules?
(Sorry I'm a bit new to this maybe my question doesn't make any sense).

**Comment by tiny-james** [comment]
> But tinymce-react has a dependency to tinymce in package.json

It uses the dependency to provide type hints for the `init` prop.

> doesn't that mean that it is embedded twice?

It will use whatever tinymce version you specify in your package.json as long as it is larger than 5.5.1 (and currently smaller than 6 but that is about to be allowed too) to provide the types. It does not get any functions from the tinymce node module so once compiled to javascript this has no size impact.

> Can't we simply get tinymce from the node modules?

TinyMCE does not get compiled into the integration. You can setup webpack or a fairly simple postinstall script to copy the content of the tinymce node module into your public folder and then point to it with the `tinymceScriptSrc`. You can also (with a lot of work) get Webpack to bundle TinyMCE - as TinyMCE is made up of multiple scripts and style sheets which get loaded into iframes that are generated at runtime it is not trivial to load by bundling like most things.

I recommend checking out the [quick start guide](https://www.tiny.cloud/docs/integrations/react/#tinymcereactintegrationquickstartguide).
