### ISSUE TITLE
Update peerDependencies to include React 18

### ISSUE THREAD

**Issue by MikeCalugaru** [tinymce/tinymce-react#329]
Hello, React 18 is now available: https://reactjs.org/blog/2022/03/29/react-v18.html

Trying to use react 18 together with @tinymce/tinymce-react v3.13.1 (latest version) currently leads to a dependency conflict. I suspect this is related to the peerDependencies specified in the package.json file:
`  "peerDependencies": {
    "react": "^17.0.1 || ^16.7.0",
    "react-dom": "^17.0.1 || ^16.7.0"
  },`

Would it be possible to publish a new version which allows react 18 too?

**Comment by tiny-james** [comment]
I'm working on it.

**Comment by tiny-james** [comment]
This was released in version 3.14 on Tuesday with the old apache 2 license and then in 4.0 today with the MIT license.
