### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'find') 

### ISSUE THREAD

**Issue by ludiguo** [tinymce/tinymce-react#334]
**What is the current behavior?**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

**Comment by tiny-james** [comment]
I strongly suspect that this is a TinyMCE problem not a problem with the tinymce-react integration however without more information I don't know either way.

Can you provide a replication? Or at minimum a stacktrace?

**Comment by tiny-james** [comment]
Closing as I don't have sufficient information to act on this issue.
