### ISSUE TITLE
Allow setting of `placeholder` text

### ISSUE THREAD

**Issue by batpad** [tinymce/tinymce-react#335]
**Is your feature request related to a problem? Please describe.**

With the release of TinyMCE 5.2, `placeholder` text is now supported: https://www.tiny.cloud/blog/tinymce-placeholder-text/ . It would be great for this react plugin to allow setting of `placeholder` text.

 **Describe the solution you'd like**

Allow setting of `placeholder` as a prop to the `Editor` component.

 **Describe alternatives you've considered**

Not using `placeholder` text - but for some use-cases, placeholder text is really desirable for the user experience.

**Comment by tiny-james** [comment]
Thanks for the PR but this can already be done with the current version:
https://codesandbox.io/s/placeholder-demo-4j3vcf

```jsx
<Editor init={{placeholder: 'This is placeholder text'}} />
```

Is there a reason you don't want to use the `init` prop?

**Comment by batpad** [comment]
> Is there a reason you don't want to use the init prop?

Nope, no good reason. I obviously just did not read the documentation well enough. Many apologies for the noise and thank you so much for the quick response and the clear example.
