### ISSUE TITLE
When enabling TinyMCE, focus is set

### ISSUE THREAD

**Issue by d3vkit** [tinymce/tinymce-react#34]
When passing disabled as a prop to TinyMCE react, focus is taken when disabled is false.

I have made a codesandbox that shows this issue:

https://codesandbox.io/s/93nqq6zxrw

I reprod this using the instructions at the tinymce docs: https://www.tiny.cloud/docs/integrations/react/

Click the enable/disable button to see the editor change disabled state, and steal focus when enabled.

Thanks!

**Comment by fyrkant** [comment]
This is not a problem in the react wrapper component but the way that switching between modes in tinymce works - it sets focus after activating - so it's not something that can be fixed here. You should create an issue on [this repo](https://github.com/tinymce/tinymce) if you want to report this as a bug. 

But when would you not want the editor to get focus when enabled?

**Comment by d3vkit** [comment]
Thank you for pointing me to the correct repo; I will report there and close this issue.

>But when would you not want the editor to get focus when enabled?

We have multiple inputs between the enabling input and the editor. Users would probably expect at most that the first input in the form would receive focus, if any received focus at all (we don't plan to autofocus here).
