### ISSUE TITLE
Chrome warning :Deprecated Feature Used

### ISSUE THREAD

**Issue by aviyi** [tinymce/tinymce-react#348]
'Event.path' is deprecated and will be removed in M109, around January 2023. Please use 'Event.composedPath()' instead. See https://www.chromestatus.com/feature/5726124632965120 for more details.

**Comment by tiny-james** [comment]
I can't find any usages of `Event.path` in the tinymce-react integration searching all the code both before and after compilation. I also can't find any usages in the tinymce repository either.

If I search for `Event` on its own and `.path` on its own I do see many matches in TinyMCE code (they are common words) but nothing in the tinymce-react integration. There is a note in the TinyMCE changelog about it being removed in 4.8.2.

Please tell me where you think this code is used as I can't find it.

**Comment by tiny-james** [comment]
This warning seems to be coming from a section of code that [iterates over all properties to clone an event](https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/events/EventUtils.ts#L59-L64). We are not specifically accessing the `path` property and so there will be no problem when the `path` property ceases to exist.

Sorry about the warning but there's probably nothing we can do to avoid triggering it. It can be safely ignored.

**Comment by tiny-james** [comment]
Actually we may be able to fix the warning by adding `path` to this list:
https://github.com/tinymce/tinymce/blob/develop/modules/tinymce/src/core/main/ts/events/EventUtils.ts#L31-L40

I'll pass it on to the TinyMCE team.
