### ISSUE TITLE
Custom File Browser

### ISSUE THREAD

**Issue by mstosio** [tinymce/tinymce-react#353]
Is there any option to implement custom fileBrowser as it was on version 3?
https://www.tiny.cloud/docs-3x/howto/TinyMCE3x@How-to_implement_a_custom_file_browser/

I can easily toggle dialog with images using file_picker_callback and then I want to inject image path into insert/edit. I tried to access it with editor ref but I cant find a solution for it.
![image](https://user-images.githubusercontent.com/10117225/176205956-bbe027ac-b7a8-4897-a55a-2b2fb230d99d.png)

The only possible way which I found is isert image directly with 
`editorRef.current.insertContent(IMG_URL)`

**Comment by tiny-james** [comment]
In version 5 of TinyMCE (not the tinymce-react integration which has different versions and has just released 4 to be compatible with TinyMCE 6) the `file_browser_callback` was replaced by the `file_picker_callback`.

I recommend referring to the documentation here:
https://www.tiny.cloud/docs/migration-from-4x/#migratingfromfile_browser_callbacktofile_picker_callback

Note that the most recent version of TinyMCE is 6. If you're upgrading you might as well go to 6, so you can read about upgrading from 5 to 6 here:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
