### ISSUE TITLE
Cannot read property 'unbind' of undefined

### ISSUE THREAD

**Issue by Slasherio** [tinymce/tinymce-react#36]
I installed ```"@tinymce/tinymce-react": "^2.3.0",```
I wrote my own component following the documentation

```js
import React from "react";
import { connect } from "react-redux";

import { Editor } from "@tinymce/tinymce-react";

/**Actions */
import { editorOnChange } from "../../../actions";

class CKEditor extends React.Component {
  handleEditorChange = (content) => {
    const {
      id,
      editorOnChange,
      reducer: { actionType },
    } = this.props;
    editorOnChange(actionType, id, content);
  };

  render() {
    return (
      <Editor
        apiKey="8g8nxiiua9o6rxmlgdkupdq0cwtn4ws1819v8typvr8opxb0"
        init={{
          plugins:"powerpaste",
          toolbar:
            "formatselect | paste | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat | fontselect | fontsizeselect",
          font_formats:
            "Andale Mono=andale mono,times;Arial=arial,helvetica,sans-serif;Arial Black=arial black,avant garde;Comic Sans MS=comic sans ms,sans-serif;Courier New=courier new,courier;Helvetica=helvetica;Tahoma=tahoma,arial,helvetica,sans-serif;Terminal=terminal,monaco;Times New Roman=times new roman,times;Trebuchet MS=trebuchet ms,geneva;Verdana=verdana,geneva;Webdings=webdings;Wingdings=wingdings,zapf dingbats;Akzidenz-Grotesk Std=Akzidenz-Grotesk Std",
        }}
        value={this.props.value}
        onEditorChange={this.handleEditorChange}
      />
    );
  }
}

const mapDispatchToProps = {
  editorOnChange,
};

export default connect(
  null,
  mapDispatchToProps,
)(CKEditor);
```

I use this component at least at 3 different pages. When i'm load this component at first, it's all ok, no crashes, but when i  want to change page to another, where editor component is use too, i have a crash and error at console

```
Uncaught TypeError: Cannot read property 'unbind' of undefined
    at Yx.<anonymous> (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:76)
    at Jg.c.fire (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at Yx.fire (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at rp (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at qx (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at Yx.remove (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at Object.remove (tinymce.min.js?apiKey=0vljbszrz9brsvptl0vgtuitgk4b8rt3wc0c65kj49nmvuz7:8)
    at Editor.componentWillUnmount (Editor.js:71)
    at callComponentWillUnmountWithTimer (react-dom.development.js:14280)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
```

**It only happens when there is plugins property available. If i remove it, everything works good**
Version of Tiny - ```"@tinymce/tinymce-react": "^2.3.0",```

**I updated api key to premium, but the problem has not disappeared**

**Comment by fyrkant** [comment]
Can you share the source to a smaller app showing the issue? It would be a lot easier for me to try to get down to what's happening if I can try it our myself.

**Comment by Slasherio** [comment]
@fyrkant Ok, i'll try to make a simple clone of app in fiddle tommorow

**Comment by einarq** [comment]
The same thing is happening in our app, when quickly moving between pages that contain editors. 
It's related to the powerpaste plugin, removing that plugin removes the issue as well, but that's not an option for us.

Seems related to the event mechanism that is used to tell plugins to clean up after themselves? If this code is async, then the editor might already be unmounted by the time the plugin tries to clean up? Just a guess tho :)

**Comment by TBearSantaCruz** [comment]
We're having the same issue.    Not sure if it is related, but we just moved to licensed version of TinyMCE and added PowerPaste.

TypeError: Cannot read property 'unbind' of undefined
 /build/tinymce/plugins/powerpaste/plugin.min.js:8

***UNHANDLED EXCEPTION*** Error: Uncaught TypeError: Cannot read property 'unbind' of undefined Script: /build/tinymce/plugins/powerpaste/plugin.min.js Line: 8 Column: 175617 

StackTrace: TypeError: Cannot read property 'unbind' of undefined at Yx.<anonymous> (/build/tinymce/plugins/powerpaste/plugin.min.js:8:175617) at Jg.c.fire (/build/tinymce/tinymce.min.js:2:191285) at Yx.fire (/build/tinymce/tinymce.min.js:2:191797) at rp (/build/tinymce/tinymce.min.js:2:192233) at qx (/build/tinymce/tinymce.min.js:2:327388) at Yx.remove (/build/tinymce/tinymce.min.js:2:335695) at Object.execCommand (/build/tinymce/tinymce.min.js:2:343164) at Object._remove (/build/vendor.js:80205:28) at Object.componentWillUnmount (/build/vendor.js:80145:11) at Object.chainedFunction [as componentWillUnmount] (/build/vendor.js:32984:12)
 /build/bundle.js:126432

**Comment by TBearSantaCruz** [comment]
Work-around for us was to make sure the paste-preprocess was set to an empty function if not being used as we change text editor configurations based on context.
paste_preprocess = ()=>{}

**Comment by einarq** [comment]
It seems related to powerpaste, and it seems related to unbind/unload of the editor, which is not really React specific I guess, it just happens to be called from a React component in this case.

**Comment by Slasherio** [comment]
I removed this plugin and all works. But I need this plugin. As I read at documentation -  powerpaste it's a premium plugin and can not be used by default. So i upgraded my api key to premium and tried again. Problem is still exist

**Comment by fyrkant** [comment]
We have found the root of the problem and will release a new version of powerpaste with the fix soon.

**Comment by spocke** [comment]
This should now have been corrected and released to the cloud stable channel.

**Comment by einarq** [comment]
Could you perhaps have forgotten to actually publish the changes? Here is
the only difference in the powerpaste plugin from what we have already

[image: image.png]

**Comment by einarq** [comment]
Never mind. Source-tree was not able to detect the changes, but Beyond
Compare does.

Thanks
