### ISSUE TITLE
Get empty content from onInit func when setting value asynchronously

### ISSUE THREAD

**Issue by Bulala-liu** [tinymce/tinymce-react#361]
> > why is it closed?
> 
> Because the question was answered. There is nothing I can change in the integration to "fix" this problem. You simply have to use the tools that the integration provides to solve it.
> 
> > Is it a way to distinguish which triggers the onEditorChange between onInit and user input?
> 
> Simply query the editor state `onInit` as in the example I gave above. The editor will normalise the input given before the `onInit` happens so you have access to the normalised version which you can use as the unchanged reference to detect changes caused by user input.

Hi,
I still have a problem. When the value is settled asynchronously in the upper form, `onInit` function return empty content. 
Here's a demo.
https://codesandbox.io/s/tinymce-react-editor-controlled-dirty-with-normalisation-forked-e33h0v?file=/src/index.js

_Originally posted by @Bulala-liu in https://github.com/tinymce/tinymce-react/issues/298#issuecomment-1182845919_

**Comment by tiny-james** [comment]
I had not anticipated that problem, thanks for the issue!

Here is the solution I came up with:
https://codesandbox.io/s/getting-normlised-content-for-async-setup-ztwp60

It uses the fact that when the `initialValue` is set it resets the undo levels which means the previous undo level is `undefined`.
```jsx
<Editor
        onAddUndo={(evt, editor) => {
          if (evt.lastLevel === undefined) {
            setNormalisedContent(editor.getContent());
          }
        }}
/>
```

I plan to create an event prop for this situation so doing this is less annoying. I will probably call it `onInitialValue`.

**Comment by Mario-Eis** [comment]
I dont get it. How is this supposed to work with formik or another form library? Passing the form state to initialValue sets the cursor position to the beginning of the line, while typing.
