### ISSUE TITLE
How to locally import language js file?

### ISSUE THREAD

**Issue by CaptainJon** [tinymce/tinymce-react#362]
I have downloaded the language js file, but according to the document, it looks like I have to deploy the js file on a server so I could use the 'language_url' option. However the problem is my application has no access to internet due to the server problem, and i dont want to deploy it on every server where the application runs, so is there any way to import the file locally and be bundled together with the application? I tried the following way, it it has a global vars problem:

`
import { Editor } from '@tinymce/tinymce-react';
import tinymce from 'tinymce/tinymce';
import './zh-Hans.js';
`
this will lead an error 'tinymce is not defined' in React

**Comment by CaptainJon** [comment]
actually I was building it as a public component to npm so my team can use it

**Comment by tiny-james** [comment]
Could you link a replication showing that problem using [code-sandbox](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty)?

If you can avoid it I'd avoid bundling TinyMCE and host it, however there are guides on bundling it for react here:
https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/

There's a bit more information about bundling UI localizations here (not specific to react but you should be able to adapt it):
https://www.tiny.cloud/docs/tinymce/6/bundling-localization/

**Comment by tiny-james** [comment]
Note if you aren't loading the localization from node_modules you might have to follow the zip guide:
https://www.tiny.cloud/docs/tinymce/6/react-zip-bundle/

**Comment by tiny-james** [comment]
Since I can't do more without a replication I'm closing this.
