### ISSUE TITLE
Is it possible to make it compatible with React 18.2?

### ISSUE THREAD

**Issue by shestakov-vladyslav** [tinymce/tinymce-react#367]
Is it possible to make it compatible with React 18.2?

![image](https://user-images.githubusercontent.com/18069756/181267541-22dce9f4-d262-4e26-a958-7c3b7cfd39a8.png)

**Comment by tiny-james** [comment]
That error message is complaining that "react-useportal" does not support react 18 ( it appears to only support react 16 https://github.com/alex-cory/react-useportal/blob/master/package.json#L40 ).

`tinymce-react` supports any react version in the range 16.7 to 18 (well technically that excludes the specific version 17.0.0 but that's not an important detail).
