### ISSUE TITLE
Did I not update the initValue settings in time?

### ISSUE THREAD

**Issue by hexiaochen666** [tinymce/tinymce-react#386]
![image](https://user-images.githubusercontent.com/52769073/192185122-605caacb-68df-462e-ba8c-42f6e665b10b.png)

At first, it was undefined. After refreshing, the initial value was available, but it was not updated?

**Comment by hexiaochen666** [comment]
> Ref: INT-3019

I'm sorry, I don't understand what you mean. Could you be more specific?

**Comment by tiny-james** [comment]
Can you post your editor configuration? Also which version of the integration are you using? Which version of TinyMCE are you using?

The `initialValue` prop can be set asynchronously since version 3.11.0 of the integration, prior to that it had to be set before initializing the editor.

**Comment by tiny-james** [comment]
Here is an example of setting the `initialValue` after the editor has loaded:
https://codesandbox.io/s/asynchronous-initial-value-uh75r4

**Comment by tiny-james** [comment]
Since there has been no reply in a week I am closing this on the assumption it is resolved.
