### ISSUE TITLE
Numbered list

### ISSUE THREAD

**Issue by zilkenberg22** [tinymce/tinymce-react#390]
how to make numbered list like this :
1. Test 1
2. Test 2
    2.1 test 2-1
    2.2 test 2-2
3. Test 3

**Comment by tiny-james** [comment]
That's not supported by TinyMCE directly, however as it is HTML you can get something working with CSS.
https://codesandbox.io/s/css-nested-list-counter-hnj93r

based on the solution here:
https://stackoverflow.com/a/11522260/7377237
