### ISSUE TITLE
All CDN are down

### ISSUE THREAD

**Issue by jeromemiranda** [tinymce/tinymce-react#391]
**What is the current behavior?**
The rich text editor is not being rendered

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**
Basically, just use the latest rich text editor and it will error that the cdn are returning error 502
- https://cdn.tiny.cloud/1/no-origin/tinymce/6.2.0-10/skins/ui/oxide/content.min.css
- https://cdn.tiny.cloud/1/no-origin/tinymce/6.2.0-10/plugins/imagetools/plugin.min.js
- https://cdn.tiny.cloud/1/no-origin/tinymce/6.2.0-10/plugins/toc/plugin.min.js

**What is the expected behavior?**
It should render the editor

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
4.1.0

**Comment by JamieDF** [comment]
Same issue here

**Comment by jeromemiranda** [comment]
Seems like this is now resolved, closing the issue.
