### ISSUE TITLE
Editor not visible on page in tinymce v6

### ISSUE THREAD

**Issue by mwkho** [tinymce/tinymce-react#392]
**What is the current behavior?**
The editor  is on the DOM, yet it's visibility is set to hidden

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

Followed the steps on 
https://www.tiny.cloud/docs/tinymce/6/react-cloud/ to integrate it as a component

**What is the expected behavior?**
Editor component should be visible and rendered with the TinyMCE

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

TinyMCE : 6.2.0
tinymce-react: 4.2.0

![image](https://user-images.githubusercontent.com/16160574/194717948-7071ead4-05d8-4851-8552-01e20ee1ef33.png)

it worked in TinyMCE latest of v5
Seems like modal.js is not being found
![image](https://user-images.githubusercontent.com/16160574/194718228-043ad66c-d78d-48ac-ba24-2f93f341f1a1.png)

**Comment by tiny-james** [comment]
That's quite odd since it should be getting the model from the same location it gets TinyMCE.

Based on the error messages I would assume it is loading TinyMCE from:
`http://localhost:3000/static/js/`

But if you followed that guide you linked then TinyMCE would be coming from the cloud so you'd see requests to `cdn.tiny.cloud` in your network tab.

**Comment by tiny-james** [comment]
I suspect you might be self-hosting the editor, in which case you might want to follow this guide:
https://www.tiny.cloud/docs/tinymce/6/react-pm-host/

**Comment by tiny-james** [comment]
Closing due to lack of information to diagnose the problem.
