### ISSUE TITLE
CDN file get 404 error

### ISSUE THREAD

**Issue by PhamMinhKha** [tinymce/tinymce-react#397]
Real link:  https://cdn.tiny.cloud/1/b287p97b7tdpxut9rhoeq2v9odbh0l29is71adgf3vs65jv7/tinymce/6.2.0-10/plugins/searchreplace%20visualblocks%20code%20fullscreen/plugin.min.js
I try access from the browser but get 404
![image](https://user-images.githubusercontent.com/12944689/197509831-af8ee3da-f1d5-4757-ae10-64130c12835a.png)

I try go back version 3.9 and everything work.
Please check cdn server

**Comment by tiny-james** [comment]
Note that by default version 3.x of the integration loads TinyMCE 5 from the cloud and 4.x of the integration loads TinyMCE 6 from the cloud.

It looks like you have written your plugins like this:
```jsx
<Editor
  init={{
    // .. other config ...
    plugins: ['searchreplace visualblocks code fullscreen'],
  }}
/>
```
Which was valid for TinyMCE 5 but not TinyMCE 6.
As of TinyMCE 6 they [must be written like this](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#plugins):
```jsx
<Editor
  init={{
    // .. other config ...
    plugins: ['searchreplace', 'visualblocks', 'code', 'fullscreen'],
  }}
/>
```
Please check the migration guide for more changes that occurred between 5 and 6.
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/
