### ISSUE TITLE
Init configuration only displays minimal features

### ISSUE THREAD

**Issue by andrewhl** [tinymce/tinymce-react#4]
This is how I'm initializing the component.

```javascript
            <TinyMCE
                init={{
                    plugins: ['advlist autolink autosave lists link image charmap print preview hr anchor pagebreak',
                        'searchreplace wordcount visualblocks visualchars code fullscreen',
                        'insertdatetime media nonbreaking save table contextmenu directionality',
                        'emoticons template paste textcolor colorpicker textpattern imagetools codesample toc help'],
                    toolbar1: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
                    toolbar2: 'print preview media | forecolor backcolor emoticons | codesample help',
                    image_advtab: true,
                    file_browser_callback_types: 'image',
                    file_picker_callback: filePickerCallback,
                    branding: false,
                    height: 400,
                }}
                initialValue={this.props.content}
                onChange={(e) => handleEditorChange(e, this.props)}
            />
```

This is what the output looks like: 
![8zhdry](https://user-images.githubusercontent.com/1120082/33270641-bcb379e8-d352-11e7-9e9e-fc3d94ec7109.png)

This is what it looks like when I use [react-tinymce](https://github.com/instructure-react/react-tinymce):

![screen shot 2017-11-27 at 09 10 22](https://user-images.githubusercontent.com/1120082/33270700-eb97c9ee-d352-11e7-8665-8f41580460d1.png)

Not sure what I'm doing incorrectly. Help would be appreciated.

**Comment by fyrkant** [comment]
How are you loading in TinyMCE? Seems like it isn't loading the plugins correctly.

**Comment by fyrkant** [comment]
Hmm, no it has to be something else, it isn't even removing the branding even though you've set branding to false in the init...

**Comment by fyrkant** [comment]
Are you using the correct component? The component should be imported like this:
`import {Editor} from '@tinymce/tinymce-react';`

I see that you are using a `<TinyMCE />` component, unless you have aliased it I guess the problem is that you are using the wrong component.

**Comment by andrewhl** [comment]
My apologies! I ran yarn add tinymce-react, which installs a different library entirely. I'm using the correct library now and appears to working properly. Many thanks!
