### ISSUE TITLE
Load from CDN

### ISSUE THREAD

**Issue by gbminnock** [tinymce/tinymce-react#40]
**Question**
Hi, 
is it possible to load this from a cdn? in the same manner as I can load react from 
````
<script>//unpkg.com/react@16.0.0/umd/react.production.min.js</script>
````

I found a package which looks correct but am unsure which file I need to use as target: [https://unpkg.com/@tinymce/tinymce-react@2.4.0](https://unpkg.com/@tinymce/tinymce-react@2.4.0)
Any guidance appreciated,
tks

**Comment by fyrkant** [comment]
No there's no cdn build available.
