### ISSUE TITLE
Tinymce react link and table dialog hidden behind full screen editor

### ISSUE THREAD

**Issue by yingying96** [tinymce/tinymce-react#402]
Currently the link and table dialog is hidden behind whenever we click on it in full screen mode.
After exiting the full screen mode, i can see the dialog.

Tried to edit the z-index but it seems to cancel out my own style instead of overriding it.
I have tried to edit it directly (skin.min.css) in browser tools as shown below and it should appear when z-index is 9999.

![image](https://user-images.githubusercontent.com/19566726/201511991-f44bf058-35d8-4065-aa94-486a872e4b2e.png)

**Comment by yingying96** [comment]
Referred to here as well - https://stackoverflow.com/questions/9194217/how-to-set-z-index-on-tinymce-toolbar and https://github.com/tinymce/tinymce/issues/6100

**Comment by yacodes** [comment]
@yingying96 Unfortunately there is not enough info for us to reproduce this issue and it is not related to the Tiny's React integration.

I will close this issue. Please consider opening it in the main `tinymce` repo with the reproducible example hosted on codepen or a similar service.
