### ISSUE TITLE
Links opening in new tab not working

### ISSUE THREAD

**Issue by daniicamanalang** [tinymce/tinymce-react#407]
**What is the current behavior?**
I have added this configuration `default_link_target: '_blank'` for tinymce and it is supposed to open links to a new tab but it is not working on any browser and devices. No target="_blank" is added on source code.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**
Please see this [link](https://codesandbox.io/s/react-tinymce-link-opens-on-new-tab-not-working-2gjmsj)

**What is the expected behavior?**
It displays `<a href="href" target="_blank" />` to the source code so that users can open the link in new tab instead of getting redirected

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
All browsers and devices. Version is: `"@tinymce/tinymce-react": "^4.2.0",`.
This actually works on the latest published version of tinymce but not on react wrapper.

**Comment by lnewson** [comment]
Hi @daniicamanalang,

Looking at the example provided you are using TinyMCE 6 which renamed that option to `link_default_target` as per the [Migration Guide](https://www.tiny.cloud/docs/tinymce/6/6.0-release-notes-core-changes/#things-we-renamed). So if you update it to use `link_default_target: "_blank"` then it should work, or at least does in my testing.

The other option is to swap back to using TinyMCE 5 by using the [cloudChannel](https://www.tiny.cloud/docs/tinymce/6/react-ref/#cloudchannel) property such as `cloudChannel="5"`. One thing to note though if you do that though is that TinyMCE 5 support ends in [April 2023](https://www.tiny.cloud/docs/enterprise/system-requirements/#supportedtinymceversions).

**Comment by yacodes** [comment]
There was no discussion here for a while. Considering this issue solved and closing it.
