### ISSUE TITLE
Cannot disable autofocus

### ISSUE THREAD

**Issue by waynebloss** [tinymce/tinymce-react#41]
Hello and thanks for a great component.

I am having trouble disabling autofocus. Here is what I tried so far:

`<Editor init={{auto_focus: false, ... }} ... />`

and also

`<Editor init={{auto_focus: '', ... }} ... />`

But neither of them works. Whenever I navigate to a page with the Editor, it gets focus.

**Comment by waynebloss** [comment]
Here's my workaround for now. It causes the page to jump around a bit because the `Editor` is all the way at the bottom of the page.

```js
/**
 * This hack re-focuses on a different input after the editor is mounted since
 * disabling the TinyMCE editor auto focus functionality doesn't work.
 * See https://github.com/tinymce/tinymce-react/issues/41
 */
function hackToDisableAutoFocusOnTinyMCE() {
  let attempts = 0;
  function tryResetFocus() {
    // console.log("ATTEMPTING TO RESET FOCUS...");
    const { activeElement } = document;
    // ASSUMPTION: TinyMCE implements the only focusable IFRAME on the page.
    if (activeElement && activeElement.tagName !== "IFRAME") {
      if (++attempts < 15) { // * 100ms = try for 1500ms
        window.setTimeout(tryResetFocus, 100);
        return;
      }
    }
    // console.log("RESETTING FOCUS...");
    // ASSUMPTION: There is only one element with id="name".
    const nameInput = document.getElementById("name");
    if (nameInput) {
      nameInput.focus();
      // Next 2 lines are only needed on Firefox (so far), to scroll top.
      const parentScroller = getScrollParent(nameInput);
      parentScroller.scrollTo({ top: 0, left: 0 });
    }
  }
  window.setTimeout(tryResetFocus, 100);
}
```

**Comment by fyrkant** [comment]
Like my colleague writes [here](https://github.com/tinymce/tinymce/pull/4530#issuecomment-452515663) that's not what `auto_focus` is supposed to do, and adding a way to stop focusing to tinymce is not something that can be fixed in the react wrapper so I'm closing this issue.

**Comment by ljmerza** [comment]
"not something that can be fixed"??? Great professional answer.
