### ISSUE TITLE
No documentation how to access a status bar to add information to it, eg. when creating a new plugin

### ISSUE THREAD

**Issue by ewuski** [tinymce/tinymce-react#410]
**Is your feature request related to a problem? Please describe.**
I am trying to translate this `charactercount `plugin: https://gist.github.com/ClementParis016/ab06847c41160c22f278e4cabe4a0879 to work with @tinymce/tinymce-react@4.2.0

The main problem atm is to get the status bar to add info to it as per this line in the above example:

`var statusbar = editor.theme.panel && editor.theme.panel.find('#statusbar')[0];`

The problem is that `panel` does not exist anymore within `editor.theme` and there is no documentation on where to find the `statusbar `element within `tinymce`.

 **Describe the solution you'd like**
I would like to have access to the status bar element within the tinymce editor within a custom plugin to add information to the statusbar.

 **Describe alternatives you've considered**
There is no alternative.

**Comment by yacodes** [comment]
@ewuski Thanks for the feature request! We've added it to our backlog and will consider implementing it in the future.

I will close this issue though. This feature request concerns only the main `tinymce` repo and not the React integration.

**Comment by yacodes** [comment]
Closing the issue.
