### ISSUE TITLE
Editor sends a request per each created instance

### ISSUE THREAD

**Issue by SergeyShablenko** [tinymce/tinymce-react#42]
I have a page with dynamic number of editors, they may appear or be destroyed. After editor created it sends a request with apiKey. I have a case, when there are like 60+ editors on a page and each sends a request. How could I reduce number of requests? CSS files are requested each time for each instance too.

![selection_077](https://user-images.githubusercontent.com/13334277/49281954-982a9780-f496-11e8-9851-dbf720f4de04.png)
![selection_076](https://user-images.githubusercontent.com/13334277/49281961-9a8cf180-f496-11e8-9769-03dc933815c3.png)

**Comment by fyrkant** [comment]
This is how it has to be because the content.min.css is used inside of an iframe, so it has to request it from the document inside of the iframe. If you use an inline editor it will only load the content css file once.
