### ISSUE TITLE
upon assigning typescript react selector, throws unable to assign string to undefined init

### ISSUE THREAD

**Issue by rahulreddyv** [tinymce/tinymce-react#422]
**What is the current behavior?**
[TypeScript] Type 'string' is not assignable to type 'undefined'.
    11 |         placeholder: "Type Here...",
    12 |         quickbars_selection_toolbar: 'bold italic | blocks | blockquote | quickimage quicktable quicklink',
  > 13 |         selector: "textarea"
       |         ^^^^^^^^
    14 |       }} />
    15 |   </Box>;
    16 | }

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**
it should assign the string to selector on init
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

**Comment by rahulreddyv** [comment]
Also it blurts all these:
TypeError: Cannot read properties of undefined (reading '_owner')
    at t (backend.bundle.js:1:119865)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)
    at t (backend.bundle.js:1:122074)

**Comment by tiny-james** [comment]
The react integration creates the element that the editor is initialized on. For that reason both `selector` and `target` are not allowed.

Please see:
https://www.tiny.cloud/docs/tinymce/6/react-ref/#init
