### ISSUE TITLE
Typescript React, Styles not working in Inline Editor 

### ISSUE THREAD

**Issue by rahulreddyv** [tinymce/tinymce-react#423]
**What is the current behavior?**
Font styles are not working in typescript react. Bold, italics are working through. 

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**
They should be working properly!!! :)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
TinyMCE 6

**Comment by tiny-james** [comment]
In inline mode the editor inherits styling from the page. The editor component does not support styling directly so this is working as intended.

The list of available properties is listed here:
https://www.tiny.cloud/docs/tinymce/6/react-ref/

Here is an example of styling the editor content while using inline mode
https://codesandbox.io/s/styling-editor-with-css-jizo2s?file=/src/index.js

Normally though with inline mode you focus on styling the page as a whole and the editor shares the page styles.
