### ISSUE TITLE
@tinymce/tinymce-react cannot read data base64 in tag <img>

### ISSUE THREAD

**Issue by Quocphu123** [tinymce/tinymce-react#426]
i use`"@tinymce/tinymce-react": "^4.2.0"` and   `"tinymce": "^6.3.1"`

In the code i add content is something like : 
`content = <img height="117" width="497" alt="image.png" src="data:application/png;base64,iVBORw0KGgoAAAA...">` 
but when i check elements in the F12 the result is missing attribute src and dosen't show the image
`<img height="117" width="497" alt="image.png" `

`
<Editor value={content}/>
`

**Comment by kundanbasha** [comment]
what is meant by Ref: INT-3084?

**Comment by kundanbasha** [comment]
@Quocphu123 could you please tell me? how did you fix this issue?

**Comment by tiny-james** [comment]
> what is meant by Ref: INT-3084?

That's a bot which creates a ticket in Jira for us to track this issue. It posts the Jira code here so when we look at the issue directly we can find the related ticket. So in other words just ignore it. :smile:

**Comment by kundanbasha** [comment]
@tiny-james could you please share the solution?

**Comment by Quocphu123** [comment]
@kundanbasha turn out @tinymce/tinymce-react could read data base64 , the problem is in the data.
In my case i just replace the "data:application" to "data:image" and problem solved

`    imgUrl = imgUrl.replace(/application/g, "image")`
