### ISSUE TITLE
Copy paste content not working in Editor plugins max length

### ISSUE THREAD

**Issue by vicky9696v** [tinymce/tinymce-react#428]
**What is the current behavior?**

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

**Comment by tiny-james** [comment]
Please provide a replication and clear instructions I can't understand what you mean.

**Comment by tiny-james** [comment]
Closing as "Can not reproduce" due to insufficient information. If you provide a replication case with understandable instructions I am happy to try again.
