### ISSUE TITLE
Add version mapping table to Readme

### ISSUE THREAD

**Issue by samatcolumn** [tinymce/tinymce-react#445]
**Is your feature request related to a problem? Please describe.**

When upgrading this library in my app it often means that I'll also be upgrading TinyMCE. In order to figure out what version of TinyMCE I am going to get, I have to scan the changelog here.

 **Describe the solution you'd like**

It would be really nice if the README of this repo contained a table mapping version ranges of this library to TinyMCE versions,

 **Describe alternatives you've considered**

N/A

**Comment by tiny-james** [comment]
The general rule is unless you specify the [`cloudChannel` prop](https://www.tiny.cloud/docs/tinymce/6/react-ref/#cloudchannel) you will always get the most recent editor on the cloud. The version of the integration only sets the default value of the `cloudChannel` prop.

In version 0 to 2.x of the integration the `cloudChannel` defaulted to `"4"`.
In version 3.x of the integration the `cloudChannel` defaulted to `"5"`.
In version 4.x of the integration the `cloudChannel` defaulted to `"6"`.

Of course if you load TinyMCE yourself either by specifying the [`tinymceScriptSrc` ](https://www.tiny.cloud/docs/tinymce/6/react-ref/#tinymcescriptsrc)or by adding a script tag to your page then the integration will use whatever version is provided.

The current integration tries to maintain compatibility with TinyMCE versions 4 to 6. It is likely that compatibility with TinyMCE 4 will be dropped in the next major version release to simplify maintenance.

**Comment by tiny-james** [comment]
Note that the information about the cloud channel defaults is already mentioned in the [changelog](https://github.com/tinymce/tinymce-react/blob/main/CHANGELOG.md#400---2022-04-08).
