### ISSUE TITLE
Unable to check your domain because the referer header is missing - React

### ISSUE THREAD

**Issue by aruljayaraj** [tinymce/tinymce-react#447]
**When I open the TinyMCE editor on iPhone through Ionic I'm getting the following error.**

**"We’re unable to check your domain because the referer header is missing. Please read the Guide on how to ensure your referer header is present, so we can then customize your editor experience."**

I've already added the Tinymce Cloud Premium Key in the Editor

![image](https://user-images.githubusercontent.com/414208/225958513-5d27adbf-07dd-45c3-a9a9-8c4916be096c.png)

**I've used "@tinymce/tinymce-react": "^4.3.0"**

**Comment by tiny-james** [comment]
Have you loaded the TinyMCE script on the page separately?

This situation might occur if that script tag is missing the attribute `referrerpolicy="origin"`. 

If the tinymce-react Editor component detects TinyMCE is already loaded on the page it will attempt to use it. If there is no script tag loading TinyMCE then the Editor element will create a script tag with the `referrerpolicy` attribute set to "origin" so this error should not occur.
