### ISSUE TITLE
Rendering tinymce content without editor

### ISSUE THREAD

**Issue by sivai2i** [tinymce/tinymce-react#45]
I want to render tinymce content just for view for specific set of users. I am creating a list which looks fine in editor but when rendering as plain html the spacing is not correct. 

I am using the below configuration,

`{
      resize: false,
      height: 200,
      menubar: false,
      plugins: 'lists',
      toolbar: 'undo redo | styleselect | bold alignleft aligncenter alignright | bullist numlist outdent indent ',
      selector: 'textarea'
}`

Attaching the screenshots for reference,
![i1](https://user-images.githubusercontent.com/6792259/50339132-9d7e7d80-053c-11e9-90aa-0c697411a87b.png)
![i2](https://user-images.githubusercontent.com/6792259/50339137-a0796e00-053c-11e9-9c19-67700ff4a930.png)

**Comment by fyrkant** [comment]
The CSS in the editor can be changed so it looks the same as on your published page by using the `content_css` setting: https://www.tiny.cloud/docs/configure/content-appearance/#content_css
