### ISSUE TITLE
tinymce6 does not support react18.2

### ISSUE THREAD

**Issue by FrancisKaneY** [tinymce/tinymce-react#450]
**What is the current behavior? Describe the bug**

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: front-admin-new@0.1.0
npm ERR! Found: react@undefined
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.0.0 || ^17.0.1 || ^16.7.0" from @tinymce/tinymce-react@4.3.0
npm ERR! node_modules/@tinymce/tinymce-react
npm ERR!   @tinymce/tinymce-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [fiddle.tiny.cloud](https://fiddle.tiny.cloud/) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE?**

**Comment by danoaky-tiny** [comment]
It should be compatible with React 18.2.0, see https://github.com/tinymce/tinymce-react/blob/4d4a5610c480d0f2c51ff3435794b3b0fa4cf164/package.json#L33

Perhaps try regenerating your package manager's lockfile: _package-lock.json_, _yarn.lock_, _pnpm-lock.yaml_, etc
