### ISSUE TITLE
The fontselect not working.

### ISSUE THREAD

**Issue by Jatin0302** [tinymce/tinymce-react#453]
Right now we are not getting the separate dropdown of font family selection. 
For current solution, we have added the CDN link (https://cdn.tiny.cloud/1/qagffr3pkuv17a8on1afax661irst1hbr4e6tbv888sz91jc/tinymce/5/tinymce.min.js).
I know that it is not correct way but it is not working with this package so please provide the correct way.

**Comment by TinyITAdmin** [comment]
Ref: INT-3176

**Comment by Jatin0302** [comment]
Hello can you provide the link form it?

**Comment by tiny-james** [comment]
If you want to load Tinymce 5 instead of TinyMCE 6 set the `cloudChannel` prop.
https://www.tiny.cloud/docs/tinymce/6/react-ref/#cloudchannel

**Comment by tiny-james** [comment]
Alternatively you can upgrade to TinyMCE 6, I am guessing you are still using `fontselect` instead of `fontfamily`:
https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#things-we-renamed

Though that is a question for the tinymce repository.
