### ISSUE TITLE
expose interfaces for typescript

### ISSUE THREAD

**Issue by megacherry** [tinymce/tinymce-react#454]
I just wrote a function that handles the upload and need the BlobInfo interface for it. Unfortunately the interfaces are not exported.

Can interfaces be exported?

**Comment by TinyITAdmin** [comment]
Ref: INT-3177

**Comment by tiny-james** [comment]
This question should be asked on the `tinymce` repository as it is related to TinyMCE not this react integration.

The interfaces are available but you have to go via the editor options.

```ts
// get the type from the tinymce repository
import { EditorOptions  } from 'tinymce';

// when you assign the upload handler type it will give blob and progress the correct types
const upload: EditorOptions['images_upload_handler'] = async (blob, progress) => {
  return "image.jpg";
}
```

Alternatively you can extract the `BlobInfo` type from the method parameters:
```ts
type BlobInfo = Parameters<NonNullable<EditorOptions['images_upload_handler']>>[0];
```

**Comment by megacherry** [comment]
Thank you :)
