### ISSUE TITLE
Editor functionality conflicts with MUI in React

### ISSUE THREAD

**Issue by tdusman** [tinymce/tinymce-react#455]
I am getting the source code area disabled in tinymce editor when implementing the editor in MUI components (paper, card, and box etc). Also not allowing me to scroll the page from editor textarea when using the scrollbar from this package (react-perfect-scrollbar).

**versions:**
"@tinymce/tinymce-react": "^4.1.0"
"react": "^17.0.2"
"typescript": "^4.6.4"
"@mui/material": "^5.7.0"
"react-perfect-scrollbar": "^1.5.8"

**Comment by TinyITAdmin** [comment]
Ref: INT-3180

**Comment by danoaky-tiny** [comment]
Could you please provide a demo using the provided template: https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js, then we're happy to help you further.
