### ISSUE TITLE
hitting enter causes screen to jump

### ISSUE THREAD

**Issue by ccbiozhaw** [tinymce/tinymce-react#456]
**What is the current behavior?**

when i hit enter the screen jumps

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

![image](https://github.com/tinymce/tinymce-react/assets/80820813/57cda74c-cd12-4030-804c-840e9e36d4de)
 -> hit enter

![image](https://github.com/tinymce/tinymce-react/assets/80820813/a711de4b-c203-477e-88e7-530c4e2affef)
-> screen jumps to this

i can also see that when the editor is in full screen: this is the offical example available here:

https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/

![image](https://github.com/tinymce/tinymce-react/assets/80820813/2c9ff52d-bec8-4232-b7a2-b4e1561184db)

after hitting enter
![image](https://github.com/tinymce/tinymce-react/assets/80820813/20b35d21-04bd-469e-a175-70c20132fbab)

**What is the expected behavior?**

the screen doesnt jump.

**steps to reproduce**

go to :
https://www.tiny.cloud/docs/tinymce/6/full-featured-open-source-demo/

open fullscreen without scrolling down! then hit enter and it will push the editor down.
if you scroll down before going fullscreen it will not even open properly ( i also see that in my own project)

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
google chrome

**Comment by TinyITAdmin** [comment]
Ref: INT-3184

**Comment by ccbiozhaw** [comment]
i noticed it doesnt happen in the basic example so i went trhough all options:

it is cused by this:

          // toolbar_sticky: true,

removing it fixes the problem

**Comment by tiny-james** [comment]
This is probably a issue that should be forwarded to the TinyMCE repository. The tinymce-react project does not handle the `toolbar_sticky` setting, it is passed directly to TinyMCE.

**Comment by TheSpyder** [comment]
Sorry about this one. It was a core issue - https://github.com/tinymce/tinymce/issues/8832 - fixed in TinyMCE 6.7
