### ISSUE TITLE
TypeError: editor.setMode is not a function

### ISSUE THREAD

**Issue by cMack87** [tinymce/tinymce-react#458]
Editor.js:168 refers to the function "setMode" which was deprecated and then removed, as described [here](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/#previously-deprecated-items-now-removed).

**Comment by TinyITAdmin** [comment]
Ref: INT-3195

**Comment by tiny-james** [comment]
This is working as intended. Check the comment on the source code to see why:
https://github.com/tinymce/tinymce-react/blob/main/src/main/ts/Utils.ts#L104-L112

Basically this component supports TinyMCE 4, 5 and 6. TinyMCE 4 does not have the modern way of setting this value.
