### ISSUE TITLE
Changing Theme while the component is on DOM does not work.

### ISSUE THREAD

**Issue by Manj0tBenipal** [tinymce/tinymce-react#460]
Changing the theme of the editor requires **unmounting** and then **mounting** the editor again.

The live demo of the project is available [here](https://codesandbox.io/p/github/Manj0tBenipal/Notes/master?file=/src/App.js:67,13&workspaceId=33e38fd0-9078-4574-8c2e-0e8c8303ceb0)

When a prop being passed down to the parent component changes, the parent component runs a useEffect() which changes the init object(stored in the state) passed down to the editor as a prop.  However, it does not take effect until the component is unmounted and mounted again.
 
The browser used for testing is Chrome.

**Comment by TinyITAdmin** [comment]
Ref: INT-3206

**Comment by shanmen-tiny** [comment]
Hello @Manj0tBenipal,

This is a known problem. The only workaround is changing the key to force a reinit of the editor. TinyMCE does not support changing the theme without a reinit.
