### ISSUE TITLE
Type 'string' is not assignable to type 'never'

### ISSUE THREAD

**Issue by sh-shoaib** [tinymce/tinymce-react#461]
When passing the value of the '[selector](https://www.tiny.cloud/docs/configure/integration-and-setup/#selector)' attribute as `div#${id}` then it is throwing an error.

`Error: Type 'string' is not assignable to type 'never' `

![TinyMCE Error](https://github.com/tinymce/tinymce-react/assets/105193391/bf07db12-baef-4a52-b6e2-283b28cfd85f)

As the `selector` attribute type is defined as `never`.

**Comment by TinyITAdmin** [comment]
Ref: INT-3208

**Comment by danoaky-tiny** [comment]
The selector prop isn't used or needed for tinymce-react.
See: https://www.tiny.cloud/docs/tinymce/6/react-ref/#init

> When using tinymce-react:
> * The init prop does not require the selector or target options
> * If the selector, target, or readonly options are set using the init prop, they will be overridden by the integration.

We've intentionally omitted the `selector` and `target` props from `RawEditorSettings` because of this.
