### ISSUE TITLE
Can't type anything on Toolbar Insert/Edit Image

### ISSUE THREAD

**Issue by Briyan-NS** [tinymce/tinymce-react#462]
**Does someone ever face this kind of issue? So i can't type anything on Insert/Edit Image toolbar while using it on my project.**

**Here is my screen record**
https://www.awesomescreenshot.com/video/19392842?key=acb20e0370078f3059225c30e329dc01

I think this should be typeable

Currently this is the library that I've installed **"@tinymce/tinymce-react": "^3.12.3",**

Please help me to figure out this issue? Thanks a lot before

**Comment by TinyITAdmin** [comment]
Ref: INT-3209

**Comment by Briyan-NS** [comment]
Actually, this issue has been resolved by today. Just add the enforceFocus key inside the modal and put the value with false. 
This tinyMCE comes from Modal Bootstrap basically

![image](https://github.com/tinymce/tinymce-react/assets/98829641/935cb54c-5c48-40bf-b6c9-8e4a45c71c78)
