### ISSUE TITLE
The editor spend a long time to initialize when first load.

### ISSUE THREAD

**Issue by wangwanlin-97** [tinymce/tinymce-react#463]
**What is the current behavior?**
As the title, it is slow because it fetch plugins from cdn although plugins are already in subfolders.

![image](https://github.com/tinymce/tinymce-react/assets/55093874/7b581e16-0fe1-40e0-83f7-c2ffd488f275)

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**

I wonder is there any way to use existed plugin filed other than fetch form cdn.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

@tinymce/tinymce-react": "^4.3.0

**Comment by danoaky-tiny** [comment]
You can choose to use your package manager to host TinyMCE, see either (depending on your implementation):
https://www.tiny.cloud/docs/tinymce/6/react-pm-host/
https://www.tiny.cloud/docs/tinymce/6/react-pm-bundle/

If you're using premium plugins, then you can also use a hybrid mode to achieve this. Let us know and we can help further if needed.
