### ISSUE TITLE
Dark mode to light mode not working

### ISSUE THREAD

**Issue by isaacdarcilla** [tinymce/tinymce-react#464]
**What is the current behavior?**

Trying to switch from dark mode to light mode, docs here https://www.tiny.cloud/blog/dark-mode-tinymce-rich-text-editor/

![image](https://github.com/tinymce/tinymce-react/assets/22732118/a2f6ddc3-c784-436a-8fa8-b7601bebb257)

It seems it cannot find the right styles when switching to light mode., thus it does not render the editor.

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]

```js
init={{
          skin: (localStorage.theme === 'dark' ? 'oxide-dark' : ''),
          content_css: (localStorage.theme === 'dark' ? 'dark' : ''),
          ...
}}
```

**What is the expected behavior?**

Light mode editor should be rendered.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Latest

**Comment by TinyITAdmin** [comment]
Ref: INT-3214

**Comment by isaacdarcilla** [comment]
```js
skin: (localStorage.theme === 'dark' ? 'oxide-dark' : 'snow'),
content_css: (localStorage.theme === 'dark' ? 'dark' : 'default'),
```

Ahh my mistake. Fixed!
