### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'removeChild') in Editor when umounting the Editor component from UI

### ISSUE THREAD

**Issue by ashukumar2001** [tinymce/tinymce-react#466]
**What is the current behavior?**
When i render the Editor component this cannot read properties of null error will be thrown.
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

**What is the expected behavior?**

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

**Comment by TinyITAdmin** [comment]
Ref: INT-3217

**Comment by ashukumar2001** [comment]
what is INT-3217?

**Comment by danoaky-tiny** [comment]
We need more information. Please provide a demo of your problem with [codesandbox.io](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) (or similar) and we're happy to help further.
