### ISSUE TITLE
TInyMce version 6.3.1 Not Working

### ISSUE THREAD

**Issue by dpratyash** [tinymce/tinymce-react#469]
I Update My tinymce from 5.6.2 to 6.3.1
But I am getting Error in My Local as 

**`Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#4c8ad70e-8dae-428b-a165-f10f727f9156' is not a valid selector.`**

Anything I am missing Here ??
Or any Other version Update Missing ??

**Comment by TinyITAdmin** [comment]
Ref: INT-3223

**Comment by dpratyash** [comment]
@TinyITAdmin 
Where is the Link ??

**Comment by shanmen-tiny** [comment]
Hi @dpratyash,

We need more information on this case to replicate the issue - preferably an example. Can you please supply your replication code using the codesandbox template available here:
[https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js](https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js)
