### ISSUE TITLE
Custom plugin Button Loses Disabled State on Additional State Update

### ISSUE THREAD

**Issue by Stanislavussov** [tinymce/tinymce-react#471]
**What is the current behavior?**
Despite setting the `enabled` property of a custom plugin to false, and adding an additional state that causes the component with the WYSIWYG editor to rerender, the button's enabled state gets reset after each render.

**What is the expected behavior?**
The `enabled` state should remain consistent across rerenders.

**Which versions of TinyMCE, and which browser/OS are affected by this issue? Did this work in previous versions of TinyMCE or tinymce-react?**
Browser: Version 116.0.5845.179 (Official Build) snap (64-bit)
OS: Ubuntu
NPM Package Version: `"@tinymce/tinymce-react": "^4.3.0"`

**Comment by TinyITAdmin** [comment]
Ref: INT-3228

**Comment by danoaky-tiny** [comment]
Just need a bit more info, could you please provide a code snippet of what you're trying to achieve?
