### ISSUE TITLE
Option to debounce onEditorChange calls

### ISSUE THREAD

**Issue by ThiefMaster** [tinymce/tinymce-react#473]
This would allow making the editor a controlled component while greatly reducing performance issues while typing.

Currently I'd have to implement all the events manually, because while I could debounce the callback passed to `onEditorChange`, this would not help because `getContent` is called internally.

The debouncing would also work pretty nicely together with the auto-rollback because the two timeouts could be aligned (rollback being slightly higher than debounce).

**Comment by TinyITAdmin** [comment]
Internal Ref: INT-3234

**Comment by danoaky-tiny** [comment]
This _may_ work, but it's worth noting that if you're worried about efficiency, you might be better off with an uncontrolled editor and just query the editor's content when you need it.

Introducing a debounce to `onEditorChange` could cause some unreliable behaviour with content being mismatched if were to go out of sync. But in saying that it could be worth a try, so you're more than welcome to put in a PR for your suggestion and we can discuss it further.

**Comment by ThiefMaster** [comment]
please keep it open
