### ISSUE TITLE
Editor inside "react-bootstrap" modal body seen shrink in size

### ISSUE THREAD

**Issue by sushantjadhav111** [tinymce/tinymce-react#474]
Tried to apply 100% width,and other couple of styles, but its not accepting

Code Implementation: 
 <Modal.Body className="p-0">
      <Editor
        id={id}
        apiKey={ApiUrlConstants.tinyMCEKey}
        value={value}
        onEditorChange={handleChange}
        init={{
          menubar: false,
          branding: false,
          height: 250,
          width: width?width:600,
          plugins: [
            "advlist autolink lists link image charmap print preview anchor",
            "searchreplace visualblocks code fullscreen",
            "insertdatetime media table paste code help wordcount",
          ],
          toolbar:
            "undo redo | " +
            "bold italic underline | alignleft aligncenter " +
            "alignright | bullist numlist | outdent indent | copy paste",
        }}
      />
     </Modal.Body>

any solution for this?

<img width="1305" alt="Screenshot 2023-09-28 at 5 35 25 PM" src="https://github.com/tinymce/tinymce-react/assets/71134943/e6bd19a4-6725-49e6-bd9b-400e84041ed3">

**Comment by danoaky-tiny** [comment]
I've tried to replicate the implementation you gave along with the base example of a modal from react-bootstrap's documentation and I haven't been able to replicate this issue: [codesandbox](https://codesandbox.io/p/devbox/nice-river-34f4zr?file=%2Fsrc%2Findex.js%3A51%2C27&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clp7cpd0m0007356ggsn33pl7%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clp7cpd0m0003356gawkdzah7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clp7cpd0m0005356guh4rr3be%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clp7cpd0m0006356gy19zg8jr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clp7cpd0m0003356gawkdzah7%2522%253A%257B%2522id%2522%253A%2522clp7cpd0m0003356gawkdzah7%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp7cpd0k0002356gy4q4qx2n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clp7cuvom00gn356gpnzezgka%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clp7cpd0k0002356gy4q4qx2n%2522%257D%252C%2522clp7cpd0m0006356gy19zg8jr%2522%253A%257B%2522id%2522%253A%2522clp7cpd0m0006356gy19zg8jr%2522%252C%2522activeTabId%2522%253A%2522clp7d6ty404w9356go4mkac5u%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clp7d6ty404w9356go4mkac5u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clp7cpd0m0005356guh4rr3be%2522%253A%257B%2522id%2522%253A%2522clp7cpd0m0005356guh4rr3be%2522%252C%2522activeTabId%2522%253A%2522clp7d6qu304tn356g10ax4zfb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clp7cpd0m0004356g0tk93aax%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clp7cphwm000begev3bmc9nkc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clp7d6qu304tn356g10ax4zfb%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

Could you please provide your own code sandbox? You can fork the one I've linked above if you'd like.

Also I'm assuming `width: width?width:600,` is just a typo/error in the issue description?
