### ISSUE TITLE
Read only mode not work

### ISSUE THREAD

**Issue by Sergey-lang** [tinymce/tinymce-react#477]
Preview mode does not work. The editor is still clickable and I can edit the content.
 mode: 'readonly', -  didn't work
 readonly: true -  didn't work
 
- the useEffect works, but it does not always.
- (mozila) - If you make the Internet connection slower, it does not work (throw error - tinymce is not defined) and i can edit content

Mozila Firefox. Network Regular 4G (users with bad connection can't click on button because it's content for editing)
![image](https://github.com/tinymce/tinymce-react/assets/63201050/026b038f-26f9-4e3c-b023-e9f68b709d0f)
![image](https://github.com/tinymce/tinymce-react/assets/63201050/72de0609-6c6b-4748-8797-c97437d049d0)

https://codesandbox.io/s/nervous-star-8fd7qj?file=/src/index.js

**What is the expected behavior?**
I can't edit content.
I can view the content as in preview mode . Click links and navigate as if I saw a normal page

the task is to show the content from the editor while maintaining the same formatting, styles, fonts as the usual page content

"tinymce": "^6.1.2", 
 "@tinymce/tinymce-react": "^4.2.0",
Chrome / Mozila

**Comment by danoaky-tiny** [comment]
The property you're looking for is [disabled](https://www.tiny.cloud/docs/tinymce/6/react-ref/#disabled).

You can see an example of how it works here: [Storybook](https://tinymce.github.io/tinymce-react/?path=/docs/editor--toggle-disabled-prop), and [source code](https://github.com/tinymce/tinymce-react/blob/main/src/stories/Editor.stories.tsx#L121-L134)

**Comment by Diveafall** [comment]
What is the purpose of the `readonly` property inside `init` of you can still edit?

**Comment by danoaky-tiny** [comment]
@Diveafall See https://www.tiny.cloud/docs/tinymce/6/react-ref/#init
Setting the `readonly` prop within `init` is overriden.

**Comment by Diveafall** [comment]
I understand. If the property doesn't do anything (is overridden anyway) I would prefer it not existing at all.
