### ISSUE TITLE
@storybook/storybook-deployer leaked into dependencies

### ISSUE THREAD

**Issue by Senderek** [tinymce/tinymce-react#479]
**What is the current behavior?**
`@tinymce/tinymce-react` contains `@storybook/storybook-deployer` in the dependencies in package.json, which cascades to all configurations consuming `@tinymce/tinymce-react@4.3.1`

**Steps to reproduce**
```
npm install @tinymce/tinymce-react@4.3.1
```

**What is the expected behavior?**
Package forces the consuming application to only download the packages that are used during runtime when using `npm i`

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
Version: 4.3.1
PR: https://github.com/tinymce/tinymce-react/pull/478
In previous versions the dependency array only contained `prop-types` and `tinymce`

**Comment by shanmen-tiny** [comment]
Hi @Senderek and @zavan ,

Thank you for reporting, and the issue has been addressed in #483, and we have removed the `storybook-deployer` dependency. A new version `tinymce-react` version (4.3.2) has been released and is now available for download from npm.
