### ISSUE TITLE
menubar not acting like should

### ISSUE THREAD

**Issue by vicky-conexa** [tinymce/tinymce-react#480]
**Issue Description:**

For some reason, my menubar is not behaving as it should. The menu items lack margin and padding, appearing tightly packed together. I am providing the code and screenshots for reference.
I'm working with React + TS and NextJs.

**Code:**

`<Editor
					apiKey={key}
					init={{
						plugins:
							'preview importcss searchreplace autolink autosave save directionality code visualblocks visualchars fullscreen image link media codesample table charmap pagebreak nonbreaking anchor insertdatetime advlist lists wordcount charmap quickbars emoticons accordion',
						editimage_cors_hosts: ['picsum.photos'],
						menubar: 'file edit view insert format tools table',
						toolbar:
							'undo redo | accordion accordionremove | blocks fontfamily fontsize | bold italic underline strikethrough | align numlist bullist | link image | table media | lineheight outdent indent| forecolor backcolor removeformat | charmap emoticons | code fullscreen preview | save print | pagebreak anchor codesample | ltr rtl',
						autosave_ask_before_unload: true,
						autosave_interval: '30s',
						autosave_prefix: '{path}{query}-{id}-',
						autosave_restore_when_empty: false,
						autosave_retention: '2m',
						image_advtab: true,
						importcss_append: true,
						file_picker_callback: handleFile,
						height: 400,
						language: 'es',
						image_caption: true,
						quickbars_selection_toolbar:
							'bold italic | quicklink h2 h3 blockquote quickimage quicktable',
						noneditable_class: 'mceNonEditable',
						toolbar_mode: 'wrap',
						contextmenu: 'link image table',
						branding: false
					}}
					onEditorChange={handleEditorChange}
					value={initialValue}
					onSaveContent={handleSave}
				/>`
**Photos**
<img width="1053" alt="Screenshot 2023-11-16 at 12 58 37" src="https://github.com/tinymce/tinymce-react/assets/143446808/e257eead-a3d7-427c-8ca1-d974c6718a0d">

**Comment by danoaky-tiny** [comment]
I can't seem to replicate your problem, see [codesandbox](https://codesandbox.io/p/sandbox/int-3253-xvm564).
Could you please provide your own Code Sandbox? You can fork the one I linked if you'd like.

**Comment by danoaky-tiny** [comment]
Confirmed to be the same bug as #490

**Comment by danoaky-tiny** [comment]
Confirmed to be fixed in the next release: https://github.com/tinymce/tinymce/pull/9261
You can see for yourself here https://fiddle.tiny.cloud/kyIaYQ3ZnL/3
