### ISSUE TITLE
v3.12.6 peerDependencies Resulting in the introduction of React 17.0.2 into my project

### ISSUE THREAD

**Issue by debughao** [tinymce/tinymce-react#486]
"peerDependencies": {
    "react": "^17.0.1 || ^16.7.0",
    "react-dom": "^17.0.1 || ^16.7.0"
  },
 instead of
 "peerDependencies": {
    "react": ">=16.9.0",
    "react-dom": ">=16.9.0"
  }

**Comment by danoaky-tiny** [comment]
If I understand your problem correctly, you'll either need to downgrade your version of tinymce-react to a version that supports React v16, or upgrade your version of React. Which at that point you may as well look into upgrading to the latest version of each and weigh up how much work the migration is.

**Comment by debughao** [comment]
Can tinymce-react support react 16 or later?
peerDependencies: change react to >=16.x

**Comment by danoaky-tiny** [comment]
My mistake, it already supports React v16. See:
https://github.com/tinymce/tinymce-react/blob/e2b1907eadb751f81e01d8239fdf876e77430d43/package.json#L33
