### ISSUE TITLE
Inline + fixed_toolbar_container causes CSS files to not load

### ISSUE THREAD

**Issue by gperl27** [tinymce/tinymce-react#490]
**What is the current behavior?**

There's very inconsistent loading behavior of `content.inline.min.css` when using a combination of `inline` and `fixed_toolbar_container`. It seems when the CSS assets are cached, `content.inline.min.css` won't load at all, causing the toolbar to looked squished and unusable.

This seems to have started about 1-2 weeks ago and perhaps related to the CSS asset architecture updates introduced in the latest JS library.

This is urgent for our team as it broke our production application and even locking in a previous version using `cloudChannel` doesn't seem to resolve the issue.

Possibly related: #480 

Codesandbox:
<img width="728" alt="Screenshot 2023-12-05 at 11 35 44 AM" src="https://github.com/tinymce/tinymce-react/assets/15915958/7fd11ed4-4b48-493a-81cd-bab5e22b0b07">

Production application:
<img width="783" alt="Screenshot 2023-12-04 at 3 13 08 PM" src="https://github.com/tinymce/tinymce-react/assets/15915958/62059a4d-5a53-4b8f-8377-e5388909fd11">

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io]
(https://codesandbox.io/s/tinymce-tinymce-react-p6bqty?file=/src/index.js) or similar.**

Reproducible [codesandbox](https://codesandbox.io/p/sandbox/int-3253-forked-5vtk83?file=%2Fsrc%2Findex.js%3A20%2C11-20%2C34)

It's inconsistently reproducible when doing either refreshes or hard refreshes.

**What is the expected behavior?**

To load the CSS normally

Production app when it works:
<img width="824" alt="Screenshot 2023-12-05 at 11 55 36 AM" src="https://github.com/tinymce/tinymce-react/assets/15915958/d98ffc4c-52d7-48d5-9998-ed7813180260">

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
- All browsers
- Latest version of the React component using the `apiKey` cloud strategy. The production app uses a premium key.

**Comment by danoaky-tiny** [comment]
First off It's worth mentioning that if you have a support subscription, you'll be better served by our support team who will be able to assist: https://support.tiny.cloud/hc/en-us/requests/new 

A workaround for now: are you sure setting `cloudChannel` to 6.7.3 doesn't fix the issue? Setting `cloudChannel` to 6 will (as of right now) set the version to 6.8.1

**Comment by danoaky-tiny** [comment]
Confirmed to be fixed in the next release: tinymce/tinymce#9261
You can see for yourself here https://fiddle.tiny.cloud/kyIaYQ3ZnL/3
