### ISSUE TITLE
 Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector

### ISSUE THREAD

**Issue by SuperChuck83** [tinymce/tinymce-react#494]
**this problem is reproductible in your storybook https://tinymce.github.io/tinymce-react/?path=/story/editor--iframe-editor**

**What is the current behavior?**

since the 6 december 2023, tinymce react failed to init in chrome 87 to 119.
the problem comes from the component "Editor".

with the error above in the browser console: 
 "Failed to execute 'querySelectorAll' on 'Element': 'map:not(svg map),canvas:not(svg canvas),del:not(svg del),ins:not(svg ins),a:not(svg a)' is not a valid selector" 

**What is the expected behavior?**
should work on older version of chrome. ( <120 )

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

Version  
    "@tinymce/tinymce-react": "4.3.0" 
or 
    "@tinymce/tinymce-react": "4.3.2" 

chrome vesion : 87 to 119., it's working on the chrome V120 and after.

**Comment by danoaky-tiny** [comment]
This is a core TinyMCE issue. I'll close this as I can see you've opened an issue there as well.
