### ISSUE TITLE
TinyMCE requires standards mode.

### ISSUE THREAD

**Issue by PanetiX** [tinymce/tinymce-react#495]
Hello, TinyMCE won't load because: "Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode."

On my page i use "<!DOCTYPE html>" as beginning but for some reason (i REALLY don't know why, or where this comes from) at the first point of my site is a "DDD". I searched all files on my server bot this "DDD" is on no file. I searched all files using the grep command on my linux server.

it looks like this:

```
DDD<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="DE">
<head>     
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
```

how to disable in TinyMCE, that the doctype is requied?

What i have tried:

i add to the tinymce.init the following code:
`     doctype: '<!DOCTYPE html>',`

**Comment by danoaky-tiny** [comment]
There's no way to force start TinyMCE if it's detected the webpage is not in standards mode. So unfortunately the only way to fix this is to find the cause of your phantom "DDD" you see.
If you have any other questions let us know.
