### ISSUE TITLE
TinyMCE doesn't load in IE11

### ISSUE THREAD

**Issue by roebuk** [tinymce/tinymce-react#5]
I've just embedded the `<Editor />`  component within my application and visited the demo (https://tinymce.github.io/tinymce-react/) and noticed that TinyMCE fails to load in IE11. It loads fine in Chrome, Firefox, Edge and Safari.

I'm currently using React 15.6.1 and rendering my Editor component like so:

   
    <Editor
      init={tinymceConfig}
      initialValue={value}
      inline={false}
      onChange={handleChange}/>

It appears to be failing silently as there are no errors being logged to the console. Any ideas what could be causing this?

I'll do a little more digging when I get some more free time.

**Comment by fyrkant** [comment]
Hi! 
I haven't gone that deep on this but I'm not sure if React itself works with IE11 without polyfills? See: https://reactjs.org/docs/javascript-environment-requirements.html

I'll test adding some polyfills when I have time and see if it works better.

Thank you for this issue!

**Comment by roebuk** [comment]
IE11 contains `Map` and `Set`, it's only lower than IE10 requires the polyfill. Fingers crossed, I'll have some time today to take a dive into this.

**Comment by fyrkant** [comment]
I looked into it a little but I only figured out that it is the webpack bundle that is causing the problem, I get the error:

`SCRIPT5007: Unable to get property 'configurable' of undefined or null reference`

From this line in the bundle:

```js
  // This condition is true in modern browsers that implement Function#name properly
  var canConfigureName = (0, _getOwnPropertyDescriptor2.default)(handler, 'name').configurable;
```

Not sure what to do with that information, though... 🤔

**Comment by roebuk** [comment]
I'm going to close this issue as after some research I don't believe it's an issue with `tinymce-react`. 

As you mentioned it appears to be more of an issue with TinyMCE being bundled through Webpack. 

Thank you for your time. :)
