### ISSUE TITLE
Unable to create multiple instances on same page

### ISSUE THREAD

**Issue by brymon68** [tinymce/tinymce-react#50]
Hello, 

My apologies, but I'm unable to find React-specific documentation for TinyMCE. 

I'm trying to render two different instances of TinyMCE, but they seem to render the same initialValue no matter how many different ways I try to key them, add ids, etc: 

```
<div>
     <div id="remote" className="remote">
         <h1>Changes on server: </h1>
            <Editor
                  key={1}
                  id={1}
                  className="remote"
                  initialValue={this.props.remoteconflict}
                  disabled={true} />
        </div>
         <br />
        <div id="local" className="local">
            <h1>Your changes: </h1>
             <Editor
                  key={2}
                  id={2}
                  className="local"
                  initialValue={this.state.localconflict}
                  onEditorChange={this.handleEditorChange}
                    }
                  }}
                />
              </div>
            </div>
```

 Any ideas how I can get this to work?

**Comment by fyrkant** [comment]
Hmm, you shouldn't have to set `id` or `key` to get this to work... And it seems to work for me here:
https://codesandbox.io/s/13jwrolz1j

**Comment by brymon68** [comment]
Hmm. Stripping off classname, key and id seemed to fix but I swear I had tried this. This can be closed and thanks for sandbox @fyrkant
