### ISSUE TITLE
Any reason why react & react-dom are direct dependencies of the app?

### ISSUE THREAD

**Issue by ahmedelgabri** [tinymce/tinymce-react#51]
Any reason why react & react-dom are direct dependencies of the app? instead of specifying a range of peer dependencies or explicitly mention in the docs that you need specific version?

Because any project using this package is 100% using react. So, if you specify it as a peer dependencies with a range or explicitly mention in the readme or changelog or something the minimum version required it will be better than having two version of react in your bundle.

**Comment by fyrkant** [comment]
No you are correct, they should be peerDeps!

**Comment by fyrkant** [comment]
Hmm, I wonder what range of versions I should use?

**Comment by ahmedelgabri** [comment]
Same as this, no? https://github.com/tinymce/tinymce-react/blob/c553bdd608cad36fb8de7531d99817f85b18d6ae/package.json#L47-L48

**Comment by fyrkant** [comment]
Hmm, or should it be devDependencies maybe? Because otherwise you can't really run the tests...

**Comment by fyrkant** [comment]
Ahh, it should be both peer and dev I think!

**Comment by fyrkant** [comment]
This is fixed now!

**Comment by ahmedelgabri** [comment]
Thanks!
