### ISSUE TITLE
Loading external plugins from local machine

### ISSUE THREAD

**Issue by codeforsure** [tinymce/tinymce-react#52]
Hi i had a plugin in my local machine and i try to integration it in existing build using the following code
```
external_plugins: {
    'eqneditor':'file:///Users/varun.meka/Desktop/tiny_mce_v3.5.8⁩/plugins⁩/equation⁩/editor_plugin.js'
  },
```
but it's not loading

**Comment by fyrkant** [comment]
The file has to be on a web server, not just on your computer.

**Comment by codeforsure** [comment]
Can't I load plugins from my local machine

**Comment by fyrkant** [comment]
You can run a simple http server on you local machine and use that address.

**Comment by codeforsure** [comment]
```
external_plugins: {
    'eqneditor':'http://0.0.0.0:8000/editor_plugin.js'
  },
plugins: 'eqneditor',
toolbar1: 'formatselect eqneditor| bold italic strikethrough'
```
i was running it on server, it's showing no error but still can't load the plugin

**Comment by codeforsure** [comment]
Hi @fyrkant  , I found the issue the plugin is made for tinymce v4 but i am using in tinymce v5 is there any way to use v4 plugins

**Comment by fyrkant** [comment]
Not without changing the plugin, I'm afraid.
