### ISSUE TITLE
react18 + tinymce/tinymce-react,  use image_caption and file_picker_callback

### ISSUE THREAD

**Issue by Lil-Kr** [tinymce/tinymce-react#524]
## about image_caption this function

* **they image not center aligned, but when I not using image_caption or set it value to false, then can center aligne**
* **or do I need to add css by self?**

![image](https://github.com/tinymce/tinymce-react/assets/50562423/c4caa4ee-969f-40af-b770-4ce82f8e9981)

![image](https://github.com/tinymce/tinymce-react/assets/50562423/e26a3e19-a555-45e7-881d-265992051be7)

-------

![image](https://github.com/tinymce/tinymce-react/assets/50562423/104cfbed-2a6b-41ec-b6a7-5d123bd0c765)

![image](https://github.com/tinymce/tinymce-react/assets/50562423/56d70d23-c92c-4007-b3e3-6c9740072984)

-----------

## About file_picker_callback function

* **I checked whit CodePen, and how to use the `const blobCache =  tinymce.activeEditor.editorUpload.blobCache;` this function in react 18(TTypeScript)**,  how I should be get the `tinymce`  object?
* **ref-link**: https://www.tiny.cloud/docs/tinymce/latest/image/
* **my git-repo link**: https://github.com/Lil-Kr/blog-system-single/blob/oh-router-change-base/react18-blog-admin/src/views/comps/tinymce/Tinymce.tsx

![image](https://github.com/tinymce/tinymce-react/assets/50562423/95b3b33f-72f2-414a-b90a-e189f383ef8d)

**env version**:  https://github.com/Lil-Kr/blog-system-single/blob/oh-router-change-base/react18-blog-admin/package.json

------

thanks so much !!!

**Comment by lorenzo-pomili** [comment]
I see that you link is no more available: https://github.com/Lil-Kr/blog-system-single/blob/oh-router-change-base/react18-blog-admin/src/views/comps/tinymce/Tinymce.tsx , I tried to use https://github.com/Lil-Kr/blog-system-single/blob/oh-router-change-base/react18-blog-admin/src/views/comps/tinymce/TinymceLocal.tsx instead but I'm not able to reproduce the bug with it.

Do you still have this bug? if so could you please post the step that are you doing to reproduce the bug and also an example affected by that bug?
