### ISSUE TITLE
About this.elementRef.current?.OwnerDocument.DefaultView question

### ISSUE THREAD

**Issue by hlongc** [tinymce/tinymce-react#528]
When I look at the source code, I have a question about the view value here, why pass `this.elementRef.current?.OwnerDocument.DefaultView` to obtain it and window for the most part are the same, but if the window after the Proxy agent, the two are not the same, what is the suitable scene is `ownerDocument.DefaultView`?

version: 4.3.0
file path：src/main/ts/components/Editor.tsx
<img width="634" alt="view" src="https://github.com/tinymce/tinymce-react/assets/23303556/172bdce5-e1ba-4937-8111-fcf6398508fa">

**Comment by danoaky-tiny** [comment]
Hi, would you be able to further clarify what your issue or question is?
