### ISSUE TITLE
Toolbar Sticky not working properly

### ISSUE THREAD

**Issue by rajraii** [tinymce/tinymce-react#529]
**What is the current behavior?**
Tinymce React Toolbar not working properly
There are following cases here:
1. Toolbar doesnt automatically sticks to top when scrolled down in content
![image](https://github.com/tinymce/tinymce/assets/71391631/3d9ac950-29be-4f7e-bfb8-6b9b125f4177)

![image](https://github.com/tinymce/tinymce/assets/71391631/0c2e1626-5d50-4ec0-ae59-af5f7a4b0982)

2. Toolbar only gets sticked to top when there is a click event inside content 
Reproduced this behaviour after pressing enter  inside content
![image](https://github.com/tinymce/tinymce/assets/71391631/eccb691b-a175-44e4-920d-dbeda1f29f87)

3. It will be sticked to top of the page even when user scrolls out of the content area 
![image](https://github.com/tinymce/tinymce/assets/71391631/7db1b254-e9bd-480c-b4ba-3119117ec59c)

4.  Selector option  in init json is not accepting a string value
![image](https://github.com/tinymce/tinymce-react/assets/71391631/2970108a-a603-4d86-a9b2-2e4c7c16ec47)

###NOTE:
I was able to identify the issue: 
The css in parent element consist of `overflow: auto`. Need to rectify it

**What is the expected behavior?**
Should have stick only to the top of content context (not at page) when users scrolls on page, Clicking or event should have not been the trigger here.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

- Browser: Chrome
- OS: Ubuntu
- First affected version: React Tinymce Version : 4.3.2
- Worked in version: React Tinymce Version : 4.3.2

**Comment by danoaky-tiny** [comment]
You're using the `selector` prop, which is purposely overridden and won't be used, see https://www.tiny.cloud/docs/tinymce/latest/react-ref/#init.

Apart from that, could you please fork our [code sandbox](https://codesandbox.io/p/sandbox/competent-cloud-yny726) to replicate your issue. Or provide a codepen or something similar. Then we can help you further.

**Comment by rajraii** [comment]
@danoaky-tiny In this demo, I have tried to replicate my behavior, Though I could not make the TinyMCE resizable according to the size of the content in it.
If you click inside the editor, the editor toolbar is sticky. But when you scroll outside of Editor then the behavior changes to Static

[Code Sandbox](https://codesandbox.io/p/sandbox/serene-wave-m8gydf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxa0n7hm00062v6iwmxmbgy6%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxa0n7hm00022v6ihgix7g4s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxa0n7hm00032v6i8rt6unhw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxa0n7hm00052v6iimtfnc1j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxa0n7hm00022v6ihgix7g4s%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxa0n7hl00012v6iyt0y36s9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxa0n7hm00022v6ihgix7g4s%2522%252C%2522activeTabId%2522%253A%2522clxa0n7hl00012v6iyt0y36s9%2522%257D%252C%2522clxa0n7hm00052v6iimtfnc1j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxa0n7hm00042v6ijipya1bh%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxa0n7hm00052v6iimtfnc1j%2522%252C%2522activeTabId%2522%253A%2522clxa0n7hm00042v6ijipya1bh%2522%257D%252C%2522clxa0n7hm00032v6i8rt6unhw%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxa0n7hm00032v6i8rt6unhw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Tinymce Tollbar is not sticky when parent has a `Overflow` styling in it**.

**Comment by andresmotiva** [comment]
I am having the same issue @rajraii 
- Sticky toolbar does not understand when I scroll back up and remains on top
- I am having also the issue of the toolbar having different behavior when editor is focused and blurred. 

Did you manage to make it work?

**Comment by rajraii** [comment]
@andresmotiva I was able to fix this issue with a hack, manually dispatching event `resize`
```
editor.on("LoadContent", function() {
         window.dispatchEvent(new Event('resize'))
}
```

Note: Loadcontent event fires before the painting, You can add a setInterval as well on it

**Comment by wr-andrewbarnhart** [comment]
@lorenzo-pomili This code sandbox should show the issues. There are two editors using `toolbar_sticky` inside a container with an `overflow` applied. The toolbars don't become sticky until interacting with the content in the editor (adding a newline is the easiest way). The second editor's toolbar is hidden until the same interaction occurs. Once the toolbars are visible and sticky they do not align to the correct position in the container but instead stick to the top of the viewport.

[Sandbox](https://codesandbox.io/p/sandbox/quirky-moser-r4fjp7?file=%2Fsrc%2Findex.tsx)

**Comment by lorenzo-pomili** [comment]
hi, to solve this problem you should add `ui_mode: "split"` to your `init`, this is the documentation of the [ui_mode](https://www.tiny.cloud/docs/tinymce/latest/ui-mode-configuration-options/#ui_mode), let me know if you still have the problem

**Comment by wr-andrewbarnhart** [comment]
@lorenzo-pomili Thank you that solves it. I can't believe I missed this in the docs.
