### ISSUE TITLE
Cursor jumps to the start when I start typing

### ISSUE THREAD

**Issue by arthurvanl** [tinymce/tinymce-react#530]
**What is the current behavior?**
Cursor jumps to the start of the content
I am using 5.0.1

Video:

https://cdn.discordapp.com/attachments/1233030809267474556/1243188454016422039/2024-05-23_15-06-13.mp4?ex=665090f8&is=664f3f78&hm=a35e5db9e2883f756c1b7c87b6c27fedcdcbba32ad4b8fc6615bea5a7ea1f22c&

**Comment by danoaky-tiny** [comment]
Unfortunately we can't access your discord link.

Could you please provide a codesandbox (or something similar) which replicates your issue. You can fork [our code sandbox](https://codesandbox.io/p/sandbox/competent-cloud-yny726) if you'd like. Then we're happy to help you further.

**Comment by u-rogel** [comment]
@arthurvanl I had a similar issue while I was passing the controlled `value` into `initialValue` prop. When I switched to use the `value` prop instead it got fixed. Also you can wrap your initial-value with `useMemo` then the initial-value passed will actually be static.
