### ISSUE TITLE
"@tinymce/tinymce-react": "^5.1.0" NOT FIND

### ISSUE THREAD

**Issue by zhengmenghuang** [tinymce/tinymce-react#535]
![image](https://github.com/tinymce/tinymce-react/assets/29627098/399f11a7-fee2-4ced-ab8d-60f7c997b6dc)

**Comment by ELHart05** [comment]
Same issue here!

**Comment by danoaky-tiny** [comment]
We've identified the issue and are working on a fix. Apologies for the inconvenience.

**Comment by danoaky-tiny** [comment]
Please use v5.1.1. This includes the built _/lib_.
