### ISSUE TITLE
Cannot find module '@tinymce/tinymce-react' or its corresponding type declarations

### ISSUE THREAD

**Issue by ELHart05** [tinymce/tinymce-react#536]
**What is the current behavior?**
Cannot find module '@tinymce/tinymce-react' or its corresponding type declarations

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/p/sandbox/tinymce-react-yny726?file=src/index.tsx) or similar.**
The code was working for months, now when I **npm i** whether locally or in the server, it says that the module not found, 
![image](https://github.com/tinymce/tinymce-react/assets/96151694/fca93ff5-76dc-496c-93b3-9c487a818048)
![image](https://github.com/tinymce/tinymce-react/assets/96151694/a1bc0d3b-e6d8-4ad7-8db8-c634b7b7c36b)
BY exploring the node_modules I found out that when installing the '@tinymce/tinymce-react' package it only installs informations, no content, code or exports to import!
![image](https://github.com/tinymce/tinymce-react/assets/96151694/de1aa669-03f4-4553-84fa-1c6a72509a29)

**What is the expected behavior?**
the package imported normally and work as it always worked before!

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
- "@tinymce/tinymce-react": "^5.1.0",
- Kali GNU/Linux Rolling x86_64
- Firefox 115.8.0

**Comment by danoaky-tiny** [comment]
We've identified the issue and are working on a fix. Apologies for the inconvenience.

**Comment by danoaky-tiny** [comment]
Please upgrade to v5.1.1. This includes the built _/lib_.
