### ISSUE TITLE
Can't find localization settings

### ISSUE THREAD

**Issue by liuningfr** [tinymce/tinymce-react#54]
I am a developer from China. I can't find a way to translate the toolbar into Chinese.
There is a localization settings in `tinymce`. (https://www.tiny.cloud/docs/general-configuration-guide/localize-your-language/)
But I don't know how to make it support Chinese in `tinymce-react`.
I will appreciate if you could give me some advice.

**Comment by fyrkant** [comment]
You will have to download the language files (from [here](https://www.tiny.cloud/get-tiny/language-packages/)) and use the [`language_url`](https://www.tiny.cloud/docs/configure/localization/#language_url) setting to link to the language file on your server, so something like this: 

```js
<Editor init={{ language_url: 'https://yourdomain.com/zh_CN.js' }} />
```
