### ISSUE TITLE
Textarea value lags behind editor content on submit

### ISSUE THREAD

**Issue by urugator** [tinymce/tinymce-react#55]
Reproduction:
https://codesandbox.io/s/7mkwnr21x0
1) Type "a" to editor
2) Hit Submit -> console output: `content: ""`
3) Hit Submit again -> console output `content: <p>a</p>`

Possibly related: https://github.com/tinymce/tinymce/issues/4702

EDIT:
I found out that  `triggerSave()` has to be called to propagate changes to textarea.
Meaning that I need to somehow obtain the editor instance in onSubmit handler:
```javascript
onSubmit(event) {
    const tinyMce = somehowGetInstance(); // by ID perhaps? is there better way?
    tinyMce.triggerSave();
    const formData = new FormData(event.target); // now the textarea should have proper value
}
```
Or I have to manage `FormData` manually (meaning that textarea is pretty useless):
```javascript
onSubmit(event) {
    const formData = new FormData(event.target); 
    formData.set('content', state.content); // or directly from instance
}
```
Is that correct? Is there a better way to make use of the textarea for ajax request?

EDIT2:
So far I ended up with:
```javascript
el('input', { type: 'hidden', name: 'mainContent', value: fields.mainContent.value }),
el(TinyMce.Editor, {
   value: fields.mainContent.value,
   onEditorChange: value => onEditorChange('mainContent', value),
}),
```

**Comment by fyrkant** [comment]
Instead of depending on the textarea value I'd just use react state like this: https://codesandbox.io/s/qvqyy14wq4

**Comment by urugator** [comment]
I do have a backing state, but during submit I want to avoid the need to manually building the request from the state. The form also contains file inputs, so I still have to reach out for these directly. I would end up reimplementing exactly the same logic as `new FormData(event.target)` already does.

I can live with the solution shown in "EDIT2" as it can be quite easily abstracted away.
However I wonder why the texarea isn't immediately updated on every change, performance reasons I suppose? I presume there isn't anything that could be done about that (?).

 Feel free to close the issue.

**Comment by fyrkant** [comment]
You could do something like this: https://codesandbox.io/s/k5wvkj8j67

**Comment by urugator** [comment]
Yea, but that's not much of an improvement is it? I have to manually maintain the reference for each editor instance and pass it to onSubmit handler...
Thanks for the suggestion though.
