### ISSUE TITLE
how to update the initialValue?

### ISSUE THREAD

**Issue by ChiaJune** [tinymce/tinymce-react#6]
thank you for providing such a great react implementation!
And how to update the data(initialValue) when the editor has instantiated?

**Comment by Cedric-locchi** [comment]
hello, I am in the same case, I cant update initValue with my new state.

**Comment by ChiaJune** [comment]
@Cedric-locchi 
i found a way, [setContent](https://www.tinymce.com/docs/api/tinymce/tinymce.editor/#setcontent), you can use it with the `componentWillReceiveProps`

**Comment by Cedric-locchi** [comment]
but how to access at the Editor component from componentWillReceiveProps? i'm new with react...

**Comment by ChiaJune** [comment]
@Cedric-locchi you can use [ref](https://reactjs.org/docs/refs-and-the-dom.html) to get the instance of the editor

**Comment by Cedric-locchi** [comment]
hello, no feedback for the issue? I can't change the info inside my editor for update

**Comment by fyrkant** [comment]
I'm off work for the holidays, I'll be back on Tuesday the 2nd.

**Comment by fyrkant** [comment]
@Cedric-locchi Can you give me some more info on what you are trying to do? Are you trying to update the content in the editor? You could just use the tinymce setContent like @ChiaJune says above, either using `tinymce.activeEditor.setContent('your content')` if you only have one active editor, or `tinymce.get('id_of_your_editor').setContent('your content')` if you have more than one. 

Not sure how you would use the `ref` to get the editor instance, @ChiaJune can you show how you solved it?

**Comment by Cedric-locchi** [comment]
I tried this, but it does not work properly, the data is displayed and hidden in stride.
my ref:
```js
    ref={(editor) => { this.editor = editor }}
```
and y use in componentDidMount or componentWillreceiveProps like this
 ``` js
    this.editor.editor.setContent(this.props.event.description);
```

**Comment by ChiaJune** [comment]
@fyrkant I'm sorry, I did not solve this problem well. Finally, I used the [react-tinymce-input](https://github.com/HurricaneJames/react-tinymce-input), but it's not perfect. I get an error when refreshing the browser...:sob::sob:

**Comment by Cedric-locchi** [comment]
i have this error now...

```js
   Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'e.parser.parse')
```

**Comment by fyrkant** [comment]
If you are using the lastest `v2.1.1` of the package you can do like this:

```js
<Editor
  init={{
    setup: editor => {
      this.setState({activeEditor: editor})
  }}
  initialValue='<p>howdy</p>'
/>
```

And simply save the active editor in the parent component state and then use `this.state.activeEditor.setContent`. 

But why you are changing the content in the editor after intialisation? It should work but the cursor position will probably be messed up... Could you two give me some more info on what you are trying to do?

**Comment by Cedric-locchi** [comment]
I would like to recover a content already created to edit it, modify the content and update the info in the database

**Comment by fyrkant** [comment]
The easiest way to get the editor might just be to set an id on the component, so `<Editor id="my-id" />` and then use `tinymce.get('my-id')` to get a hold of the editor instance and run `setContent` on it.

**Comment by fyrkant** [comment]
You can now [use the Editor as a controlled component](https://github.com/tinymce/tinymce-react#using-as-a-controlled-component).

**Comment by RunningEgg** [comment]
> I would like to recover a content already created to edit it, modify the content and update the info in the database

@Cedric-locchi you must have found your solution by now, but wanted to answer for others.
Like answers above, use `tinymce.activeEditor.setContent('your content')` or `tinymce.get('id_of_your_editor').setContent('your content')` to set editor content .
To get the content of open editor use `tinymce.activeEditor.getContent()` or `tinymce.get('id_of_your_editor').getContent()` .
