### ISSUE TITLE
Provide the typescript types to use in props

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#63]
I have a project that is written in TypeScript and I need to type a component with the props based on TinyMCE. I'm not finding the exported types.

Is there a way to provide them?

Thanks

**Comment by SimonFc** [comment]
Hi,
The Typescript prop types are now being exported in version 3.1.1. Hope this helps!
```
import { Editor, IAllProps } from '@tinymce/tinymce-react';
```
