### ISSUE TITLE
How do i ajax save?

### ISSUE THREAD

**Issue by oren-gershoni** [tinymce/tinymce-react#73]
using the save plugin i want the button/key-shortcut to trigger an ajax save (instead of the normal form submit)
in normal, none-react tinymce using "save_onsavecallback"  works 

```
 tinymce.init({
            selector: "#editor", 
            plugins: "save",
            toolbar: "save",
            save_onsavecallback: function () {
                console.log('no submit');
                // do what i want here
            }
        });
```

it reaches the callback and prevents a submit,
however in the react package using either "onSaveContent" or "onSubmit" does not provided the same result...
what should i do?

**Comment by SimonFc** [comment]
The events that are provided by the React integration are not the same as the callbacks certain plugins provide, like `save_onsavecallback`. Meaning you would do it in the same way with tinymce-react as you would do with just tinymce:
```
<Editor
  init={{
    save_onsavecallback: function (editor) {
        console.log('no submit');
    }
  }}
/>
```
