### ISSUE TITLE
Unable to select the text in editor if it is set to readonly mode

### ISSUE THREAD

**Issue by jagusanju** [tinymce/tinymce-react#76]
**What is the current behavior?**
Unable to select the text in editor if it is set to readonly mode
**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**
setMode to readonly on initializing the editor
 setup: function(editor) {   
      editor.setMode('readonly');    
    }
**What is the expected behavior?**
Should allow user to select the text
**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
Chrome browser
"@tinymce/tinymce-react": "2.2.5",

**Comment by SimonFc** [comment]
What version of TinyMCE are you using? There was a bug with selection and read-only mode but that was fixed in 5.0.6.

Closing this since it's working with the latest version [codesandbox](https://codesandbox.io/s/tinymcereact-wslpw?fontsize=14)

**Comment by jagusanju** [comment]
I think its fixed in the latest version I was seeing the issue in 4.9
