### ISSUE TITLE
Can't find mentions plugin

### ISSUE THREAD

**Issue by plainnany** [tinymce/tinymce-react#77]
```
import { Editor } from '@tinymce/tinymce-react';
import  'tinymce/plugins/mentions'

<Editor
  apiKey="API_KEY"
  init={{ plugins: 'link table mentions' }}
/>
```
I find docs about [mentions](https://www.tiny.cloud/docs/plugins/mentions/#), I add some code like above,  It doesn't work, I can't find metions file  in node_modules -> _tinymce@5.0.5 -> plugins , How do I use mentions plugin in tinymce-react?

**Comment by SimonFc** [comment]
That is due to the mentions plugin being a premium feature. If you're using Cloud it would be easy for you to enable it. You can read more about it [here](https://apps.tiny.cloud/products/atmention/). Let me know if you got any questions.
