### ISSUE TITLE
table_default_attributes not working as expected? 

### ISSUE THREAD

**Issue by brymon68** [tinymce/tinymce-react#84]
Package.json 
```
"@tinymce/tinymce-react": "^2.5.0",
```

Can someone provide an example of how to use the table_default_attributes object in init of TinyMCE-react component? 

I have tried something like: 
```
<TinyMCE
    init={{
        table_default_attributes: {
            border: "5",
         }
     }}
 />
```
But border thickness does not change. Any ideas how to get this to work?

**Comment by SimonFc** [comment]
It works alright for me, [CodeSandbox](https://codesandbox.io/s/tinymcereact-ct8ci?fontsize=14). Can you see what's different?
1. Insert -> Table
2. The inserted table will have a border attribute set to 5

**Comment by brymon68** [comment]
@SimonFc  thank you for the codesandbox example. I believe I misunderstood the intended behavior of table_default_attributes and and I should have better explained my usecase. Typically, my team's workflow is to paste table data from another source into the TinyMCE editor.  they do not build the table from scratch in TinyMCE. 

Once my team pastes the table data into the editor, they have to click the table, then go to Table > Table Properties to change border, cellspacing, etc. They do this every time they paste table data into the editor. 

Off the top of your head, do you know if these default configurations can be programmatically set?

**Comment by SimonFc** [comment]
No worries! If you're using the paste plugin I think using [paste_postprocess](https://www.tiny.cloud/docs/plugins/paste/#paste_postprocess) might work for you. Perhaps something like [this](https://codesandbox.io/s/tinymcereact-pygp5?fontsize=14)

**Comment by brymon68** [comment]
Literally exactly what I was looking for @SimonFc. Thanks so much for your help!

**Comment by SimonFc** [comment]
Great that it's working for you!
