### ISSUE TITLE
Readme example not working: Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode.

### ISSUE THREAD

**Issue by Jack-Collins** [tinymce/tinymce-react#85]
**What is the current behavior?**

console contains this message.

```Failed to initialize the editor as the document is not in standards mode. TinyMCE requires standards mode.```

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

Following the example in the README

**What is the expected behavior?**

Editor should initialise.

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**

```+ @tinymce/tinymce-react@3.3.1```

Google Chrome.

**Comment by lnewson** [comment]
This is not a bug and it's likely you're missing the doctype declaration in your root HTML file (`<!DOCTYPE HTML>`), as TinyMCE doesn't support running in quirks mode as mentioned here: https://www.tiny.cloud/docs/general-configuration-guide/system-requirements/

You'll see it works as expected in the CodePen linked in your issue.

**Comment by lnewson** [comment]
I should add if you can provide a CodePen where it fails when actually running in standards mode, then we're more than happy to reopen this.

**Comment by FelixNiedermann** [comment]
I got the same problem but I have DCOTYPE devlared
