### ISSUE TITLE
TinyMCE version for react 15.4.2 

### ISSUE THREAD

**Issue by filhefor** [tinymce/tinymce-react#86]
Hi, we are working on a react application with version 15.4.2. We have the same problem as #3 and unfortunately it is not possible for us to upgrade to 16+ because of our customer's policy. Is there a version of tinymce and its react component which works with react 15.4.2? If not, do you happen to know of any other rich text editor that you think would work with our react version?

Best regards,
Filip

**Comment by SimonFc** [comment]
Hi Filip,
I'm going to look into what extend tinymce-react works with React 15 and if we should possible support more versions than we do now.  But for now it looks like it's possible to initialize tinymce-react 3.2.0 works with React 15.4.2 at least. [CodeSandbox](https://codesandbox.io/s/tinymcereact-6nr0s?fontsize=14).

**Comment by filhefor** [comment]
@SimonFc Thank you for your answer. We will try it with 3.2.0 on monday

**Comment by filhefor** [comment]
We got it working now. Thanks.
