### ISSUE TITLE
Provide an event type on `onEditorChange` prop

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#87]
**Is your feature request related to a problem? Please describe.**
The Editor react component provides a prop called `onEditorChange` and it fires when a change occurs in the editor.  
**The problem:** when the change occurs I don't know which event occured. eg.: blur, change, focus, etc.  
I have some situations that I need to send a API request only when the text has changed, but the `onEditorChange` prop does not provide an argument especifying the event type.

 **Describe the solution you'd like**
The `onEditorChange` prop should provide a new argument telling the event type.  
`onEditorChange={(text, editor, event)}`

 **Describe alternatives you've considered**
Is there a way to detect the event type using the second argument `editor` provided by the `onEditorChange` prop?

**Comment by SimonFc** [comment]
Hi @vctormb 
I think that the simplest thing you could to do, other than providing event handlers for all the events that you're interested in via props such as onKeyPress, is to bind to multiple events via the [editor.on](https://www.tiny.cloud/docs/api/tinymce.util/tinymce.util.eventdispatcher/#on) method. You could do it like `editor.on('keypress paste undo redo', () => {});`

I think that adding a new argument specifying the type would be difficult to do and maybe a bit confusing. Let's say that we have a custom plugin with a new custom paste event, `pastex2` or something. We could expect this plugin to fire the change event as well(by adding an undo level) that tinymce-react listens to [here](https://github.com/tinymce/tinymce-react/blob/master/src/main/ts/components/Editor.tsx#L127) but we would have no way of knowing of this `pastex2` event.

My thinking is that even if we somehow did provide the event type to onEditorChange it would always be lacking so I think it's best to leave it as it is and use one of the alternatives I mentioned earlier.

**Comment by SimonFc** [comment]
Also, doesn't onEditorChange only fire when the text of the editor has changed? The blur or focus events shouldn't affect it :thinking:

**Comment by vctormb** [comment]
> Also, doesn't onEditorChange only fire when the text of the editor has changed? The blur or focus events shouldn't affect it 🤔

Exactly! When `onBlur` occurs the `onEditorChange` prop is called! That's why I'm facing this issue! 😞

**Comment by SimonFc** [comment]
In what scenario? [CodeSandbox](https://codesandbox.io/s/tinymcereact-erx89?fontsize=14)
1. Focus editor
2. Unfocus(blur)
Result: Only onBlur is fired

1. Focus editor
2. Type
Result: Only onEditorChange is fired

**Comment by vctormb** [comment]
> In what scenario? [CodeSandbox](https://codesandbox.io/s/tinymcereact-erx89?fontsize=14)
> 
> 1. Focus editor
> 2. Unfocus(blur)
> 
> Result: Only onBlur is fired
> 
> 1. Focus editor
> 2. Type
> 
> Result: Only onEditorChange is fired

It worked! I was using the `3.1.1` version. But I've found another problem.  
If I type something and click outside of the editor the `onBlur` will trigger the `onEditorChange`.

**Comment by henriquecaraujo** [comment]
Dispatches the change event when type and blur it's a native DOM API behaviour: [CodeSandbox vanilla change event](https://codesandbox.io/s/intelligent-goldberg-lfki2)
@vctormb  maybe an onKeyPress event should solve your problem

**Comment by henriquecaraujo** [comment]
> > Dispatches the change event when type and blur it's a native DOM API behaviour: [CodeSandbox vanilla change event](https://codesandbox.io/s/intelligent-goldberg-lfki2)
> > @vctormb maybe an onKeyPress event should solve your problem
> 
> I guess it won't trigger some events when I apply some style using the toolbar, backspace, etc.

Houston, we have a problem

**Comment by SimonFc** [comment]
> I guess it won't trigger some events when I apply some style using the toolbar, backspace, etc.
@vctormb  This sounds like a bug/bugs with TinyMCE. What operations are you having issues with?

**Comment by vctormb** [comment]
> > I guess it won't trigger some events when I apply some style using the toolbar, backspace, etc.
> 
> @vctormb Sounds like there could be a problem with TinyMCE. What operations are you having issues with?

Yes. Well, `onEditorChange` prop should not trigger when `onBlur` occurs. That's the problem that I'm facing right now.

**Comment by SimonFc** [comment]
Yeah I see what you mean. Even though it's native behavior to fire the change events on blur, onEditorChange should be restricted to only fire when the content actually changes. I'll re-open this issue, no need to create a new one!

**Comment by SimonFc** [comment]
This has been fixed in 3.3.2. Let me know if you encounter any issues!
