### ISSUE TITLE
Cursor jump back to start when pressed ENTER

### ISSUE THREAD

**Issue by gitsuraj** [tinymce/tinymce-react#88]
**What is the current behavior?**
When user press enter the cursor goes back to beginning or editor

**Please provide the steps to reproduce and if possible a minimal demo of the problem via [codesandbox.io](https://codesandbox.io/s/6yz4jzrrxw?fontsize=14) or similar.**

https://drrkq.csb.app/
https://codesandbox.io/s/tinymcereact-drrkq

I have a list of items and displaying those items in drawer. If I change value into initialValue the issue resolves but even I select different item it's content won't update.

**What is the expected behavior?**
We should just get new line form the point where cursor is located

**Which versions of TinyMCE, and which browser / OS are affected by this issue? Did this work in previous versions of TinyMCE or `tinymce-react`?**
inymce-react - 1.3.2

**Comment by SimonFc** [comment]
You're using tinymce-react as a controlled component and when doing so you should use the onEditorChange event instead of the onChange event. Read more [here](https://github.com/tinymce/tinymce-react#using-as-a-controlled-component)

I modified your [example](https://codesandbox.io/s/tinymcereact-970e7?fontsize=14) to do so.

**Comment by IsmaelEzequiel** [comment]
> You're using tinymce-react as a controlled component and when doing so you should use the onEditorChange event instead of the onChange event. Read more [here](https://github.com/tinymce/tinymce-react#using-as-a-controlled-component)
> 
> I modified your [example](https://codesandbox.io/s/tinymcereact-970e7?fontsize=14) to do so.

YOU'RE THE BEST!!!
