### ISSUE TITLE
Table plugin - columns and lines not resizable 

### ISSUE THREAD

**Issue by MailColibri** [tinymce/tinymce-react#9]
Nice Job for react implementation!
Regarding the table plugin we can resize it but not his columns.
May be a problem with @ ephox/snooker and react.

**Comment by fyrkant** [comment]
Hi! 
Thank you for this issue, I'll take a look at it today.

**Comment by fyrkant** [comment]
I'm having problems reproducing this, can you share some more details on your implementation, maybe set up a minimal test setup in a repo and let me take a look?

**Comment by fyrkant** [comment]
No response so I'm closing this.
