### ISSUE TITLE
Provide a utils to mock the Editor instance in Jest

### ISSUE THREAD

**Issue by vctormb** [tinymce/tinymce-react#91]
**Is your feature request related to a problem? Please describe.**
I'm trying to test my app with Jest that depends on TinyMCE editor.  
The problem is that when I run my tests with React Testing Library, the editor `init_instance_callback` is not called, and I need it to be called to alocate the editor instance inside the useState(). Maybe the Iframe has some delay?

 **Describe the solution you'd like**
Provide a mock to mock the editor in Jest or a good example on how to do it.

 **Describe alternatives you've considered**
Is there a way to mock the Editor in Jest and make the `init_instance_callback` be called? Is there a clear example in some repository?

**Comment by SimonFc** [comment]
Hmm I think that should work just fine. Is TinyMCE being loaded in your tests? There might be some delay if you load via Cloud, just speculation though. For testing of tinymce-react itself we
1. [Import tinymce](https://github.com/tinymce/tinymce-react/blob/ccd70c717a800150fc4df66079ac66900bb06e98/src/test/ts/alien/Loader.tsx#L6)
2. Initialize the editor with a [base_url](https://github.com/tinymce/tinymce-react/blob/ccd70c717a800150fc4df66079ac66900bb06e98/src/test/ts/alien/Loader.tsx#L31) (the project prefix is something that's specific to our testing framework)
3. Wait for the [UI to load](https://github.com/tinymce/tinymce-react/blob/ccd70c717a800150fc4df66079ac66900bb06e98/src/test/ts/alien/Loader.tsx#L35) with the SkinLoaded event before starting the actual tests, but you using `init_instance_callback` might work just fine as well but I'm not sure if you can be certain that the UI had loaded at that point though.

There's a lot of testing-framework specific code in that file but I think that about covers it

**Comment by vctormb** [comment]
@SimonFc Do you have any examples on how to do it in React Testing Library ou similiar library? In RTL I'm waiting the editor container be loaded in the DOM, but it never loads.

**Comment by SimonFc** [comment]
No unfortunately not. I haven't used React Testing Library but isn't it using JSDOM or something or something similar under the hood? Makes me think that perhaps that is what causes TinyMCE to not load/setup.

Without an example of what your test looks like it's very difficult to say what the issue might be. I suspect that TinyMCE itself somehow isn't being loaded, and as such the tinymce-react wrapper itself  wont initialize the editor.

**Comment by vctormb** [comment]
@SimonFc Yes, it uses JSDOM. Here's a simple failing test using RTL and TinyMCE. https://github.com/vctormb/tinymce-rtl

**Comment by SimonFc** [comment]
Did you get past #61 ?
Perhaps related to [this](https://github.com/jsdom/jsdom#loading-subresources).Try disabling skin css loading by setting `skin: false` in your init option. Like I mentioned in the other issue though jsdom isn't supported by TinyMCE so there could be any number if issues that prevents it from working now.

**Comment by SimonFc** [comment]
Disable theme loading by setting `theme: false`, essentially running tiny in headless mode. I tried that with your example repo and it worked better(I suppose) but it failed on the same thing as in #61 

I'll close this as jsdom isn't anything that we're planning on supporting
