### ISSUE TITLE
MoxieManager on React Tinymce

### ISSUE THREAD

**Issue by khoaanh2212** [tinymce/tinymce-react#97]
I have a situation which i must use MoxieManager,but for now we don't have it on React Tinymce.
So i really need all of your help to bring MoxieManager into React Tinymce.

Thanks

**Comment by SimonFc** [comment]
You should be able to integrate it with TinyMCE in the same manner as if you weren't using React as described [here](https://www.moxiemanager.com/demos/tinymce.php). What issues are you encountering?

**Comment by khoaanh2212** [comment]
Hi @SimonFc 
the plugin package of MoxieManager is build for PHP now,so i can not integrate it into React Tinymce

**Comment by SimonFc** [comment]
That should not matter as everything client side is JavaScript, including MoxieManager. I'm guessing that you're having issues with serving the MoxieManager-plugin. What step of the instructions are you having issues with? Perhaps the [TinyMCE Installation](https://www.moxiemanager.com/documentation/index.php/Installation_php) section?

**Comment by khoaanh2212** [comment]
yes @SimonFc .i have problem when call Auth via MoxieManager from Frontend.

**Comment by SimonFc** [comment]
At this point I think it's best that you contact our support since MoxieManager is a premium feature and this doesn't seem to be an issue related to our React integration. You can contact them via: https://support.tiny.cloud/hc/en-us/requests/new
